### ISSUE TITLE
Year in release date for 2019 year' releases is incorrect

### ISSUE THREAD

**Issue by arestarh** [aws/aws-tools-for-powershell#1]
Hi,

Starting from _aws-tools-for-powershell_ version **3.3.450.0** year in release date is **2018** and seems like should be changed to 2019.

**Comment by sstevenkang** [comment]
Ah.  good catch.  :)  We'll address this.

**Comment by matteo-prosperi** [comment]
Thank you for reporting this issue. I have fixed the dates.
