### ISSUE TITLE
AWSPowerShell: When Possible, Cmdlets Should Fail Immediately if a Region is not Specified.

### ISSUE THREAD

**Issue by bgshacklett** [aws/aws-tools-for-powershell#10]
## Expected Behavior
If a Cmdlet which requires a region is executed and no region is specified, either by persistent means, shell defaults, or parameter, the Cmdlet should throw an error.

## Current Behavior
The Cmdlet will hang for 15 seconds. Some Cmdlets (`Get-CfnStackResource`, for instance) cannot be killed with `^C`
```
> measure-command {get-ec2instance}
...
get-ec2instance : No region specified or obtained from persisted/shell
defaults.
...
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 15
Milliseconds      : 820
Ticks             : 158205674
TotalDays         : 0.000183108418981481
TotalHours        : 0.00439460205555556
TotalMinutes      : 0.263676123333333
TotalSeconds      : 15.8205674
TotalMilliseconds : 15820.5674
```

## Possible Solution
Unfortunately, I don't have the visibility into why the current behavior exists, which makes it difficult for me to suggest a resolution. I would, however, suggest keeping "fail fast" in mind.

## Steps to Reproduce (for bugs)
1. Ensure that no region is configured via persisted or shell default mechanisms
1. Initialize the authentication variables
    * `AWS_SESSION_TOKEN`  
    * `AWS_ACCESS_KEY_ID`
    * `AWS_SECRET_ACCESS_KEY`
1. Run `Get-Ec2Instance` with no parameters.

## Context
If I forget to specify a region, it can be up to 15 seconds for the command to time out and allow me to fix my mistake. Fast iteration on command execution is impeded, and it causes frustration.

## Your Environment
Platform      : Win32NT
ServicePack   : 
Version       : 10.0.14393.0
VersionString : Microsoft Windows NT 10.0.14393.0
                                   
PSVersion                      5.1.14393.1480                                
PSEdition                      Desktop                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.1480}     
BuildVersion                   10.0.14393.1480                               
CLRVersion                     4.0.30319.42000                               
WSManStackVersion              3.0                                           
PSRemotingProtocolVersion      2.3                                           
SerializationVersion           1.1.0.1

**Comment by ashishdhingra** [comment]
Hi @bgshacklett,

Good afternoon.

I was going through the backlog and came across this issue. As mentioned in the https://github.com/aws/aws-tools-for-powershell/issues/10#issuecomment-319796231, region detection involves searching in the predefined locations. I'm not sure of a work around which would disable EC2 Instance Metadata search at this stage. Hope this helps.

Please confirm if could close this issue.

Thanks,
Ashish

**Comment by bgshacklett** [comment]
Seems like there's no easy fix. Thanks for looking into it. I'm onboard with closing it out.

**Comment by sgupta07** [comment]
AWSpowershell retries 3 times for all command ? is there we can change this setting like aws cli ?
