### ISSUE TITLE
new cmdlet for S3 ListObjectsV2 API 

### ISSUE THREAD

**Issue by hop317** [aws/aws-tools-for-powershell#119]
https://docs.aws.amazon.com/powershell/latest/reference/items/Get-S3Object.html it states "We recommend that you use the newer version, ListObjectsV2, when developing applications.” However, I do not see how to configure the powershell cmdlet to make a ListObjectsV2 request instead of V1.

I suggest creating a Get-S3ObjectV2 cmdlet that uses the ListObjectsV2 API https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

**Comment by ashishdhingra** [comment]
This is fixed in [AWS.Tools.S3 4.1.13.0](https://www.powershellgallery.com/packages/AWS.Tools.S3/4.1.13.0).
