### ISSUE TITLE
Feature Request: Make 'Service' parameter positional for Get-AWSService

### ISSUE THREAD

**Issue by ketanbhut** [aws/aws-tools-for-powershell#121]
Provide a general summary of the issue in the Title above.

**Expected Behavior**

Get-AWSService cw # returns similar results to Get-AWSService -Service cw

**Current Behavior**

Get-AWSService cw # returns error A positional parameter cannot be found ..

**Possible Solution**

Modify  GetAWSServiceCmdlet to add   Position=0 for Service parameter

**Steps to Reproduce (for bugs)**

Search for any module without -Service

**Context**

It is very frequent to search for module names when you have to work for a new set of Cmdlets for which you don't have module installed. -Service being the only parameter, it should be ok to make it positional. 

**Your Environment**

Include as many relevant details about the environment where the bug was discovered.
* Affected module _AWS.Tools.*_): 
* Module version as reported by `Get-AWSPowerShellVersion`: Version 4.0.2.0
* Operating System and version as reported by `$PSVersionTable.OS`: Microsoft Windows 10.0.17763
* PowerShell version as reported by `$PSVersionTable.PSEdition`: Core

**Comment by ashishdhingra** [comment]
Requires change in `GetAWSServiceCmdlet` class in https://github.com/aws/aws-tools-for-powershell/blob/master/modules/AWSPowerShell/Common/DiscoveryCmdlets.cs

**Comment by ashishdhingra** [comment]
This is fixed in [AWS.Tools.S3 4.1.13.0](https://www.powershellgallery.com/packages/AWS.Tools.S3/4.1.13.0).
