### ISSUE TITLE
Set-AWSSamlRoleProfile -StoreAllRoles Issue

### ISSUE THREAD

**Issue by atscomposer** [aws/aws-tools-for-powershell#123]
Set-AWSSamlRoleProfile -StoreAllRoles does not store all roles for all profiles associated with the account running the command.  Is there a limitation on how many accounts/roles can be returned using this command?  My company has over 130 accounts created using the same process but I only see 123 roles when running this command.

**Comment by klaytaybai** [comment]
We couldn't identify a reason for a hard limitation.  We're curious if some of the profiles are invalid for some reason. What is your process for creating each profile?
