### ISSUE TITLE
 Get-HSM2ResourceTag MaxResults Error

### ISSUE THREAD

**Issue by amarbut24** [aws/aws-tools-for-powershell#124]
When running  Get-HSM2ResourceTag I'm getting below error

`System.InvalidOperationException: MaxResults for ListTags cannot currently support any value
other than 50. Please set it to 50 if provided. --->
Amazon.CloudHSMV2.Model.CloudHsmInvalidRequestException: MaxResults for ListTags cannot
currently support any value other than 50. Please set it to 50 if provided. --->
Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400)
Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad
Request.`

No matter how I run the command I get that error

` Get-HSM2ResourceTag - ResourceID $ID`
` Get-HSM2ResourceTag - ResourceID $ID -MaxResults 50`
` Get-HSM2ResourceTag - ResourceID $ID -MaxResults "50"`

I've also tried giving `-MaxResults` various numbers to no avail

I am running module version = 4.0.2.0
PowerShell version = 5.1.14393.3471

I've ran the `aws cloudhsmv2 list-tags` command and am able to retrieve the tags

**Comment by matteo-prosperi** [comment]
Hello,
Thanks for reporting this.
I am able to reproduce the issue and I am working on a fix.

**Comment by matteo-prosperi** [comment]
Hello,
thanks again for reporting the issue. It should be fixed in version 4.0.4.0.

**Comment by amarbut24** [comment]
Awesome!! Thanks for your help on this one.
