### ISSUE TITLE
Support for setting BillingMode on New-DDBTable to OnDemand mode at creation time

### ISSUE THREAD

**Issue by hao-public** [aws/aws-tools-for-powershell#129]
When creating a new DynamoDB table with the New-DDBTable cmdlet, you cannot create it with PAY_PER_REQUEST/OnDemand mode, but have to first create the table with provisioned Read and Write capacity and then use Update DDBTable afterwards to change to OnDemand billingmode. Reprovisioning the table to OnDemand mode takes several minutes.

The AWS CLI supports creating DynamoDB tables with OnDemand mode at creation time - the PowerShell cmdlet New-DDBTable should also be able to do this.

* Affected module AWSPowerShell.NetCore
* Module version: 4.0.1.1
* Operating System: Microsoft Windows 10.0.17763
* PowerShell version: Core

**Comment by klaytaybai** [comment]
Thanks for the feedback

**Comment by ashishdhingra** [comment]
This should be fixed in [AWS.Tools.DynamoDBv2 4.1.18.0](https://www.powershellgallery.com/packages/AWS.Tools.DynamoDBv2/4.1.18.0).
