### ISSUE TITLE
Get-ELB2LoadBalancer returning "Pagination is not supported" when specifying Name parameter

### ISSUE THREAD

**Issue by chris-peterson** [aws/aws-tools-for-powershell#13]
Latest version of `AWSPowerShell.NetCore` does not allow getting an ALB by name (`Get-ELB2LoadBalancer -Name ...`)

**Expected Behavior**
Get load balancer object (or an error if the ALB does not exist)

NOTE: the latest version of aws cli works as expected:
`aws elbv2 describe-load-balancers --names 'my-alb-name'`

**Current Behavior**
This error is always returned:
`Pagination is not supported when specifying load balancers`

I have tried tweaking other parameters like `Marker`, `PageSize`, but can't find a workaround.

**Steps to Reproduce**
```
PS> Get-ELB2LoadBalancer -Name 'my-alb-name'
Get-ELB2LoadBalancer : Pagination is not supported when specifying load balancers
```

**Context**
This is a blocker for our deployments as we use ALBs to track state (enumerate currently running infrastructure, do a blue-green deployment, and then remove old resources)

NOTE: this worked in `3.3.485.0` (and earlier).

**Your Environment**
* Affected module:
`AWSPowerShell.NetCore`
* Module version: 
`Version 3.3.498.0`
* Operating System and version:
`Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64` 
* PowerShell version:
`Core (6.1.0)`

**Comment by matteo-prosperi** [comment]
Thank you for reporting this issue. It will be solved in the next release of the module.

**Comment by matteo-prosperi** [comment]
We release 3.3.509 today, this problem should be fixed. Please reopen the issue in case of any problem.

**Comment by chris-peterson** [comment]
Confirmed its fixed -- thanks for the quick resolution!
