### ISSUE TITLE
Samples request for Get-EC2Tag

### ISSUE THREAD

**Issue by matteo-prosperi** [aws/aws-tools-for-powershell#131]
See https://github.com/aws/aws-tools-for-powershell/issues/59#issuecomment-587266324

Also in `-Filter @{Name="xxx";Value="yyy"}`, `Value` should be changed to `Values`.

**Comment by ashishdhingra** [comment]
Example at https://docs.aws.amazon.com/powershell/latest/reference/items/Get-EC2Instance.html appears to be updated.
