### ISSUE TITLE
Unclear Confirm message from Install-AWSToolsModule

### ISSUE THREAD

**Issue by FireInWinter** [aws/aws-tools-for-powershell#132]
**Expected Behavior**
If I run:
Install-AWSToolsModule -Name AWS.Tools.S3 
I would expect to get a Confirm message like:
```Confirm
Are you sure you want to perform this action?
Performing the operation "Install-AWSToolsModule" on target "Version '4.0.4.0' of module 'AWS.Tools.S3'".
```

**Current Behavior**
Instead we get the message that really doesn't tell you anything other than it is trying to install something from AWS, but you can't tell what.
```
Confirm
Are you sure you want to perform this action?
Performing the operation "Install-AWSToolsModule" on target "AWS Tools version 4.0.4.0".
```

**Possible Solution**
Just have it modeled on the Confirm message of Install-Module as it makes a lot more sense.

**Steps to Reproduce (for bugs)**
Running on AWS Linux with PowerShell core 7.0rc2
Ran:
Install-Module AWS.Tools.Installer
Import-Module AWS.Tools.Installer
Install-AWSToolsModule -Name AWS.Tools.S3

**Comment by klaytaybai** [comment]
Thanks for the feedback

**Comment by ashishdhingra** [comment]
Hi @FireInWinter,

Good evening.

Looking this issue at high level, it appears to be a simple change. However, there is an ambiguity if you try to install multiple modules using the single command, e.g., `Install-AWSToolsModule -Name AWS.Tools.S3,AWS.Tools.EC2`. What should be the behavior in this case? We can install multiple modules and listing each line for each module could pollute the interactive output. Please help revalidate your requirement. 

Thanks,
Ashish
