### ISSUE TITLE
ADFS setup works only on windows

### ISSUE THREAD

**Issue by carathorys** [aws/aws-tools-for-powershell#134]
Provide a general summary of the issue in the Title above.

https://docs.aws.amazon.com/powershell/latest/userguide/saml-pst.html
Following this guide, I've tried to set up SAML authentication on Mac OS 10.15.3 to use ADFS authentication. 

If you're describing a bug, tell us what should happen. If you're suggesting a change/improvement, tell us how it should work.

When I'm trying to use `Set-AWSSamlEndpoint` or `Set-AWSSamlRoleProfile` cmdlet I'm getting the following error: 
```
Set-AWSSamlEndpoint : The encrypted store is not available.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded.
At script.ps1:24 char:11
+ $epName = Set-AWSSamlEndpoint -Endpoint $AdFsUri -AuthenticationType  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Set-AWSSamlEndpoint], AmazonClientException
+ FullyQualifiedErrorId : Amazon.Runtime.AmazonClientException,Amazon.PowerShell.Common.SetSamlEndpointProfileCmdlet
```

If describing a bug, tell us what happens instead of the expected behavior.
Include full errors, uncaught exceptions, stack traces, and relevant logs.
If service responses are relevant, please include Fiddler-captured wirelogs.
If suggesting a change/improvement, explain the difference from current behavior.

I've tried to dig into this, and I gave up digging in the AWSSDK (_.NET Standard_ project, **Amazon.Runtime.Internal.Settings.UserCrypto** class), which uses DLLImport [here](https://github.com/aws/aws-sdk-net/blob/1afe62e499790c44425d21fa42c8749cf4b355c7/sdk/src/Core/Amazon.Runtime/Internal/Settings/_bcl%2Bnetstandard/UserCrypto.cs#L177) and [here](https://github.com/aws/aws-sdk-net/blob/1afe62e499790c44425d21fa42c8749cf4b355c7/sdk/src/Core/Amazon.Runtime/Internal/Settings/_bcl%2Bnetstandard/UserCrypto.cs#L189) and requires `Crypt32.dll` which is available only on windows. 

Not required, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.

It would be nice if these data wouldn't be encrypted using Crypt32.dll, or at least **the documentations should mention that it doesn't work outside of windows**.

Provide a self-contained, concise snippet of code that can be inserted into a PowerShell session to replicate the bug. Including business logic or unrelated code makes diagnosis more difficult.

Simply invoke `Set-AWSSamlEndpoint` or `Set-AWSSamlRoleProfile` cmdlet on MacOS, or Linux

How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.
**`MacOS Catalina 10.15.3`**
Include as many relevant details about the environment where the bug was discovered.
* Affected module (_AWSPowerShell_, _AWSPowerShell.NetCore_ or _AWS.Tools.*_): **AWSPowerShell.NetCore** but I think **AWS.Tools.*** is also affected
* Module version as reported by `Get-AWSPowerShellVersion`:
```
AWS Tools for PowerShell
Version 4.0.4.0
Copyright 2012-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.104.22
Copyright 2009-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License
[http://logging.apache.org/log4net/license.html]
 ```
* Operating System and version as reported by `$PSVersionTable.OS`: 
`Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64`
* PowerShell version as reported by `$PSVersionTable.PSEdition`:
`Core`

**Comment by stonegate27** [comment]
@carathorys I saw the same issue with my Macbook. Any suggestion?

**Comment by ashishdhingra** [comment]
Looks like the error this thrown by [SettingsManager.EnsureAvailable](https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Core/Amazon.Util/Internal/SettingsManager.cs#L49).

**Comment by yevhenhnes** [comment]
Did the issues was resolved? I'm trying to use Set-AWSSamlEndpoint on Mac and have the same issue:
`Set-AWSSamlEndpoint: The encrypted store is not available.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded.
`

**Comment by ashishdhingra** [comment]
Related issue https://github.com/aws/aws-tools-for-powershell/issues/134
