### ISSUE TITLE
Set-CCRepositoryTrigger fails wiith "Repository trigger branch name list cannot be null"

### ISSUE THREAD

**Issue by Sean-Intellicore** [aws/aws-tools-for-powershell#146]
When providing an empty array with @() the command fails. 

**Expected Behavior**

Passing in @() should allow trigger to run on all branches

**Steps to Reproduce (for bugs)**
Example request:
```
Set-CCRepositoryTrigger `
            -RepositoryName "Example" `
            -Trigger @(
        @{
            Branches = @();
            CustomData = "TestData";
            DestinationArn = "arn:aws:lambda:eu-west-2:000000000000:function:Example";
            Events = "updateReference";
            Name = "ExampleTrigger";
        }
        )
```

**Your Environment**
AWS.Tools.Codecommit

```
AWS Tools for PowerShell
Version 4.0.5.0
Copyright 2012-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.104.35
Copyright 2009-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License
[http://logging.apache.org/log4net/license.html]
```
Microsoft Windows 10.0.18363
Powershell Core 7

**Comment by ashishdhingra** [comment]
The [RepositoryTrigger](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_RepositoryTrigger.html) link specifies that for **branches** parameter, if an empty array is specified, the trigger applies to all branches. However it also specifies the length constant of minimum length of 1.

**Comment by kellertk** [comment]
This issue has not received a response in 2 weeks. If you want to keep this issue open, please just leave a comment below and auto-close will be canceled.
