### ISSUE TITLE
Write-CWEPermission returns InvalidOperation: Policy size would be larger than the maximum allowed

### ISSUE THREAD

**Issue by idomingo** [aws/aws-tools-for-powershell#148]
The cmd **Write-CWEPermission** fails with the message:
InvalidOperation: Policy size would be larger than the maximum allowed.
Aparently, in the sdk version i'm running, there is some kind of validation before running the command. The existing policy for the default event bus is large, but adding a new account is allowed, it does not reach any limit.

**Expected Behavior**

The equivalent command in the aws sdk for linux is **aws events put-permission**. It works with the same parameters in the same account.
Same with aws sdk for python, boto3. The equivalent command works.
Adding the account manually in the aws console also works fine.

**Steps to Reproduce (for bugs)**

Write-CWEPermission -Principal "123456789012" -StatementId "MyID" -Action "events:PutEvents"

**Your Environment**

AWS Tools for Windows PowerShell 
Version 4.0.4.0 

Amazon Web Services SDK for .NET 
Core Runtime Version 3.3.104.22

**Comment by ashishdhingra** [comment]
Hi @idomingo,

Good afternoon.

I was going through issue backlog and came across this one. Somehow, the below PowerShell command works fine for me:

```PS
Write-CWEPermission -Principal 139480602983 -StatementId "MyID" -Action "events:PutEvents"
```

After executing above statement, I'm able to see the above account permissions under `CloudWatch -> Event Buses`.

Could you please elaborate on the existing policy for default event bus, may be that's the missing piece here?

Thanks,
Ashish
