### ISSUE TITLE
EMR DescribeJobFlows API is deprecated - error while running Get-EMRJobFlow

### ISSUE THREAD

**Issue by ketanbhut** [aws/aws-tools-for-powershell#155]
Provide a general summary of the issue in the Title above.

**Expected Behavior**

Get-EMRJobFlow should show a warning and move ahead with the output - given the API is deprecated. However it appears the API is removed, so I should not see that as an available action from PowerShell.

I don't see the command in CLI anymore, even though the [CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/batch/describe-jobs.html) is there.. 

[Boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.describe_job_flows) still has it, and it does fail just like it fails with PowerShell Get-EMRJobFlow

**Current Behavior**  
Currently, we are presented with a warning, but we hit an error as well:

`Get-EMRJobFlow`  

`WARNING: The command 'Get-EMRJobFlow' is obsolete. This API is deprecated and will eventually be removed. We recommend that you use ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions instead.`
`Get-EMRJobFlow: DescribeJobFlows API is deprecated. Please refer to http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html for further information.`

**Possible Solution**

Not sure about the solution, may be this can be raised with the dev team of EMR service - but we can remove the CommandLet/s. 

**Steps to Reproduce (for bugs)**

Just run the Get-EMRJobFlow CommandLet

**Context**

There are certain other APIs other than DescribeJobFlows which depend on JobFlow ID as a 'Required' request parameter - for example:

| API |CmdLet
|---|---|
[AddInstanceGroups](https://docs.aws.amazon.com/emr/latest/APIReference/API_AddInstanceGroups.html#EMR-AddInstanceGroups-request-JobFlowId) | Add-EMRInstanceGroup
[AddJobFlowSteps](https://docs.aws.amazon.com/emr/latest/APIReference/API_AddJobFlowSteps.html#EMR-AddJobFlowSteps-request-JobFlowId) |  Add-EMRJobFlowStep
[SetTerminationProtection](https://docs.aws.amazon.com/emr/latest/APIReference/API_SetTerminationProtection.html#EMR-SetTerminationProtection-request-JobFlowIds) | Set-EMRTerminationProtection
[SetVisibleToAllUsers](https://docs.aws.amazon.com/emr/latest/APIReference/API_SetVisibleToAllUsers.html#EMR-SetVisibleToAllUsers-request-JobFlowIds) | Set-EMRVisibleToAllUser

**Your Environment**

Include as many relevant details about the environment where the bug was discovered.
* Affected module (_AWSPowerShell_, _AWSPowerShell.NetCore_ or _AWS.Tools.*_): AWS.Tools.ElasticMapReduce
* Module version as reported by `Get-Module AWS.Tools.ElasticMapReduce`: 4.0.5.0
* Operating System and version as reported by `$PSVersionTable.OS`: Microsoft Windows 10.0.17763
* PowerShell version as reported by `$PSVersionTable.PSEdition`: Core

**Comment by ashishdhingra** [comment]
The [Get-EMRJobFlow](https://github.com/aws/aws-tools-for-powershell/blob/a146d7b488685e0af1dc1640573170fceab64e76/modules/AWSPowerShell/Cmdlets/ElasticMapReduce/Basic/Get-EMRJobFlow-Cmdlet.cs#L62) calls [IAmazonElasticMapReduce.DescribeJobFlowsAsync()](https://github.com/aws/aws-sdk-net/blob/1b68e1d25213ae245e3f84afcca567e5b2091ff8/sdk/src/Services/ElasticMapReduce/Generated/_netstandard/AmazonElasticMapReduceClient.cs#L775). Both the CmdLet and the .NET SDK method are marked as `Obsolete`. The AWS Service API page for [DescribeJobFlows ](https://docs.aws.amazon.com/emr/latest/APIReference/API_DescribeJobFlows.html) also mentions that `This API is deprecated and will eventually be removed. We recommend you use ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions instead.`.

**Comment by ashishdhingra** [comment]
Hi @ketanbhut,

Good afternoon.

I was reviewing this issue with the team and currently we do not remove the PowerShell CmdLet when the API is marked as obsolete/deprecated, and allow it to fail. This is the expected behavior for deprecated APIs. Closing this issue.

Thanks,
Ashish
