### ISSUE TITLE
Test-S3Bucket uses http

### ISSUE THREAD

**Issue by egerod** [aws/aws-tools-for-powershell#17]
**Expected Behavior**
Test-S3Bucket uses a https connection for its web request.

**Current Behavior**
Test-S3Bucket uses a http connection.

**Possible Solution**
Update Test-S3Bucket to use a https connection

**Steps to Reproduce (for bugs)**
Boot up your favorite proxy, proxy a Test-S3Bucket command through it, note that it uses http.

**Context**
Test-S3Bucket is the only aws cmdlet (to my knowledge) that uses http instead of https. This could lead to unintended data leaks. And might compromise credentials, if the query parameters on the request contains secrets. 

**Your Environment**
Test on:

- AWSPowerShell

- AWS Tools for Windows PowerShell - Version 3.3.365.0

- Amazon Web Services SDK for .NET - Core Runtime Version 3.3.25.3

- Windows 10

- PowerShell 5.1.17134.950

**Comment by matteo-prosperi** [comment]
This requires a change in the AWS SDK for .NET that AWSPowerShell leverages. A proposed change is tracked here https://github.com/aws/aws-sdk-net/pull/1209.

**Comment by matteo-prosperi** [comment]
Hello, this issue is fixed with the latest release of AWSPowerShell 3.3.553.0
