### ISSUE TITLE
Update-AWSToolsModule / Install-Module Causing Signature Error On Upgrade to 4.1.0.0

### ISSUE THREAD

**Issue by boblodgett** [aws/aws-tools-for-powershell#170]
## The Question

When updating to 4.1.0.0 using Update-AWSToolsModule in version 1.0.1.0 of the AWS.Tools.Installer module the following error will occur:

Error validating manifest signature for AWS.Tools.Common

To fix this problem update to version 1.0.2.0 of the AWS.Tools.Installer (Install-Module AWS.Tools.Installer -SkipPublisherCheck -Force) and run the command as:

Update-AWSToolsModule -SkipPublisherCheck

This issue can also occur if you have an existing version of AWS PowerShell installed and try to Install-Module MODULE_NAME -Force. The following error will be reported:

| Authenticode issuer 'CN="Amazon Web Services, Inc.", OU=AWS, O="Amazon Web Services, Inc.", L=Seattle, S=Washington, C=US' of the new module 'AWSPowerShell.NetCore' with version
     | '4.1.0.0' from root certificate authority 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US' is not matching with the authenticode issuer 'CN="Amazon.com,
     | Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US' of the previously-installed module 'AWSPowerShell.NetCore' with version '4.0.6.0' from root certificate authority
     | 'CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US'. If you still want
     | to install or update, use -SkipPublisherCheck parameter.

To fix this problem run Install-Module MODULE_NAME -Force -SkipPublisherCheck

### Environment

* Build Version: 
* OS Info: 
* Build Environment: 
* Targeted .NET Platform:  

---

This is a :question: general question

**Comment by dsl101** [comment]
With AWS.Tools.Installer 1.0.1.0 already installed, running `Install-Module AWS.Tools.Installer -SkipPublisherCheck` alone results in just a warning that 1.0.1.0 is already installed. Running `Install-Module AWS.Tools.Installer -SkipPublisherCheck -Force` issues these 2 warnings:
```
WARNING: The version '1.4.7' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
WARNING: The version '2.2.4.1' of module 'PowerShellGet' is currently in use. Retry the operation after closing the applications.
```
but did seem to install AWS.Tools.Installer 1.0.2.0 (alongside 1.0.1.0). After closing and reopening the Powershell window, I was then able to update the tools themselves using `Update-AWSToolsModule -SkipPublisherCheck`.

I presume it is OK to then just delete the `\AWS.Tools.Installer\1.0.1.0\` folder to remove the older version?
