### ISSUE TITLE
Get-RDSDBInstance and Get-RDSDBCluster should allow you to find resources by their resource IDs (cluster-xxxx.../db-xxxx...)

### ISSUE THREAD

**Issue by WToorenburghIntiveo** [aws/aws-tools-for-powershell#171]
## Describe the Feature
I feel like the Get-RDSDBInstance and Get-RDSDBCluster commandlets should allow you to retrieve instances/clusters using their unique resource IDs.

## Proposed Solution
Either supporting a `-ResourceID` parameter, or supporting Resource IDs in the `-Filter` parameter would be very helpful.

## Additional Context
The RDS Get commandlets for DB instances and clusters only support Instance IDs via the `-DBClusterIdentifier`/`-DBInstanceIdentifier` parameters, or Instance IDs and ARNs via the `-Filter` parameter. This is frustrating to me, as I'm working on a script to help my team connect to RDS instances using IAM. The IAM policies for granting access to DBs only use the `cluster-`/`db-` unique IDs, and there are no other identifiers available from that information I can use to identify which actual DBs/Clusters a given user has permissions for.

### Describe alternatives you've considered
The only other ways I can think of accomplishing this task is by either putting in some extra text in the IAM policies with the names of the DBs, or with some complex tagging scheme.

### Environment
This is working with the AWS.Tools modules on Powershell 7.0.1 on Windows 10, version 1909

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @WToorenburghIntiveo,

Good morning.

The CmdLets [Get-RDSDBInstance](https://github.com/aws/aws-tools-for-powershell/blob/master/modules/AWSPowerShell/Cmdlets/RDS/Basic/Get-RDSDBInstance-Cmdlet.cs) and [Get-RDSDBCluster](https://github.com/aws/aws-tools-for-powershell/blob/master/modules/AWSPowerShell/Cmdlets/RDS/Basic/Get-RDSDBCluster-Cmdlet.cs) are autogenerated from the service model, and map to [DescribeDBInstances](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html) and [DescribeDBClusters](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html) service API operations. The service API operation [DescribeDBInstances](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html) appear to support `dbi-resource-id` in `Filter` parameter. Whereas, service API operation [DescribeDBClusters](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html) only supports `db-cluster-id`. The filtering support at the API level is controlled by the service. Kindly check if resource ID filter works for `Get-RDSDBInstance` CmdLet as supported by service.

Based on above details, this doesn't appear to be a feature request. Please let me know if this helps.

Thanks,
Ashish
