### ISSUE TITLE
Unable to Create V1 Bucket Replication Rule That Affects the Whole Bucket

### ISSUE THREAD

**Issue by kylec32** [aws/aws-tools-for-powershell#176]
## Description
It appears that a user is unable to create a V1 replication rule (that includes replication of deletemarkers) that affects the whole bucket, only if a Prefix is provided.

## Reproduction Steps
Given code such as:
```
$primaryBucketName = "myawesomebucket"
$secondaryBucketName =  "myawesomebucketcopy"
$configurationRole = "arn:aws:iam::<account>:role/myrole"
$replicateBucketRule = [Amazon.S3.Model.ReplicationRule] @{
     Id = "BucketReplicationRule"
     Status = "Enabled"
     Prefix = ""
     Destination = @{
         BucketArn = ("arn:aws:s3:::" + $secondaryBucketName)
      }
 }
Write-S3BucketReplication -BucketName $primaryBucketName -Configuration_Role $configurationRole -Configuration_Rule $replicateBucketRule
```
I am met with: The XML you provided was not well-formed or did not validate against our published schema

If I instead give a value for the `Prefix` parameter it works with no error.

```
$primaryBucketName = "myawesomebucket"
$secondaryBucketName =  "myawesomebucketcopy"
$configurationRole = "arn:aws:iam::<account>:role/myrole"
$replicateBucketRule = [Amazon.S3.Model.ReplicationRule] @{
     Id = "BucketReplicationRule"
     Status = "Enabled"
     Prefix = "/"
     Destination = @{
         BucketArn = ("arn:aws:s3:::" + $secondaryBucketName)
      }
 }
Write-S3BucketReplication -BucketName $primaryBucketName -Configuration_Role $configurationRole -Configuration_Rule $replicateBucketRule
```

### Logs
I do see request logging mentioned in the documentation but no details of how to enable it, I do thin that would be helpful.
```
Amazon Information: 0 : Starting a process with the following ProcessInfo: UseShellExecute - False RedirectStandardError - True, RedirectStandardOutput - True, CreateNoWindow - True
Amazon Information: 1 : Process started
Amazon Information: 0 : Process ends with exitcode - 0
Amazon Error: 0 : An exception of type HttpErrorResponseException was handled in ErrorHandler., Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
Amazon Error: 1 : Received error response: [<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>116C4874F7557DA5</RequestId><HostId>XIF53dfH13MX5ihp5n8j7j7QZiJKhAVXn++O0F6sL8j0azPcgSqlSip8uMnU8ZvQTMSapp/dejM=</HostId></Error>], Amazon.S3.AmazonS3Exception: The XML you provided was not well-formed or did not validate against our published schema
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
Amazon Information: 2 : AmazonS3Exception making request PutBucketReplicationRequest to https://acmeinc-dev-us-west-2.s3.amazonaws.com/. Attempting retry 1 of 4.
```

### Environment
Version: 4.1.1.0
OS Info: Windows 10
Build Environment: Powershell 7.0.3

## Resolution

My guess is that it is removing the `Prefix` section from the request if it's empty but can't confirm this (unless I get request logging). 

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Need to reproduce if omitting Prefix all together works.

**Comment by kylec32** [comment]
Unfortunately that didn't work for me. In case it's helpful heres about as stripped down of a setup as I can create:
https://gist.github.com/kylec32/c00ce86b59056912febf52eda12fdc17
Basically the goal being not to error when running

**Comment by ashishdhingra** [comment]
Hi @kylec32,

Looks like there are some changes to the [ReplicationRule](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ReplicationRule.html) service API and the `Prefix` parameter on  has been deprecated.

The new way to write replication rule is to use `Filter` parameter of `ReplicationRule` as shown below:
```PowerShell
$primaryBucketName = "myawesomebucket-12345"
$secondaryBucketName =  "myawesomebucketcopy-12345"
$configurationRole = "arn:aws:iam::<account>:role/<rolename>"
$deleteMarkerReplicationStatus = New-Object -TypeName Amazon.S3.DeleteMarkerReplicationStatus -ArgumentList "Disabled"
$replicateBucketRule = [Amazon.S3.Model.ReplicationRule] @{
      Id = "BucketReplicationRule"
      Status = "Enabled"
      Destination = @{
          BucketArn = ("arn:aws:s3:::" + $secondaryBucketName)
       }
      Filter = @{ 
         Prefix = ""
     }
     Priority = 0
     DeleteMarkerReplication = [Amazon.S3.Model.DeleteMarkerReplication] @{
         Status = $deleteMarkerReplicationStatus
    }
}

 Write-S3BucketReplication -BucketName $primaryBucketName -Configuration_Role $configurationRole -Configuration_Rule $replicateBucketRule
``` 

The above code works, below is the screenshot:
<img width="1344" alt="Screen Shot 2020-10-09 at 2 47 31 PM" src="https://user-images.githubusercontent.com/67916761/95634303-6e513d00-0a3e-11eb-9b9b-d63200447646.png">

Please test it at your end and confirm if this issue could be closed.

Thanks,
Ashish

**Comment by kylec32** [comment]
Thank you for looking into this and providing that information. Unfortunately, although the above code works, it actually is setting up V2 replication configuration (where delete markers *are not* replicated) and not V1 replication configuration (where delete markers *are* replicated). For our use case we need the delete markers replicated as the two buckets should look as close to identical as possible.

https://aws.amazon.com/blogs/storage/managing-delete-marker-replication-in-amazon-s3/ This blog post goes over the differences between the two (as I'm not sure I explained it very well).

When you provide a non-empty prefix value it appears that it is setting up V1 replication but it just doesn't let you set it up to affect the whole bucket.

**Comment by ashishdhingra** [comment]
**Tested using AWS CLI (reference [Managing delete marker replication in Amazon S3](https://aws.amazon.com/blogs/storage/managing-delete-marker-replication-in-amazon-s3/)):**
1. Created buckets (`source-replicationrule-bucket` and `destination-replicationrule-bucket`) in the same region.
2. Enabled versioning on the source and destination buckets.
3. Created IAM role with S3FullAccess policy,
4. Created the following JSON:
```JSON
{
    "Role": "arn:aws:iam::<account_id>:role/replicationrule-testrole",
    "Rules": [
        {
            "ID": "Replication V1 Rule",
            "Prefix": "",
            "Status": "Enabled",
            "Destination": {
                "Bucket": "arn:aws:s3:::destination-replicationrule-bucket"
            }
        }
    ]
}
```

5. Executed the following command from AWS CLI (in the same folder as test.json):
```
aws s3api put-bucket-replication --bucket source-replicationrule-bucket --replication-configuration file://test.json
```

**RESULT:**
Replication Rule was successfully added on source bucket.
