### ISSUE TITLE
Add the "EtagToNotMatch" parameter to "Read-S3Object" cmdlet

### ISSUE THREAD

**Issue by thedevopsmachine** [aws/aws-tools-for-powershell#18]
The -ETagToNotMatch parameter exists on the Get-S3ObjectMetadata Cmdlet, but it's not much use there. By adding it to Read-S3Object, I can specify a MD5 hash of a local file, and if the local MD5 matches the remote file MD5, it doesn't need to download the file. This can eliminate the need for me to make 2 API calls (i.e. Get-S3ObjectMetadata and then Read-S3Object).

**Expected Behavior**
Read-S3Object should have a ETagToNotMatch parameter

**Current Behavior**
Read-S3Object does not have a ETagToNotMatch parameter

**Possible Solution**
Add the ETagToNotMatch parameter to Read-S3Object Cmdlet

**Comment by matteo-prosperi** [comment]
Is is worth noting that Read-S3Object uses the TransferUtility, so this requires more investigation and likely a change in the .NET SDK.

**Comment by hunanniu** [comment]
Will not support this
