### ISSUE TITLE
Lambda Layers for Powershell

### ISSUE THREAD

**Issue by brendan-sherrin** [aws/aws-tools-for-powershell#183]
Lambda Layers for Powershell

## Describe the Feature
Can the .net Lambda Layers be integrated into Powershell AWS tools?
https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/

### Is your Feature Request related to a problem?
The problem is that powershell Lambda zip file sizes are too large, I'd love to do Lambda console inline editing and add on the relevent AWS powershell modules as layers.  I can do this easily in python by adding a boto 3 layer to hold the content and then edit my code inline.

## Proposed Solution
Update existing Lambda module to allow specifying Lambda layers and consider creating something to easily convert an existing PS module/s as a layer.  

### Describe alternatives you've considered
Considered using python instead but dealing with AD which is more fully featured in Powershell

## Additional Context
Would really like to inline edit in the Lambda console, I really like this in other languages.

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by normj** [comment]
The latest version of the AWSPSLambdaCore allows adding layers with the `-Layer` switch. As far as adding PowerShell to the Lambda console that is beyond the scope of what we can do here.
