### ISSUE TITLE
TaskDefinition JSON argument for Register-ECSTaskDefinition-Cmdlet.cs

### ISSUE THREAD

**Issue by TheWix** [aws/aws-tools-for-powershell#184]
Looking at the docs for https://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html it takes a string argument representing a TaskDefinition Json. From there you can specify parameters to override. I can't find an equivalent for the Powershell cmdlet. I've looked around online and can't find much on it and don't see it in the source code. Am I missing something or is this functionality not available via the Powershell APIs?

**Comment by ashishdhingra** [comment]
Hi @TheWix,

Good morning.

The page [AWS Tools for PowerShell - Amazon EC2 Container Service](https://docs.aws.amazon.com/powershell/latest/reference/items/ECS_cmdlets.html) documents all the available ECS CmdLets. The closest PowerShell CmdLet for your use case is [Register-ECSTaskDefinition](https://docs.aws.amazon.com/powershell/latest/reference/items/Register-ECSTaskDefinition.html). Please review and let me know if we could close this issue.

Thanks,
Ashish

**Comment by TheWix** [comment]
That appears to be the case, @ashishdhingra. 

Would it be worth it to submit it as a feature request? It is very limiting to be forced to programmatically construct a Task Definition. It would be much nicer to be able to provide JSON and only programmatically change those fields that aren't static. 

Unless there is a simple workaround that I am not aware of?

**Comment by ashishdhingra** [comment]
@TheWix I have added feature-request label to mark it as new feature request.

**Comment by TheWix** [comment]
@ashishdhingra Thank you. This feature would do a lot to simplify updating a Task Definition.
