### ISSUE TITLE
Unable to install AWSPowershell.NetCore 4.1.2.0 when a 4.0.5.0 is already present

### ISSUE THREAD

**Issue by kduvzc** [aws/aws-tools-for-powershell#186]
It seems like the root certification authority used to sign the AWSPowershell.NetCore package has recently changed: version 4.0.5.0 root certification authority is **VeriSign Universal Root Certification Authority** while version 4.1.2.0 uses **Amazon Web Services, Inc.** . When PowerShellGet attempts to install the newer 4.1.2.0 onto a machine which already has version 4.0.5.0 installed, it fails with
```
Authenticode issuer 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US' of the new module 'AWSPowerShell.NetCore' with version '4.1.2.0' is not matching with the authenticode issuer 'CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only"
```
suggesting us to execute the Install-Module with the -SkipPublisherCheck flag. Unfortunately, we're relying on the RequiredModules property in a psd1 file to install the modules. We cannot simply uninstall the 4.0.5.0 version as it is needed to support older scripts. Is there a way to avoid this issue?

**Comment by ashishdhingra** [comment]
Hi @kduvzc,

Good morning.

Per Microsoft's [Install-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-7.1) documentation at , `-Force` parameter allows for multiple versions to be installed for the module. Please let me know if `-Force` parameter works fine along with `-SkipPublisherCheck` for your scenario.

Thanks,
Ashish

**Comment by kduvzc** [comment]
Hi @ashishdhingra !

As stated in the problem description "_Unfortunately, we're relying on the RequiredModules property in a psd1 file to install the modules_". We're not issuing the **Install-Module** cmdlet to install the module. I believe PowerShellGet does the installation of the _RequiredModules_ it finds in the psd1 file.

**Comment by ashishdhingra** [comment]
Hi @kduvzc,

I tried to find solution online for this use case. Unfortunately, `PowerShellGet` automatically downloads (may be using `Install-Module`) behind the scenes, and I do not see a way to configure `SkipVersionCheck` for the `RequiredModules` dependencies. The only (wacky) un-tested workaround I could think of is to:
-  Create a common module which has the logic for finding the required version (may be using `Find-Module`) for the required `AWSPowershell.NetCore` version and if it is not present, invoke `Install-Module` with the `SkipVersionCheck` command.
- Remove dependency on the specified `AWSPowershell.NetCore` version, but invoke the common module to install the specified version of `AWSPowershell.NetCore` as a first check.

This is a limitation of PowerShell and not sure if we could make RequiredModules work with `SkipVersionCheck` flag.

Hope this helps.

Thanks,
Ashish

**Comment by kduvzc** [comment]
What about republishing all of the previous versions of AWSPowerShell.NetCore signed with the newer root certification authority?

By the way... why was this changed in the first place?

**Comment by ashishdhingra** [comment]
Hi @kduvzc,

Good morning.

Previous versions of AWSPowerShell.NetCore are already published to NuGet and would not be updated with the newer root certificate authority due to obvious reasons. Please refer to [Announcement](https://github.com/aws/aws-tools-for-powershell/issues/170) which was made when this issue occurred. The new certificate was issued with Amazon Web Services entity which makes sense since SDKs are managed by AWS.

Thanks,
Ashish
