### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by jizquierdo-medsys** [aws/aws-tools-for-powershell#189]
So...how do you build this? ¯\_(ツ)_/¯

**Comment by ashishdhingra** [comment]
Hi @jizquierdo-medsys,

Please provide the issue details in order for us to provide guidance. Closing this issue.

Thanks,
Ashish

**Comment by jizquierdo-medsys** [comment]
That is what I need assistance with, how do I build the PowerShell tools.  There are no instructions that explains how to build the PowerShell tools. If there is, can you point me to where the instructions are at?
Thank you!

**Comment by jizquierdo-medsys** [comment]
Okay, I just saw your comment.  I will give that a try using msbuild.  Thank you!

**Comment by ashishdhingra** [comment]
Just note that you would also need to install PowerShell Core on your Windows machine. I used the latest version of PowerShell `PowerShell-7.0.4-win-x64`. I was successfully able to build AWS PowerShell tools. Closing this issue.
