### ISSUE TITLE
Cmdlet prefers Proxy settings over VPC endpoint.

### ISSUE THREAD

**Issue by henrivdr01** [aws/aws-tools-for-powershell#191]
## Description
When the EC2 VPC endpoint ec2.eu-west-1.amazonaws.com exists the Get-EC2Instance cmdlet still tries to connect to a defined proxy first.  If the proxy connection fails, the cmdlet times out. **It does not try the DNS lookup and endpoint connection directly**.

I have not tested the behavior of other cmdlets.

## Reproduction Steps

1. Make sure there is a VPC endpoint by running **Resolve-DnsName ec2.eu-west-1.amazonaws.com**. It should resolve to your endpoint instead of the public internet address.
2. Simulate a proxy failure by running **Set-AWSProxy -Hostname xxx -Port 123**
3. Run **(Get-EC2Instance -Region $myregion).Count**.  It will fail.
4. Run  **$AWSProxy = $null** 
5. Run **(Get-EC2Instance -Region $myregion).Count** .  It will use the endpoint and succeed.

### Environment

* Build Version: AWSPowerShell  4.1.5.8 and AWS.Tools.EC2 4.1.5.8
* OS Info: Windows Server 2019
* Build Environment: PowerShell

## Resolution
- We recommend that the DNS lookup be done first and the connection tried. Only if it fails should the proxy be used.

---

This is a :bug: bug-report

**Comment by PebCat** [comment]
I believe this need to be addressed wo support some bootstrap script such as the one for EKS node to join a private cluster with customized AWSProxy setting.
