### ISSUE TITLE
Missing attribute for  "Amazon_EC2_Model_IpPermission" Object 

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-tools-for-powershell#192]
Good Day , 

Can you kindly expound on the following ? 

Why are we unable to describe security group rules (permissions) based on description of the permission entry ?
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2IpPermission.html&tocid=Amazon_EC2_Model_IpPermission

The aws console clearly indicates an optional description field for a security group rule  (AKA Permission entry), but we are unable to describe or refer to permission entries based on description. 

Is this a limitation ? 

Mind you I am not requesting to add a permission entry , I am asking to describe  or update the entry by just using its description attribute .

Example : 
Describe-EC2SecurityGroupRuleIngress  -SecurityGroupId  xxxxxxx  -RuleDescription "SSH ACCESS" 
Describe-EC2SecurityGroupRuleIngress  -SecurityGroupId  xxxxxxx  -filter(description:"SSH ACCESS")

Update-EC2SecurityGroupRuleIngress  -SecurityGroupId  xxxxxxx  -RuleDescription "SSH ACCESS"  -NewIpPermission xxxxxxxxxxx
Update-EC2SecurityGroupRuleIngress  -SecurityGroupId  xxxxxxx -filter(description:"SSH ACCESS") -NewIpPermission  xxxxxxxxxxx

I hope this is understood . 
If not feel free to let me know where I need to elaborate .

Regards ,
Manuel Hubbard

 
## Describe the Feature
Make attribute available for this object ,
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2IpPermission.html&tocid=Amazon_EC2_Model_IpPermission

### Is your Feature Request related to a problem?
Updating an existing security group rule . 
I  don't want to keep adding and removing the same security group rule via the CLI 

## Proposed Solution

Make attribute available for this object ,
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2IpPermission.html&tocid=Amazon_EC2_Model_IpPermission

### Describe alternatives you've considered
If you show it in the AWS Console , make it describable via the client tooling 

## Additional Context
I was attempting to update an existing security group rule by targeting its "optional" "Description" attribute, as shown in the AWS console . 
### Environment
AWS Tools for Powershell 

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

Good afternoon.

The service API page for [IpPermission](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html) object type does not list any attribute that relates to Description. The models in AWS .NET SDK (e.g. [IpPermission](https://github.com/aws/aws-sdk-net/blob/85af718a01f63e0a71cd6bacbdb0c07f54fbb737/sdk/src/Services/EC2/Generated/Model/IpPermission.cs#L34))are based on the information shared by the service. Kindly confirm if we are referring to the same thing. I'm not sure if you are  referring to the description of [SecurityGroup](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroup.html).

Thanks,
Ashish

**Comment by manuelh2410** [comment]
Hi Ashish. 
You are correct in assuming that I am referring to the "Ip Permission object"  which forms part of the configuration of an AWS security group. 

"https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html" 

Your findings also confirm the point I am trying to make. 

The AWS console clearly shows a "description" field for security group permission entries.
Yet one is unable to query these permission entries based on the description attribute. 

I have attached a screenshot of the attribute in the AWS console in order to better illustrate my point.

My reasoning is, why show it in the AWS console if the attribute doesn't exist in the SDK?
Its very misleading and inconvenient . 

![description](https://user-images.githubusercontent.com/50540203/118362897-03e31b00-b592-11eb-89b9-f9fe3687ad76.JPG)

**Comment by ashishdhingra** [comment]
> https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html

I got your point, not sure on why there is a difference between the AWS console and API. AWS SDKs have auto-generated models based on metadata shared by service API. Without support in API, the SDKs cannot have support for this property. You may try submitting feedback at the bottom of the page for API documentation to get clarification or if we are missing something here.

Thanks,
Ashish

**Comment by manuelh2410** [comment]
I'm sorry but your response is unacceptable. 

"not sure on why there is a difference between the AWS console and API."

"You may try submitting feedback at the bottom of the page for API documentation to get clarification or if we are missing something here."

"You may want to check the API operation UpdateSecurityGroupRuleDescriptionsIngress, not sure if description updated here is same as shown in AWS console."

-

First of all, I gave you all the information I can possibly give you as an end-user. 
I don't think I have to point out to you that I am under no obligation to make you or AWS aware of the shortcomings of the AWS Powershell SDK. I also think that I need to remind you that I am taking my valuable time to respond to each of your updates. In light of this, I think you and I both know that asking me to log yet another request is not the most customer-centric decision here. 


second, 
You and I both know that the " UpdateSecurityGroupRuleDescriptionsIngress" API call has no relation to the issue at hand so let's not mention API calls unrelated to the issue. 

lastly, telling me that you "don't know"  gives me the impression that you didn't discuss this with your peers. 

As an end-user want to hear something along the lines of  "Thank you for bringing this to our attention, we have raised this internally and a change will be released in subsequent versions of the SDK", or  "We will remove the description filter from the permissions list in the AWS Console". 

Since I have spent so much time and effort communicating with you regarding this, I urge you to discuss this with your manager /colleagues and formulate a more satisfactory response.

I can tell you now, that I am certainly not planning to retype everything in a new request.

**Comment by ashishdhingra** [comment]
> I'm sorry but your response is unacceptable.
> 
> "not sure on why there is a difference between the AWS console and API."
> 
> "You may try submitting feedback at the bottom of the page for API documentation to get clarification or if we are missing something here."
> 
> "You may want to check the API operation UpdateSecurityGroupRuleDescriptionsIngress, not sure if description updated here is same as shown in AWS console."
> 
> 
> First of all, I gave you all the information I can possibly give you as an end-user.
> I don't think I have to point out to you that I am under no obligation to make you or AWS aware of the shortcomings of the AWS Powershell SDK. I also think that I need to remind you that I am taking my valuable time to respond to each of your updates. In light of this, I think you and I both know that asking me to log yet another request is not the most customer-centric decision here.
> 
> second,
> You and I both know that the " UpdateSecurityGroupRuleDescriptionsIngress" API call has no relation to the issue at hand so let's not mention API calls unrelated to the issue.
> 
> lastly, telling me that you "don't know" gives me the impression that you didn't discuss this with your peers.
> 
> As an end-user want to hear something along the lines of "Thank you for bringing this to our attention, we have raised this internally and a change will be released in subsequent versions of the SDK", or "We will remove the description filter /tab from the permissions list in the AWS Console".
> 
> Since I have spent so much time and effort communicating with you regarding this, I urge you to discuss this with your manager /colleagues and formulate a more satisfactory response.
> 
> I can tell you now, that I am certainly not planning to retype everything in a new request.

@manuelh2410 I need to revisit this issue and may be test this at my end using the new API operation I suggested above. If required, I will discuss this internally with the service team to see if they are missing description attribute in the API operation that you mentioned. All AWS SDK(s) rely on service models shared by the service team, hence could only provide attributes which are available part of that model. Let me evaluate and get back to you.

**Comment by ashishdhingra** [comment]
P49297121

**Comment by ashishdhingra** [comment]
Opened ticket with service team for their inputs.

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

I got the response from service team. The security group rule description comes from sub-shapes of IpPermission. An `IpPermission` can have any of these sub-shapes : `IpRange`, `IPv6Range`, `PrefixListId`, `UserIdGroupPair` and each of these sub-shapes include the description.

**IpRange:** https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpRange.html
**Ipv6Range:** https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Ipv6Range.html
**PrefixListId:** https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_PrefixListId.html
**UserIdGroupPair:** https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_UserIdGroupPair.html

Console uses a tabular format to show rules so that way it might not seem 1:1 with the APIs but behind the scenes it is getting description from these shapes in the API response. 

Thanks,
Ashish

**Comment by manuelh2410** [comment]
I think you misunderstood me, 
My intial question was regarding the ability to both add a description 
to a permission entry and querry that same permission entry trough its description. 
The answer you provided does not bring me any closer to achieving this .
