### ISSUE TITLE
Stream to Write-S3Object from stdout?

### ISSUE THREAD

**Issue by tomcart90** [aws/aws-tools-for-powershell#193]
I'm trying to stream from stdout to Write-S3Object, similar to how you can with the cli: https://stackoverflow.com/a/42285350. I can't seem to work out how to do it with Write-S3Object, there doesn't seem to be any examples using the -Stream Param in the docs.

Any help would be massively appreciated!!

**Comment by ashishdhingra** [comment]
Hi @tomcart90,

Good morning.

I guess you are looking for ability to pass output of `stdout` to a PowerShell cmdlet. Are you able to do use `stdout` with normal PowerShell cmdlets (not AWS PowerShell tools cmdlets)? The link https://jackgruber.github.io/2018-05-11-ps-get-process-output/ provides a useful example on how to capture output from `stdout` (use it at your own risk). You may try developing similar logic and use it with one of the [Write-S3Object](https://docs.aws.amazon.com/powershell/latest/reference/items/Write-S3Object.html) variation.

Thanks,
Ashish

**Comment by tomcart90** [comment]
Thanks Ashish, I'm more looking fo a way to stream stdout to the Write-S3Object cmdlet. I can capture stdout from my program (pg_dump in this case) and pass it to Write-S3Object, however, the output could be 40gb+ and I don't have the ram or space on disk to store that output before pushing it to S3. This is possible with the cli, so I was hoping there was an implementation for the powershell cmdlet too. I was particularly interested in how the -Stream param is supposed to work, and whether that would solve my use case.

**Comment by ashishdhingra** [comment]
> Thanks Ashish, I'm more looking fo a way to stream stdout to the Write-S3Object cmdlet. I can capture stdout from my program (pg_dump in this case) and pass it to Write-S3Object, however, the output could be 40gb+ and I don't have the ram or space on disk to store that output before pushing it to S3. This is possible with the cli, so I was hoping there was an implementation for the powershell cmdlet too. I was particularly interested in how the -Stream param is supposed to work, and whether that would solve my use case.

Hi @tomcart90,

I'm not sure what to suggest here since the issue is quite generic and related to functionality provided by PowerShell environment. The best place to start would be Microsoft's documentation or Powershell blog to check if there is a possibility to get stream object from `stdout`.

Thanks,
Ashish
