### ISSUE TITLE
Why doesn't AWS.Tools.Common support setting environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY?

### ISSUE THREAD

**Issue by passbt** [aws/aws-tools-for-powershell#199]
Why doesn't Set-AWSCredentials in, AWS.Tools.Common, support setting environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for it's authentication credentials? My specific use case is around a CI/CD tool that is not hosted within an AWS boundary. Obviously, if the CI/CD tool is hosted within an AWS boundary a role is the preferred approach and authentication works without having to do anything further. However, it appears  Set-AWSCredentials only supports the use a credentials saved in a profile and this seems like a bad idea in in a CI/CD environment. I know Set-AWSCredentials does support passing the key and secret into it directly, but why not just include the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in it's default search algorithm?

I apologize if I've somehow missed this in the online documentation.

### Environment
AWS.Tools.Common: 4.1.6.0
Windows 10

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @passbt,

Good morning.

Thanks for posting the guidance question. The behavior of `Set-AWSCredentials` is by design where it supports storing credentials to persistent store (`-StoreAs`) or temporarily for the shell (based on `-Scope` parameter, refer https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes). I'm not sure why it doesn't support setting credentials to environment variables (may be a good candidate for a feature request!).

You could set an environment variable scoped to a user using the below command as an example:
```PowerShell
[System.Environment]::SetEnvironmentVariable('AWS_ACCESS_KEY_ID','<<access_key_id>>',[System.EnvironmentVariableTarget]::User)
```

Thanks,
Ashish

**Comment by passbt** [comment]
Thank you for your response. What I'm asking for is to also include the above environment variables in the search described [here](https://docs.aws.amazon.com/powershell/latest/userguide/specifying-your-aws-credentials.html#pstools-cred-provider-chain). If it doesn't already exist, and opening a feature is the best way to move forward, I can do that.

**Comment by ashishdhingra** [comment]
> Thank you for your response. What I'm asking for is to also include the above environment variables in the search described [here](https://docs.aws.amazon.com/powershell/latest/userguide/specifying-your-aws-credentials.html#pstools-cred-provider-chain). If it doesn't already exist, and opening a feature is the best way to move forward, I can do that.

Hi @passbt,

The link that you shared specifies credential search order, not the storing credentials. You might have figured out that environment variables can be set at PS session level, user level and system level. Hence it is quite ambiguous to implement this feature.

Thanks,
Ashish
