### ISSUE TITLE
Get-S3Object -Key tag not returning exact match.

### ISSUE THREAD

**Issue by DavidGWhitaker** [aws/aws-tools-for-powershell#20]
**Expected Behavior**
When I run the commands
`
$name = "file"
` ,
`
Get-S3Object -BucketName <bucketname> -Key "$name" -ProfileName PipelineCreds| Sort-Object -Property LastModified -Descending
`
When in S3 there exists two keys: 
- file/file.txt
- file2/file.txt

I should be given `file/file.txt`

**Current Behavior**

When I run the commands
`
$name = "file"
` ,
`
Get-S3Object -BucketName <bucketname> -Key "$name" -ProfileName PipelineCreds| Sort-Object -Property LastModified -Descending
`
When in S3 there exists two keys: 
- file/file.txt
- file2/file.txt

I am currently getting the incorrect value, `file2/file.txt`

**Possible Solution**

It seems like the -Key flag is using the functionality for the -KeyPrefix tag. 

**Steps to Reproduce (for bugs)**
Please add a file/file.txt and a file2/file.txt (i dont think the file matters, but in my environment there is only one file in each folder.) in S3, and then run the command i used in the "Current Behavior" section

**Context**
I am trying to get files that match specific names. I do not want to just rename the "file2" folder in S3 because that would cause issues since the key matters for my program.

**Your Environment**
Include as many relevant details about the environment where the bug was discovered.
* Affected module (AWSPowerShell or AWSPowerShell.NetCore):  AWSPowerShell 
* Module version as reported by `Get-AWSPowerShellVersion`: 
AWS Tools for Windows PowerShell
Version 3.3.485.0
Copyright 2012-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.100.2
Copyright 2009-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

* Operating System and version as reported by `$PSVersionTable.OS`: N/a (using Windows Server 2016 Standard, 64-bit)
* PowerShell verions as reported by `$PSVersionTable.PSEdition`: Desktop

**Comment by matteo-prosperi** [comment]
Hello, we are investigating this. A fix may be backward incompatible though.

**Comment by matteo-prosperi** [comment]
Hello, thanks for opening this issue. We have addressed this issue as part of the upcoming "version 4" changes. You can already test these changes using today's release (3.3.618) of AWS.Tools. You can find more details in #61.

We will port this change to AWSPowerShell and AWSPowerShell.NetCore as part of the upcoming 4.0 release.
