### ISSUE TITLE
Instanciation issues prevents the use os specific profiles with Set-AWSCredential

### ISSUE THREAD

**Issue by GityupSS** [aws/aws-tools-for-powershell#200]
## Description
Instanciation issues prevents the use os specific profiles with Set-AWSCredential

## Reproduction Steps
```powershell
Set-AWSCredential -AccessKey $anAccessKey -SecretKey $aSecretKey -StoreAs MyProfile
Get-AWSCredential -ListProfileDetail

<# returns: 
ProfileName            StoreTypeName         ProfileLocation
-----------            -------------         ---------------
MyProfile              NetSDKCredentialsFile

#>

Set-content 'MyAwsModule.psm1' -Value @'
Import-Module AWS.Tools.Common
Import-Module AWS.Tools.S3
Import-Module AWS.Tools.IdentityManagement
Class MyAwsModule
{
	[Object]GetS3ObjectFromMyTestBucket()
	{
		Return Get-S3Object -BucketName MyTestBucket
	}
}
'@

Set-Content 'script1.ps1' -Value @'
Using module .\MyAwsModule.psm1
try
{
    Set-AWSCredential -ProfileName MyProfile
	$myAwsObj = [MyAwsModule]::new()
	$bucketFiles = $myAwsObj.GetS3ObjectFromMyTestBucket()
	$bucketFiles
}
catch
{
    $line = $_.Exception.InvocationInfo.ScriptLineNumber
    $errorMessage = $_.Exception.Message
    write-host "$line : $ErrorMessage" -ForegroundColor Magenta
}
'@

##fails to get creds from powershell prompt (either 7.1 or 5.1)
.\script1.ps1

<# : No credentials specified or obtained from persisted/shell defaults.#>
```

### Environment
PS 5.1:
**Name | Value**                                                                                                     

PSVersion : 5.1.18362.1171                                                                                            
PSEdition : Desktop                                                                                                   
BuildVersion : 10.0.18362.1171                                                                                           

PS 7.1.2
**Name | Value**
PSVersion            :        7.1.2
PSEdition            :          Core
GitCommitId      :              7.1.2
OS  :                           Microsoft Windows 10.0.18363
Platform :                      Win32NT

AWS installed modules
Version  | Name
4.1.8.0 : AWS.Tools.Common
4.1.8.0 : AWS.Tools.EC2
4.1.8.0 : AWS.Tools.IdentityManagement
1.0.2.0 : AWS.Tools.Installer
4.1.8.0 : AWS.Tools.S3

## WorkAround
- Execute script1.ps1 from PowerShell ISE or VSCODE
- Execute from CMD.exe : "C:\Program Files\PowerShell\7\pwsh.exe" c:\temp\script1.ps1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @GityupSS,

Good afternoon.

This appears to be similar to issue https://github.com/aws/aws-tools-for-powershell/issues/106.

Did you try `Set-AWSCredential -Scope Global`? Because the credentials are stored in a PowerShell variable, they have to be set in the global scope to be visible outside of the function. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes. 

Please confirm if this helps.

Thanks,
Ashish

**Comment by GityupSS** [comment]
Hi @ashishdhingra,
I'll check into this, but in my point of view, this still doesn't explain why it should behave differently, depending on the way it is called!!! This would mean that **variables could change scope**. This is a major issue!!

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra,
> 
> I'll check into this, but in my point of view, this still doesn't explain why it should behave differently, depending on the way it is called!!! This would mean that **variables could change scope**. This is a major issue!!

@GityupSS The issue you are facing is due to the behaviour of PowerShell, not the AWS PS Tools. You may try modifying your example to set something at the same scope level as Set-AWSCredential does (please find the code in repo), and examine the behaviour.

**Comment by GityupSS** [comment]
YEP! that -Scope global option solved it! Thanks
