### ISSUE TITLE
Get-SSMResourceTag should be in format mi-[0-9a-f]{17} for resource type ManagedInstance

### ISSUE THREAD

**Issue by arq-anthonyw** [aws/aws-tools-for-powershell#204]
## Description
Get-SSMResourceTag for `ManagedInstance` types is failing with error message `resourceId i-0edbbb6e54088396a should be in format mi-[0-9a-f]{17} for resource type ManagedInstance`. 
Which in a sense is somewhat correct however not all instances registered to SSM as a managed instance are in that format. I have old instances with instance Id's of `i-xxxxxxxx` and new instances with id's of `i-xxxxxxxxxxxxxxxxx`. The only instances I have using `mi-` are actually on-prem hybrid instances I have registered via a hybrid activation.

## Reproduction Steps
Spin up a new Windows instance using an AWS provided AMI that has SSM baked in and a suitable role attached and it will register with SSM automatically using it's instance ID and not something starting with `mi-`

### Environment

* Build Version: AWSPowerShell 4.1.9.0
* OS Info: Windows 10
* Build Environment: VsCode 
* Targeted .NET Platform:  5.1

## Resolution
I haven't checked the source code yet for the cmdlet to see if the restriction is based on the module itself or the AWS API but if it's a restriction controlled from the module it should be amended to allow for other scenarios supported by SSM. If it's the API... I'm guessing someone needs to be advised their stuff doesn't work like how they think it does?

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Looking at source for [Get-SSMResourceTag](https://github.com/aws/aws-tools-for-powershell/blob/a5d2b3dfc8d7ef6706a56e0b4170cfc24f33dd2b/modules/AWSPowerShell/Cmdlets/SimpleSystemsManagement/Basic/Get-SSMResourceTag-Cmdlet.cs#L40) CmdLet and .NET SDK [ListTagsForResourceRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleSystemsManagement/Generated/Model/ListTagsForResourceRequest.cs), I do not see any RegEx validation for `ResourceId`.

**Comment by ashishdhingra** [comment]
P49034715

**Comment by ashishdhingra** [comment]
Hi @arq-anthonyw,

Good afternoon.

Based on , the `Get-SSMResourceTag` uses AWS SDK for .NET to  invoke [ListTagsForResource](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ListTagsForResource.html) service API action. As per SSM service team, `ListTagsForResource` API action does not support EC2 instances as EC2 has their own API for tagging. SSM only supports the tagging for the managed instances (and few other resources).

You may try using `Get-EC2Tag-Cmdlet` for EC2 instances. Hope this helps.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
This issue has not recieved a response in 1 week. If you want to keep this issue open, please just leave a comment below and auto-close will be canceled.
