### ISSUE TITLE
Add Support for Expanded WorkSpaces API

### ISSUE THREAD

**Issue by mattk-ce** [aws/aws-tools-for-powershell#205]
The WorkSpaces API has been expanded with new commands, can we get some support for them? 
 See here: https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-workspaces-introduces-bundle-management-apis/

## Describe the Feature
In particular, I'm interested in `CreateWorkspaceBundle` and `UpdateWorkspaceBundle`.  But adding everything would be nice.

---

This is a :rocket: Feature Request

**Comment by ashovlin** [comment]
We currently release PowerShell roughly monthly, unlike the majority of the AWS SDKs which release daily. 

I anticipate that the new WorkSpaces cmdlets will be in the next release, but don't have a specific date to commit to yet.

**Comment by ashovlin** [comment]
The cmdlets for the WorkspaceBundle operations should now be in the 4.1.10.0 release of AWS Tools for PowerShell, which released last night.
* https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md#41100-2021-03-22 (WorkSpaces is at the bottom of the changelog entry for this release)
* https://www.powershellgallery.com/packages/AWS.Tools.WorkSpaces/4.1.10.0
