### ISSUE TITLE
AWS credentials retrieved from AWS SSO not available in PowerShell

### ISSUE THREAD

**Issue by cpaton** [aws/aws-tools-for-powershell#208]
## Description
Credentials obtained from the AWS CLI v2 via AWS SSO should be available to PowerShell modules

## Reproduction Steps
1. Login via AWS SSO using AWS CLI v2 ```aws sso login --profile dev```
2. Confirm credentials retrieved ```aws sts get-caller-identity```
3. Try to use credentials from PowerShell ```Get-StsCallerIdentity -ProfileName dev```.  This fails reporting Get-STSCallerIdentity: Value cannot be null. (Parameter 'Options property cannot be empty: ClientName') 

### Environment

* Build Version: 4.1.10.0
* OS Info: Windows 10
* Build Environment: Terminal

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible.

**Comment by ashishdhingra** [comment]
Could be related to https://github.com/aws/aws-sdk-net/issues/1821

**Comment by lmayorga1980** [comment]
Same for me

```
PS C:\Windows\system32> Get-SSOAccountList -ProfileName myprofile -Region "us-east-1"
Get-SSOAccountList : Value cannot be null.
Parameter name: Options property cannot be empty: ClientName
At line:1 char:1
+ Get-SSOAccountList -ProfileName myprofile -Region "us-east-1"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...countListCmdlet:GetSSOAccountListCmdlet) [Get-SSOAccountList], InvalidOperationEx
   ception
    + FullyQualifiedErrorId : System.ArgumentNullException,Amazon.PowerShell.Cmdlets.SSO.GetSSOAccountListCmdlet
```

In **python** works when I authenticate using `aws sso login --profile myprofile` and the following script is able to locate the credentials and let me run my `boto3` automation.

```
boto3.setup_default_session(profile_name='cmprodadmin')
```

**Comment by falloutphil** [comment]
Yep - same for me.  I can get my sso login to work with the aws cli, and boto3 to piggyback off this for python using, but I don't seem to be able to login directly using powershell, or piggyback off a cli login like I can in python.  The company I work at exclusivesly uses sso (no access or secret keys) for all AWS logins, so this basically rules out any powershell use with aws.

**Comment by ashishdhingra** [comment]
With AWS Powershell Tools version `4.1.13.0`, the reported error is gone, but now we get another error:
```PowerShell
Get-STSCallerIdentity: Assembly AWSSDK.SSOOIDC could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.SSOAWSCredentials, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604.
```
