### ISSUE TITLE
Remove-S3Object has undocumented limit of 1000 objects

### ISSUE THREAD

**Issue by pluto00987** [aws/aws-tools-for-powershell#21]
**Problem**
Per the underlying API, an S3 'multi-object delete' operation can process up to 1000 objects at once.

Using Remove-S3Object with an InputObject seems to have the same limit but it isn't mentioned in the relevant documentation. (Also probably using KeyCollection or KeyAndVersionCollection too).

[https://docs.aws.amazon.com/powershell/latest/reference/items/Remove-S3Object.html](url)

Additionally, violating that limit results in a completely unhelpful error message:

`Remove-S3Object : The XML you provided was not well-formed or did not validate against our published schema
`

**Suggested Solution**
A minimal solution is to mention the limit in the docs and improve the error message.
A more robust solution would be to have Remove-S3Object automagically split/stack such requests behind the scenes in a manner similer to how Get-S3Object does.

**Your Environment**
Windows Server 2016

PS C:\aws_scripts> Get-AWSPowerShellVersion

AWS Tools for Windows PowerShell
Version 3.3.498.0
Copyright 2012-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.101.0
Copyright 2009-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

PS C:\aws_scripts> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2879
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2879
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ashishdhingra** [comment]
S3 [DeleteObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) API specifies the 1000 keys limit. Probably a PowerShell API documentation update only.

**Comment by afroz429** [comment]
Thanks for bringing this to our attention. The documentation has been updated in 4.1.361 version.
