### ISSUE TITLE
AWS.Tools.S3 v4.1.10.0 get-s3presignedurl SignatureDoesNotMatch

### ISSUE THREAD

**Issue by wsl2001** [aws/aws-tools-for-powershell#213]
## Description
when using get-s3presignedurl in version 4.1.10.0 the following error appears when trying the presigned URL

the request signature we calculated does not match the signature you provided. check your key and signing method

## Reproduction Steps
tried v 4.1.9.0 no issues found.
update to v 4.1.10.0 issue is back.
remove all aws modules and install again v 4.1.10.0 and issue is back.

### Environment
windows server 2012 with windows powershell 5.1 & powershell 7.1

## Resolution
revert back to earlier version 4.1.9.0 or earlier.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Assuming this issue is for `us-east-1` region, this could be related to https://github.com/aws/aws-sdk-net/issues/1826. The fix was pushed in SDK, but pending for PowerShell.

**Comment by ganeshnj** [comment]
We have released 4.1.11.0 of AWS Tools for PowerShell which should fix the signing issue.

https://www.powershellgallery.com/packages/AWSPowerShell.NetCore
https://www.powershellgallery.com/packages/AWSPowerShell
https://www.powershellgallery.com/packages/AWS.Tools.S3
