### ISSUE TITLE
Get-CWLFilteredLogEvent Interleaved parameter not defaulting as stated

### ISSUE THREAD

**Issue by mfcooney** [aws/aws-tools-for-powershell#215]
## Description
Get-CWLFilteredLogEvent's -Interleaved parameter is defaulting to $false.  The deprecation remarks indicate it defaults to $true.

## Reproduction Steps
Ran these commands:

1. $(Get-CWLFilteredLogEvent -LogGroupName xxx -limit 3).Events
   - Shows logs from 3/26/2021 from stream i-000201f68990e559b-app (first alphabetically) 
2. $(Get-CWLFilteredLogEvent -LogGroupName xxx -limit 3 -Interleaved $true).Events
   - Shows logs from 3/22/2021 from stream i-02cfc7aa5352b5e26-wss (first chronologically) 

Where 'xxx' has log streams where the earliest chronological stream is not the same as the first alphabetically.

Running the command with '-Interleaved $false' is the same as not specifying it (first command), indicating it defaults to false, contrary to the deprecation remark.

### Logs
**PS /Users/me/Desktop> $(Get-CWLFilteredLogEvent -LogGroupName wr-uat -limit 3).Events**                    

EventId       : 36054979054707454038836657336541946208894101974831792128
IngestionTime : 1616761182227
LogStreamName : **i-000201f68990e559b-app**
Message       : **03/26/2021** 12:19:36,384 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-2) WFLYDS0013: Started FileSystemDeploymentService 
                for directory /opt/wildfly/standalone/deployments
Timestamp     : 1616761176980

EventId       : 36054979054707454038836657336541946208894101974831792129
IngestionTime : 1616761182227
LogStreamName : **i-000201f68990e559b-app**
Message       : **03/26/2021** 12:19:36,426 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of 
                "i3bo-mbss-client-2.5.3-develop-3451.war" (runtime-name: "i3bo-mbss-client-2.5.3-develop-3451.war")
Timestamp     : 1616761176980

EventId       : 36054979065857826638101968907309805345218282727822000130
IngestionTime : 1616761182227
LogStreamName : **i-000201f68990e559b-app**
Message       : **03/26/2021** 12:19:36,429 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of 
                "issuance-wfm-processor-2.5.3-develop-3451.war" (runtime-name: "issuance-wfm-processor-2.5.3-develop-3451.war")
Timestamp     : 1616761177480

**PS /Users/me/Desktop> $(Get-CWLFilteredLogEvent -LogGroupName wr-uat -limit 3 -Interleaved $true).Events** 
_WARNING: Parameter 'Interleaved' is obsolete. Starting on June 17, 2019, this parameter will be ignored and the value will be assumed to be true. The response from this operation will always interleave events from multiple log streams within a log group._

EventId       : 36047753652980757315521447889193100041237955605585592320
IngestionTime : 1616437184098
LogStreamName : **i-02cfc7aa5352b5e26-wss**
Message       : **2021-03-22** 17:44:48,181 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service 
Timestamp     : 1616437178761

EventId       : 36047753652980757315521447889193100041237955605585592321
IngestionTime : 1616437184098
LogStreamName : **i-02cfc7aa5352b5e26-wss**
Message       : Caused by: java.lang.IllegalStateException: WFLYUT0079: No SSL Context available from security realm 'ApplicationRealm'. Either the realm is not 
Timestamp     : 1616437178761

EventId       : 36047753652980757315521447889193100041237955605585592322
IngestionTime : 1616437184098
LogStreamName : **i-02cfc7aa5352b5e26-wss**
Message       : **2021-03-22** 17:44:50,209 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) Timestamp     : 1616437178761

### Environment

* Build Version: 4.1.11.0
* OS Info:  Windows 10, OSX Big Sur
* Targeted .NET Platform: 5.1.17763.1490, 7.1.3 

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @mfcooney,

Good morning.

Looking at the [Get-CWLFilteredLogEvent](https://github.com/aws/aws-tools-for-powershell/blob/master/modules/AWSPowerShell/Cmdlets/CloudWatchLogs/Basic/Get-CWLFilteredLogEvent-Cmdlet.cs), looks like for [Interleaved](https://github.com/aws/aws-tools-for-powershell/blob/afa95716c699fc547be689e26639cd0892538f5f/modules/AWSPowerShell/Cmdlets/CloudWatchLogs/Basic/Get-CWLFilteredLogEvent-Cmdlet.cs#L146) parameter (it's `Nullable<bool>`, hence default value is `null` if not specified), the deprecation message is coming from the service, refer [FilterLogEvents Service API](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html). Hence, even though PowerShell CmdLet might specify explicit value of `false`, service API would always assume the value to be `true` for this operation. I'm not sure how you assumed that it is considering value as `false`. Kindly advise if you compared the output with explicit values `false` and `true`, and if they returned different results. Also, try examining the behavior with AWS CLI.

Thanks,
Ashish

**Comment by mfcooney** [comment]
Thank you, @ashishdhingra .  Specifying '-Interleaved $false' produces the same results as not specifying -Interleaved at all, which is how I came to the conclusion.  Looking at the aws-cli, I can recreate the issue there.  These two commands produce the same results as above:

aws logs filter-log-events --log-group-name xxx --max-items 3 
aws logs filter-log-events --log-group-name xxx --max-items 3 --no-interleaved 

Whereas this command returns the correct results, like above:
aws logs filter-log-events --log-group-name xxx --max-items 3 --interleaved 

I'll open an issue in the aws-cli project.  The deprecation message here is out of sync with the underlying toolset, so it's technically still a bug, but if you feel the aws-cli project is the right place to address this, feel free to close this issue.

**Comment by ashishdhingra** [comment]
> Thank you, @ashishdhingra . Specifying '-Interleaved $false' produces the same results as not specifying -Interleaved at all, which is how I came to the conclusion. Looking at the aws-cli, I can recreate the issue there. These two commands produce the same results as above:
> 
> aws logs filter-log-events --log-group-name xxx --max-items 3
> aws logs filter-log-events --log-group-name xxx --max-items 3 --no-interleaved
> 
> Whereas this command returns the correct results, like above:
> aws logs filter-log-events --log-group-name xxx --max-items 3 --interleaved
> 
> I'll open an issue in the aws-cli project. The deprecation message here is out of sync with the underlying toolset, so it's technically still a bug, but if you feel the aws-cli project is the right place to address this, feel free to close this issue.
> 
> Update: Actually, I don't know where to report this next. Could you please point me in the right direction?

@mfcooney Good morning. I don't think this is a bug. The deprecation message itself states `Important: Starting on June 17, 2019, this parameter is ignored and the value is assumed to be true. The response from this operation always interleaves events from multiple log streams within a log group`. The value is always assumed to be `true` by the service irrespective of whatever value is passed by clients (PowerShell, AWS CLI, etc.). Repository for AWS CLI is https://github.com/aws/aws-cli. Closing this issue.
