### ISSUE TITLE
Unable to copy between s3 buckets in different regions with Copy-S3Object

### ISSUE THREAD

**Issue by redwyre** [aws/aws-tools-for-powershell#216]
## Description

Unable to copy between s3 buckets in different regions with Copy-S3Object, where aws s3 cp is able to.

## Reproduction Steps

`Copy-S3Object -BucketName eco-releases-staging -DestinationBucket eco-releases-eu -Key test.txt -DestinationKey test.txt`
however, using aws cli is fine:
`aws s3 cp s3://eco-releases-staging/test.txt s3://eco-releases-eu/test.txt`

Adding -Region doesn't help

### Logs

Copy-S3Object : The bucket you are attempting to access must be addressed using the specified endpoint. Please send
all future requests to this endpoint.

### Environment

* Build Version: 4.1.12.0
* OS Info: Windows Server 2019 v1809
* Build Environment: N/A
* Targeted .NET Platform:  N/A

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

I guess the commandlet needs to resolve the endpoints like aws s3 cp does?

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @redwyre,

Good afternoon.

The S3 client cannot be configured to "work in both regions". It must be configured with a region so it works in a single region. When copying objects between buckets (between regions), set the S3 client to the target region. Then, specify the source and target buckets.

For your case, the following command (for example works):
```PowerShell
Copy-S3Object -BucketName bucket-us-east-2-1234 -DestinationBucket bucket-us-east-1-1234 -Key testfile -DestinationKey testfile -Region us-east-1

ETag         : "b31e446ce37dab2e3d4f126785f58c08"
BucketName   : bucket-us-east-1-1234
Key          : testfile
LastModified : 4/27/2021 4:35:18 PM
Owner        : Amazon.S3.Model.Owner
Size         : 15
StorageClass : STANDARD
```
Here I had specified the region as `us-east-1` which is the region for destination bucket.

Hope this helps. Closing this issue.

Thanks,
Ashish

**Comment by redwyre** [comment]
```
Copy-S3Object -BucketName eco-releases-staging -DestinationBucket eco-releases-eu -Key test.txt -DestinationKey test.txt -Region eu-central-1
Copy-S3Object : The bucket you are attempting to access must be addressed using the specified endpoint. Please send
all future requests to this endpoint.
```
the first bucket is in `US West (Oregon) us-west-2` and the second is in `EU (Frankfurt) eu-central-1`

Also as I said `aws s3 cp` is able to handle this without being told what region to use, why can't `Copy-S3Object` just do the same?

**Comment by ashishdhingra** [comment]
> ```
> Copy-S3Object -BucketName eco-releases-staging -DestinationBucket eco-releases-eu -Key test.txt -DestinationKey test.txt -Region eu-central-1
> Copy-S3Object : The bucket you are attempting to access must be addressed using the specified endpoint. Please send
> all future requests to this endpoint.
> ```
> 
> the first bucket is in `US West (Oregon) us-west-2` and the second is in `EU (Frankfurt) eu-central-1`
> 
> Also as I said `aws s3 cp` is able to handle this without being told what region to use, why can't `Copy-S3Object` just do the same?

Hi @redwyre,

As you saw earlier in https://github.com/aws/aws-tools-for-powershell/issues/216#issuecomment-828025644, I was able to successfully copy the object from source bucket in `us-east-2` to destination bucket `us-east1` region. For cross region, the current implementation in AWS PowerShell requires explicit region endpoint to be set. Also, for copying objects between regions, you need to have proper IAM permissions. I'm not sure if this is a bug but could be considered as an improvement in the form of `feature-request` in future release. Kindly let me know if this is fine.

Thanks,
Ashish

**Comment by redwyre** [comment]
Maybe you could try buckets in the regions I've used as it's not working for me (`us-west-2` and `eu-central-1`). `aws s3 cp` works fine so it doesn't seem to be a permissions issue.

As specifying region doesn't work in my case, I would definitely consider removing the need for it a fix, but if you want to split it up into making region work as a bugfix and removing it a feature that's up to you.

**Comment by ashishdhingra** [comment]
Hi @redwyre,

Good afternoon.

I'm changing this back to `bug`. I was able to reproduce the issue using the below command:
```PowerShell
Copy-S3Object -BucketName testbucket-issue216-us-west-2 -DestinationBucket testbucket-issue216-eu-central-1 -Key testfile -DestinationKey testfile -Region eu-central-1

Copy-S3Object: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. 
```
Further test revealed that it is also not working for source bucket in `us-east-1` and destination bucket in `us-east-2`.

In my config file, the default region is set as `us-east-2`, not sure if this affecting the copy operation.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
No auto close

**Comment by peterrsongg** [comment]
@redwyre This bug has been addressed in the latest PowerShell release. Closing this issue now.
