### ISSUE TITLE
Docker image with PowerShell tools installed

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-tools-for-powershell#217]
I wish there was a docker image I could use to quickly issue AWS commands both from my pc and from a CircleCI pipeline

## Describe the Feature
Ideally I'd like to be able to do something like

```
> docker run -it --rm aws/powershell pwsh
PS> Install-AWSToolsModule -Name AWS.Tools.ECS
PS> Get-ECSClusterServices
``` 

### Is your Feature Request related to a problem?
I need to force the deployment of many services

## Proposed Solution
Prepare a docker image with the basic tools module installed and the repository already "trusted"

### Describe alternatives you've considered
I could prepare a Dockerfile by my own, but it would be better to have an image curated by AWS

## Additional Context
I need to force the deployment of many services and I prefer using powershell over bash

### Environment
Ideally both Windows and Linux

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @Kralizek,

Good afternoon.

I'm not sure this is a feasible feature request. Microsoft provides `mcr.microsoft.com/windows/servercore:1809` Docker image. You can use this image in your Dockerfile. You can then launch `powershell.exe` instead of `pwsh.exe` and execute `Install-AWSToolsInstaller` to install AWS PowerShell tools installer.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @Kralizek,

Good afternoon.

Just FYI, there is AWS CLI v2 docker image available at https://aws.amazon.com/blogs/developer/aws-cli-v2-docker-image/ where you could use AWS CLI to issue AWS command.

Thanks,
Ashish

**Comment by pcgeek86** [comment]
A few years ago, I created this very simple project, which builds a fresh container image (daily) with all of the AWS PowerShell modules pre-installed.

https://github.com/pcgeek86/aws-powershell-container/pkgs/container/aws-powershell-container

You can use it with:

```
docker pull ghcr.io/pcgeek86/aws-powershell-container:4.1.822
```

Currently there is not a `latest` tag published, so you'll have to reference the list of tags, which is based on the module version.

It had stopped publishing new versions a long time ago, so there's a gap, but I just got the GitHub Actions workflow running again.
