### ISSUE TITLE
Get-EC2Tag - Inconsistency in -Filter hashtable between actual and help

### ISSUE THREAD

**Issue by neman-pcas** [aws/aws-tools-for-powershell#218]
Exactly as per https://github.com/aws/aws-tools-for-powershell/issues/59#issue-513382478 but with Get-EC2Tag documentation rather than Get-EC2Instance documentation. Bug also submitted at https://docs.aws.amazon.com/forms/aws-doc-feedback?service_name=PowerShell-Ref&topic_url=https://docs.aws.amazon.com/powershell/latest/reference/items/Get-EC2InstanceStatus.html

## Description
Documentation at https://docs.aws.amazon.com/powershell/latest/reference/items/Get-EC2Tag.html indicates a filter hashtable that uses a Value**s** key but misspells it Value. The documentation in Get-Help Get-EC2Tag -Examples is also wrong.

## Reproduction Steps
Run the example:
Get-EC2Tag -Filter @{Name="resource-type";Value="image"}

Get the error:
Get-EC2Tag : Cannot bind parameter 'Filter'. Cannot create object of type 
"Amazon.EC2.Model.Filter". The Value property was not found for the 
Amazon.EC2.Model.Filter object. The available property is: [Name <System.String>] 
, [Values <System.Collections.Generic.List`1[[System.String, mscorlib, 
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]>]
At C:\Users\NemanSyed\Documents\Batch\AWSEC2InstanceStop.ps1:36 char:28
+ ... Tag -Filter @{Name="resource-type";Value="instance"},@{Name="key";Val ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-EC2Tag], ParameterBinding 
   Exception
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Amazon.PowerShell.Cm 
   dlets.EC2.GetEC2TagCmdlet

Change Value to Values, and it works.

### Environment

PS C:\WINDOWS\system32> $PSVersionTable
Name                           Value                                                                                                                                                                                         
----                           -----                                                                                                                                                                                         
PSVersion                      5.1.19041.906                                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                       
BuildVersion                   10.0.19041.906                                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                                           
SerializationVersion           1.1.0.1

* Get-AWSPowerShellVersion -ListServiceVersionInfo
AWS Tools for PowerShell
Version 4.1.12.0
Copyright 2012-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Amazon Web Services SDK for .NET
Core Runtime Version 3.7.0.14
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
* OS Info: 
* Build Environment: 

## Resolution
Change Value to Values in the examples, and it works:

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
This has been fixed at https://docs.aws.amazon.com/powershell/latest/reference/items/Get-EC2Tag.html
