### ISSUE TITLE
Prompting to enter MFA every single time

### ISSUE THREAD

**Issue by kbyunAncile** [aws/aws-tools-for-powershell#219]
## The Question
I have configured MFA for my named profile. When I use aws cli, it prompts MFA authentication for the first time. Then it caches it for certain duration or when new profile is detected.  
But for Powershell aws-tool always prompts MFA authentication every time script runs.

for example, if I have a powershell script 
```
Write-Host "aws cli call"
aws s3 ls
Write-Host "Powershell AWS-Tool Call"
Get-S3Bucket
```

for first execution, both calls will ask MFA. But on second execution only Powershell AWS-Tool will ask MFA.
I wonder if there is a configuration for MFA sessions. 

Or maybe it is related to how I'm configuring profile? 
for AWS CLI, I set environment variable `$env:AWS_PROFILE="myprofile"` to desired profile
for Powershell AWS-Tool, I call `Set-AWSCredential -ProfileLocation $env:UserProfile\.aws\config -ProfileName myprofile`

### Environment

* OS Info: Windows 10
* Build Version:
```
AWS Tools for Windows PowerShell
Version 4.0.5.0

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.104.35
```

---

**Comment by ashishdhingra** [comment]
Hi @kbyunAncile,

Good morning.

AWS Tools for PowerShell rely on AWS .NET SDK behind the scenes. Kindly refer the guidance provided in https://github.com/aws/aws-sdk-net/issues/1844#issuecomment-831580377.

Thanks,
Ashish
