### ISSUE TITLE
Get-EC2Subnet  -name  attribute  /AWS Console 

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-tools-for-powershell#220]
Good Day, 

I have come across another anomaly. 

This issue/bug consists of two parts.

Part one : 
If you check the AWS console, you will see that the console offers an option to enter a "name" for the vpc subnets in your account
Yet if you compare this to the documentation for both the "Get-EC2Subnet"  command-let and the "Amazon.EC2.Model.Subnet object"
you will see that the "name" property is not available for the  "Amazon.EC2.Model.Subnet" object, nor is possible to query your subnets based  the  "name" attribute, see the "Get-EC2Subnet" documentation. 

The second part of this anomaly is that when one adds a "name" to a subnet, the "Tags" property is populated with a "{Name}" 
value ,instead of the name added in the AWS Console.
I tested this with several subnets and the behaviour is the same each and every time. 

SubnetId                    : subnet-0dxxxxxb
Tags                        : {Name}

SubnetId                    : subnet-0e7xxx2f
Tags                        : {Name}

SubnetId                    : subnet-1xxxc25
Tags                        : {Name}

This shows yet  another inconsistency between the information in the AWS console and the available API calls. 
And in this case, It also shows that the "Tags" property for the "Amazon_EC2_Model_Subnet" object is unreliable, specifically when you interact with this object using the EC2Console. 
![test](https://user-images.githubusercontent.com/50540203/121878073-94388b00-cd0b-11eb-9086-f2957a9ffe57.JPG)

I have added screenshots to better illustrate my point. 

PowerShell Module:
PS C:\Windows\System32> get-installedModule -name *AWS*

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
4.1.12.0             AWSPowerShell.NetCore               PSGallery            The AWS Tools for PowerShell lets develo…

Powershell version: 

PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Documentation: 
https://docs.aws.amazon.com/powershell/latest/reference/items/Get-EC2Subnet.html
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2Subnet.html&tocid=Amazon_EC2_Model_Subnet

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

Good morning.

Thanks for posting the issue. Upon reviewing the subnet documentation, it appears that the [Amazon EC2 - Subnet - API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Subnet.html) does not have a property `name`. The model in AWS .NET SDK (and hence PowerShell) relies on definitions shared by service and hence appear to be correct. Upon reviewing further, when I create a subnet from AWS VPC console, it clearly specifies that Subnet name is `Create a tag with a key of 'Name' and a value that you specify.`:
<img width="813" alt="Screen Shot 2021-06-14 at 9 57 11 AM" src="https://user-images.githubusercontent.com/67916761/121930727-8bd65500-ccf7-11eb-8877-f030d5d9d0e1.png">

It indicates that the subnet name information is present as value for a tag `Name`. For instance, I create a subnet with name `testsubnet`, it created a tag `Name` with value `testsubnet`:
<img width="1331" alt="Screen Shot 2021-06-14 at 10 08 33 AM" src="https://user-images.githubusercontent.com/67916761/121931628-b674dd80-ccf8-11eb-9002-2080dc888dc5.png">

When PowerShell command `Get-EC2Subnet` is executed, it displays the subnet details. The `Tags` property is an array of `Tag` objects. To view the `Tags`, use `(Get-EC2Subnet).Tags` instead, which displays tag information:
```
Key  Value
---  -----
Name testsubnet
```
To apply `Filter` on `Get-EC2Subnet`, you may use any of the following 2 queries:
- Return all subnets with a tag called "Name" defined:
```PowerShell
Get-EC2Subnet -Filter @{name="tag-key";values="Name"}
```
- Return all subnets with a specific tag "Name" set
 ```PowerShell
Get-EC2Subnet -Filter @{name="tag:Name";values="testsubnet"}
```

Hope this helps.

Thanks,
Ashish

**Comment by manuelh2410** [comment]
Good Day , 

Thanks for investigating, but no, this does not help, nor do your troubleshooting steps represent the steps I took to replicate the behaviour .

**Comment by ashishdhingra** [comment]
> Good Day ,
> 
> Thanks for investigating, but no, this does not help, nor do your troubleshooting steps represent the steps I took to replicate the behaviour .

@manuelh2410 Could you please elaborate on what is missing here and let us know the steps to replicate the behavior> May be something is missing here. I do not see any inconsistency with the API documentation and AWS Console behavior.

**Comment by manuelh2410** [comment]
Good Day ,

Thanks for investigating, your time and your update, but no, this does not help, nor do your troubleshooting steps represent the steps I took to replicate the behaviour .

The object does not contain the -Name attribute , and yet , there is a Name attribute clearly shown in the EC2 console . 
When you interact with the name attribute in the AWS console , the "Tag" attribute of the object is populated . 

You can see how this is unreliable , unexpected and plain wrong

**Comment by ashishdhingra** [comment]
> Good Day ,
> 
> Thanks for investigating, your time and your update, but no, this does not help, nor do your troubleshooting steps represent the steps I took to replicate the behaviour .
> 
> The object does not contain the -Name attribute , and yet , there is a Name attribute clearly shown in the EC2 console .
> When you interact with the name attribute in the AWS console , the "Tag" attribute of the object is populated .
> 
> You can see how this is unreliable , unexpected and plain wrong
> 
> this is clearly a bug

@manuelh2410 As mentioned in my detailed findings, the Name column in the AWS Console specifies the value of tag named `Name`. This is not an bug/issue with the PowerShell tools or AWS .NET SDK.

**Comment by manuelh2410** [comment]
Correct, I found the same issue with 3 other command-lets. 
I know the difference between a  -name attribute, and a "name" "value" tag. The documentation clearly makes that destinction.
So lets not conflate the two . 
The object does not have a name attribute that is correct and we have already established that .But  when I populate the  -name attribute  for an already existing object in the AWS Console, and  then querry my object using the  AWS-Powershell tools  the "Tag" object attribute is populated with an obscure " {Name}" value  instead of listing a -Name attribute ,with the value I added trought the aws console . again , it does not seem very client obsessed to ask or demand that I open yet another case for this issue . And If possible I would like you to discuss this with your superiors or colleagues before pushing back on this .

**Comment by ashishdhingra** [comment]
@manuelh2410 Let me discuss with the team and if possible, would create an issue with appropriate service team. The reason I requested you to open the issue using the Support option is for easy tracking and direct communication from service team. I will post an update here based on my discussion.

**Comment by ashishdhingra** [comment]
Related issues:
- https://github.com/aws/aws-tools-for-powershell/issues/222
- https://github.com/aws/aws-tools-for-powershell/issues/221

**Comment by ashishdhingra** [comment]
Upon further investigation,
**For AWS Console:**
If you click on the settings for Subnet list, it clearly selects `Name` tag by default to display and uses tag name as column name:
<img width="1491" alt="Screen Shot 2021-06-14 at 11 59 01 AM" src="https://user-images.githubusercontent.com/67916761/121944977-1d4dc300-cd08-11eb-9ba5-a2b4afa9f00c.png">

Based on my testing, you have ability to create multiple tags for a subnet and select that Tag to be displayed as a column in the list.
<img width="1074" alt="Screen Shot 2021-06-14 at 12 10 18 PM" src="https://user-images.githubusercontent.com/67916761/121946213-8bdf5080-cd09-11eb-93b5-06566e5a1c2d.png">

**For PowerShell CmdLet:**
The output of the CmdLet is controlled by PowerShell console. The `Tags` property is an array, hence it displays the `Name` property in curly braces. For testing, I added another tag named `CustomTag` and now the output is shown below:
<img width="684" alt="Screen Shot 2021-06-14 at 12 12 54 PM" src="https://user-images.githubusercontent.com/67916761/121946673-06a86b80-cd0a-11eb-888c-5a9c17364989.png">

**Comment by ashishdhingra** [comment]
@manuelh2410 For graphical user interface issues, please submit the feedback using the option provided in the AWS Console. In case you face any PowerShell related issues, feel free to open a new issue.

**Comment by manuelh2410** [comment]
Customer Obsession!!!!!

**Comment by ashishdhingra** [comment]
> Being a graphical user interface, 
> 
> One assumes that the AWS Console is a 1 to 1 representation of objects, attributes, their related data, and the associated API functionality. 
> 
>  
> 
> In line with this, any end-user would assume that the data stored in the NAME column would represent the data linked to the  -Name Parameter of the object being shown (displayed), an not that of a "mapped" to a Tag: key Value pair. 
> 
> 
> 
> In this scenario e both established that this is clearly not the case.
> 
>   
> 
> If you check the example I included you can clearly see that the Get-EC2Image command-let returns both a Name attribute with its corresponding  "my-image" value and a separate Tags attribute with the corresponding, albeit obscure {name} value.
> 
> 
> 
> So please tell me how is it logically sound, to have the Name attribute of an object, not map to the Name column of a graphical user interface displaying that same object. 
> 
> 
> 
> And how is it possible that not all user-configurable objects have a Name attribute, while the console clearly provides a designated "Name" column
> 
> 
> 
> If you like I can check with the graphical user interfaces of competing cloud providers in order to confirm if what I am suggesting /asking is unreasonable. 
> 
> 
> 
> In case someone asks me, Is it safe to conclude that not all object attributes have a 1 to 1 mapping with what is displayed in the AWS console ? 
> 
> 
> 
> https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2Image.html&tocid=Amazon_EC2_Model_Image
> 
> ![Get-EC2Image](https://user-images.githubusercontent.com/50540203/122081355-5157df80-cdff-11eb-9568-5b3e31e2c401.JPG)
> 
> 

@manuelh2410 Yes, I do see some inconsistency between different API s provided by service. I will post this question to service team to get their inputs for this inconsistency and update you accordingly.
