### ISSUE TITLE
Get-EC2volume   -name attribute  and EC2 Console

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-tools-for-powershell#221]
Good Day,

I have come across another anomaly.

This issue/bug consists of two parts.

Part one :
If you check the AWS console, you will see that the console offers an option to enter a "name" for the vpc volumes in your account
Yet if you compare this to the documentation for both the "Get-EC2volume" command-let and the "Amazon.EC2.Model.volume object"
you will see that the "name" property is not available for the "Amazon.EC2.Model.volume" object, nor is possible to query your volumes based the "name" attribute, see the "Get-EC2volume" documentation.

The second part of this anomaly is that when one adds a "name" to a volume, the "Tags" property is populated with a "{Name}"
value ,instead of the name added in the AWS Console.
I tested this with several volumes and the behaviour is the same each and every time.

volumeId : volume-xxxxx8c
Tags : {Name}

volumeId : volume-xxxxxf3a
Tags : {Name}

volumeId : volume-xxxxxxfb
Tags : {Name}

This shows yet another inconsistency between the information in the AWS console and the available API calls.
And in this case, It also shows that the "Tags" property for the "Amazon_EC2_Model_volume" object is unreliable, specifically when you interact with this object using the EC2Console.

I have added screenshots to better illustrate my point.

PowerShell Module:
PS C:\Windows\System32> get-installedModule -name AWS

Version Name Repository Description

4.1.12.0 AWSPowerShell.NetCore PSGallery The AWS Tools for PowerShell lets develo…

Powershell version:

PS C:\Windows\System32> $PSVersionTable

Name Value

PSVersion 7.1.3
PSEdition Core
GitCommitId 7.1.3
OS Microsoft Windows 10.0.19042
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0

https://docs.aws.amazon.com/powershell/latest/reference/items/Get-EC2Volume.html
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2Volume.html&tocid=Amazon_EC2_Model_Volume
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2DescribeVolumesResponse.html&tocid=Amazon_EC2_Model_DescribeVolumesResponse
![volumes](https://user-images.githubusercontent.com/50540203/121902667-d2dc3e80-cd27-11eb-8f9e-f88091b8f8de.JPG)

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

Good morning.

Looks like this issue is similar to the other one opened by you https://github.com/aws/aws-tools-for-powershell/issues/220.

Upon reviewing the subnet documentation, it appears that the [Amazon EC2 - Volume - API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Volume.html) does not have a property `name`. The model in AWS .NET SDK (and hence PowerShell) relies on definitions shared by service and hence appear to be correct. Upon reviewing further, when I create a volume from AWS EC2 console, it provides option to add a Name tag (there is no Name field):
<img width="1285" alt="Screen Shot 2021-06-14 at 10 28 47 AM" src="https://user-images.githubusercontent.com/67916761/121933813-66e3e100-ccfb-11eb-9aec-d185c1fc68a2.png">

After I specify `Name` tag, it populates volume list and the value in `Name` column (which corresponds to Name tag value).
<img width="1237" alt="Screen Shot 2021-06-14 at 10 31 12 AM" src="https://user-images.githubusercontent.com/67916761/121934054-aad6e600-ccfb-11eb-88bd-7e7bd6140182.png">

When the PowerShell cmdlet `Get-EC2Volume`, it displays details of the volume(s) where `Tags` property is an array. To view the tags, use the command `(Get-EC2Volume).Name`:
```
Key  Value
---  -----
Name testvolume
```

As noted in https://github.com/aws/aws-tools-for-powershell/issues/220, you may use `Filter` parameter to results of `Get-EC2Volume` cmdlet.

Hence, there doesn't appear to be any inconsistency with the functionality in AWS console and documentation.

Hope this helps.

Thanks,
Ashish

**Comment by manuelh2410** [comment]
Good Day ,

Thanks for investigating, your time and your update, but no, this does not help, nor do your troubleshooting steps represent the steps I took to replicate the behaviour .

The object does not contain the -Name attribute , and yet , there is a Name attribute clearly shown in the EC2 console . 
When you interact with the name attribute in the AWS console , the "Tag" attribute of the object is populated . 

You can see how this is unreliable , unexpected and plain wrong

**Comment by ashishdhingra** [comment]
> Good Day ,
> 
> Thanks for investigating, your time and your update, but no, this does not help, nor do your troubleshooting steps represent the steps I took to replicate the behaviour .
> 
> The object does not contain the -Name attribute , and yet , there is a Name attribute clearly shown in the EC2 console .
> When you interact with the name attribute in the AWS console , the "Tag" attribute of the object is populated .
> 
> You can see how this is unreliable , unexpected and plain wrong

@manuelh2410 As mentioned in my detailed findings, the Name column in the AWS Console specifies the value of tag named `Name`. This is not an bug/issue with the PowerShell tools or AWS .NET SDK.

**Comment by manuelh2410** [comment]
Correct, I found the same issue with 3 other command-lets. 
I know the difference between a  -name attribute, and a "name" "value" tag. The documentation clearly makes that destinction.
So lets not conflate the two . 
The object does not have a name attribute that is correct and we have already established that .But  when I populate the  -name attribute  for an already existing object in the AWS Console, and  then querry my object using the  AWS-Powershell tools  the "Tag" object attribute is populated with an obscure " {Name}" value  instead of listing a -Name attribute ,with the value I added trought the aws console . again , it does not seem very client obsessed to ask or demand that I open yet another case for this issue . And If possible I would like you to discuss this with your superiors or colleagues before pushing back on this .

**Comment by ashishdhingra** [comment]
@manuelh2410 Let me discuss with the team and if possible, would create an issue with appropriate service team. The reason I requested you to open the issue using the Support option is for easy tracking and direct communication from service team. I will post an update here based on my discussion.

**Comment by ashishdhingra** [comment]
Related issue https://github.com/aws/aws-tools-for-powershell/issues/220

**Comment by ashishdhingra** [comment]
Upon further investigation,
**For AWS Console**
Create Network Interface allows to assign tags. For testing, tag named `Name` and value `TestNI` was created. The Network Interface list displayed the value of this tag in Name column:
<img width="794" alt="Screen Shot 2021-06-14 at 12 21 04 PM" src="https://user-images.githubusercontent.com/67916761/121947563-05c40980-cd0b-11eb-9a32-5dae8f613fe2.png">

Clicking on Settings for the list displays dialog which selects `Name` tag by default to be displayed as one of the columns:
<img width="1482" alt="Screen Shot 2021-06-14 at 12 22 07 PM" src="https://user-images.githubusercontent.com/67916761/121947731-3e63e300-cd0b-11eb-9b0e-5471fece5ef4.png">
Hence, clearly, Name column is mapped to tag named `Name`.

**Comment by manuelh2410** [comment]
Being a graphical user interface, 
One assumes that the AWS Console is a 1 to 1 representation of objects, attributes, their related data, and the associated API functionality. 
 
In line with this, any end-user would assume that the data stored in the NAME column would represent the data linked to the  -Name Parameter of the object being shown (displayed), an not that of a "mapped" to a Tag: key Value pair. 

In this scenario e both established that this is clearly not the case.
  
If you check the example I included you can clearly see that the Get-EC2Image command-let returns both a Name attribute with its corresponding  "my-image" value and a separate Tags attribute with the corresponding, albeit obscure {name} value.

So please tell me how is it logically sound, to have the Name attribute of an object, not map to the Name column of a graphical user interface displaying that same object. 

And how is it possible that not all user-configurable objects have a Name attribute, while the console clearly provides a designated "Name" column

If you like I can check with the graphical user interfaces of competing cloud providers in order to confirm if what I am suggesting /asking is unreasonable. 

In case someone asks me, Is it safe to conclude that not all object attributes have a 1 to 1 mapping with what is displayed in the AWS console ? 

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2Image.html&tocid=Amazon_EC2_Model_Image
![Get-EC2Image](https://user-images.githubusercontent.com/50540203/122081574-7fd5ba80-cdff-11eb-87d6-ee08cbe300b1.JPG)

**Comment by ashishdhingra** [comment]
@manuelh2410 For graphical user interface issues, please submit the feedback using the option provided in the AWS Console. In case you face any PowerShell related issues, feel free to open a new issue.

**Comment by manuelh2410** [comment]
Customer Obsession!!!!!

**Comment by manuelh2410** [comment]
![Uploading Get-EC2Image_Output.JPG…]()
