### ISSUE TITLE
Missing configuration  parameters 

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-tools-for-powershell#224]
Good Day, 

I encountered yet another inconsistency. 

This time is with the Register-EC2Image command-let. 

I registered a new AMI using this command-let and used the -Name parameter in order to specify a name for my AMI (image) . 
Upon opening the EC2 console, I was yet again unpleasantly surprised. 

I observed that the "AMI Name" column was populated with the value I specified for the  -Name parameter. 
I don't think it's unreasonable or strange to expect that the "Name" column would be populated in this scenario. 

Neither the Register-EC2Image nor Get-EC2Image command-lets contain an "AMI Name" configuration parameter. 
neither do they list "AMI Name" as an alias for the "-name" configuration parameter. 

I need to create "how-to guides" for my colleagues using screenshots of the AWS console as a reference and this poses a significant problem for me. These user guides are crucial in my companies adoption of the AWS platform.
![Register-EC2Image](https://user-images.githubusercontent.com/50540203/122615882-a0b14080-d089-11eb-806e-c1462d42f5a1.JPG)
![Get-EC2Image_Output](https://user-images.githubusercontent.com/50540203/122615906-a9097b80-d089-11eb-90bb-c1059bbe595c.JPG)

can you expound on this?

**Comment by manuelh2410** [comment]
I posed similar issues in the past and you promised me to get back to me , in the spirit of customer obsession I am going to ask that this request remains open until we have come to a suitable resolution.

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

Good afternoon.

Thanks for reporting yet another inconsistency. If you refer AWS CLI documentation https://docs.aws.amazon.com/cli/latest/reference/ec2/register-image.html as well, it used `--name` parameter for AMI Name, wheres in AWS Console UI, it displays the column as `AMI Name`. As mentioned in earlier issues, all SDKs and CLI tools depend on service API models and not dependent on the UI of the AWS Console. I had already reported the inconsistency mentioned in earlier issue(s) with service team and would include this inconsistency as well.

Based on your suggestion I will keep this issue open until we receive response from service team.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
P48650004

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

Good afternoon.

I have received response from service team. The inconsistency in UI design and for some APIs (reported in other issues) date back to pre tag-on-create times, and are unlikely to change since literally thousands of customers are now expecting this behavior for their existing code. So, unfortunately, the AWS Console and service API behavior is unlikely to change.

There is nothing SDK could change since it is dependent on the service behavior and does not control the UI design of the AWS console. Hence, closing this ticket.

Thanks,
Ashish
