### ISSUE TITLE
'https://checkip.amazonaws.com?format=json'  issues 

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-tools-for-powershell#227]
It seems that the following API call Invoke-RestMethod -Uri 'https://checkip.amazonaws.com?format=json'
returns a response with an additional "blank" character appended 

This results in two issues. 

1.Incorrect character length reported by Powershell, see below: $webip.length
2.Unable to properly append additional strings (characters) to the object returned by the API response (in this case the IP address returned by the API endpoint)
3.The "Trim()" method has zero effect on the string response returned by the "https://checkip.amazonaws.com" API endpoint. 

The Trim() method should in essence remove all blank spaces from the API response.
$webip.Trim() 

I compared this behavior to that of other (more reliable) free API endpoints and concluded that this issue is specific to "checkip.amazonaws.com". 

The reference API endpoints I used were : 

- https://ip.seeip.org?format=json
  command string:
  [string]$webip = (Invoke-RestMethod -Uri 'https://ip.seeip.org?format=json')

- https://api.ipify.org?format=text
  [string]$webip = (Invoke-RestMethod -Uri 'https://api.ipify.org?format=text')

My aim is to append "/32" to the API response and then use this new string "x.x.x.x/32" in the rest of my workflow. 
When using your endpoint this results in 

193.148.18.61
/32

which is not a single string. 

See my test results below: 

Kindly ignore the "C:\Program Files (x86)\Google\Cloud SDK>" working directory, I am in the process of migrating workloads to google. 

https://checkip.amazonaws.com  test sequence: 
=============================================
PS C:\Program Files (x86)\Google\Cloud SDK> [string]$webip = (Invoke-RestMethod -Uri 'https://checkip.amazonaws.com?format=json')
PS C:\Program Files (x86)\Google\Cloud SDK> $webip
193.148.18.61
PS C:\Program Files (x86)\Google\Cloud SDK> $webip.length
14
PS C:\Program Files (x86)\Google\Cloud SDK> $webip.Trim()
193.148.18.61
PS C:\Program Files (x86)\Google\Cloud SDK> $webip.length
14
PS C:\Program Files (x86)\Google\Cloud SDK> $webip[13]

PS C:\Program Files (x86)\Google\Cloud SDK> $webip[12]
1
PS C:\Program Files (x86)\Google\Cloud SDK> $MyIP = "$webip$Sub"
PS C:\Program Files (x86)\Google\Cloud SDK> $myip
193.148.18.61
/32
PS C:\Program Files (x86)\Google\Cloud SDK> $myip[13]

PS C:\Program Files (x86)\Google\Cloud SDK> $myip[14]
/

Control Method: https://ip.seeip.org
====================================
[string]$webip = (Invoke-RestMethod -Uri 'https://ip.seeip.org?format=json')

PS C:\Program Files (x86)\Google\Cloud SDK> [string]$webip = (Invoke-RestMethod -Uri 'https://ip.seeip.org?format=json')

PS C:\Program Files (x86)\Google\Cloud SDK> $webip
193.148.18.61
PS C:\Program Files (x86)\Google\Cloud SDK> $webip.length 
13
PS C:\Program Files (x86)\Google\Cloud SDK> $webip.Trim()
193.148.18.61
PS C:\Program Files (x86)\Google\Cloud SDK> $webip.length
13

PS C:\Program Files (x86)\Google\Cloud SDK> $sub="/32"

PS C:\Program Files (x86)\Google\Cloud SDK> $MyIP = "$webip$Sub"
PS C:\Program Files (x86)\Google\Cloud SDK> $myip
193.148.18.61/32

PS C:\Program Files (x86)\Google\Cloud SDK> $myip[13]
/
PS C:\Program Files (x86)\Google\Cloud SDK> $myip[14]
3

======================================

This is scary because I almost incorporated this endpoint into my solution.
If you are planning to continue to offer this endpoint to the public, can you please ensure that it at least adheres to standards? 
By offering this endpoint you are setting the expectation that its responses are usable.

**Comment by ashishdhingra** [comment]
Hi @manuelh2410,

Good morning.

The `Invoke-RestMethod` is the CmdLet provided in the module [Microsoft.PowerShell.Utility](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1). Upon checking further, if we access the URL https://checkip.amazonaws.com?format=json directly in web browser, the response appear to have extra line at the end (as viewed in Page source):
<img width="575" alt="Screen Shot 2021-06-28 at 8 49 29 AM" src="https://user-images.githubusercontent.com/67916761/123666308-f2766b00-d7ed-11eb-8899-d30941be5478.png">

The output of `Invoke-RestMethod` could vary as mentioned at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1#outputs. In this case the output it of type `System.String` and using `Trim()` works, in my case:
- `$webip.Length` returns 13
- `$webip.Trim().Length` returns 12
- `$webip.Trim()+"/32"` returns `xx.xx.xxx.xx/32`).

Unfortunately, this repository is for reporting issues with the AWS PowerShell tools CmdLets and not sure if we can do anything to control the response for this endpoint. I will open a ticket with service team for them to address this issue where extra line is returned in the response.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
> Good Day,
> Thanks for your response, if we are waiting for feedback from the service team why are we closing this ticket?
> It doesn't seem very customer-obsessed it seems you are in a hurry to close this

@manuelh2410 The issue is neither related to AWS .NET SDK/PowerShell, nor related to services supported by SDK. This is a separate service hosted for checking the IP (I saw some reference to it in AWS CLI documentation). Hence closed this ticket. From customer obsession standpoint, I have opened issue internally so that it is eventually taken care by appropriate team. Request you to use the workaround to use the `Trim()` function until the issue is resolved.

**Comment by manuelh2410** [comment]
Also $webip.Trim()+"/32" does work , that is correct . 
but why does one need to resort to this in order to concatenate these strings? 

The fact is that I have a specific need to concatenate the two variables exactly in the way mentioned in my example above. 
Why is it not mentioned that the API returns blank characters?

**Comment by ashishdhingra** [comment]
P49142220

**Comment by ashishdhingra** [comment]
@manuelh2410 As per service team, there is no standard for "What's My IP" services, and making this change to remove extra line to a mature service could have significant consequences to other mature services and customers. You could use the `Trim()` Powershell method (https://devblogs.microsoft.com/scripting/trim-your-strings-with-powershell/) to get the same result. (NOTE: This is not the issue with AWS Powershell tools or .NET SDK)

**Comment by manuelh2410** [comment]
Good Day,
the service is "checkmyip" . not "checkmyipandspaces" 
Users querying this API are expecting their public IP address, not their public IP address and spaces. 
Its evident that AWS has a clear problem with both presenting data and tools to end-users .
