### ISSUE TITLE
S3 PowerShell Command Issues

### ISSUE THREAD

**Issue by RandomGuy2322** [aws/aws-tools-for-powershell#229]
## Description
Running Write-S3Object in PowerShell comes out with a method issue.

## Reproduction Steps
Install all necessary Powershell packages (AWS.Tools and AWSPowerShell.NetCore).
Attempt a Write-S3Object command (it worked at first, but then broke and unsure how).

### Logs
Write-S3Object : Method not found: 'System.IAsyncResult Amazon.Runetime.SharedInteraces.ICoreAmazonS3.BeginDelete(System.String, System.String,System.Collections.Generic.IDictionary`2<System.String,System.Object>, System.AsyncCallback,System.Object)'.

### Environment

* SDK Version: Unknown
* Package Version: Unknown
* OS Info: Server 2019 hosted on an EC2 instance with proper IAM roles attached
* Build Environment PowerShell
* Targeted .NET Platform:  Unknown

Summary: I had this command working and it actually Did upload the file to the S3 bucket. However after I closed out of ISE and reopened it to reset my session, it stopped working. I didn't change anything that should've affected this command and am unsure as to how to fix it.

This is using the AWSCLIv2 install also.

Any help is greatly appreciated.

Thank you.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @RandomGuy2322,

Good morning.

I have transferred your issue to AWS PowerShell repository. Could you please share the version of AWS PowerShell Tools installed (using the CmdLet `Get-AWSPowerShellVersion`)? If it is not the latest version, please update your AWS PowerShell tools to latest version.

Also are you using Windows PowerShell (assuming yes) or PowerShell Core 7.x? Windows PowerShell sometimes has inconsistent behavior which gets resolved by itself. Do you get the issue using PowerShell Core 7.x?

AWS CLI v2 install should not have any impact on `Write-S3Object` CmdLet.

Thanks,
Ashish

**Comment by RandomGuy2322** [comment]
Hello,

After running Get-AWSPowerShellVersion, it is saying the AWS Tools for Windows PS is 4.0.2.0. It also says Amazon Web Services SDK for .NET, Core Runtime Version 3.3.104.13.

I believe I am using Windows PowerShell 7, however I am unsure 100%.

**Comment by ashishdhingra** [comment]
@RandomGuy2322 Since You are using PowerShell ISE, it's most probably using Windows PowerShell. Could you try upgrading to latest version of AWS Tools for PowerShell? There have been many releases after version `4.0.2.0`.

**Comment by RandomGuy2322** [comment]
Hi @ashishdhingra, apologies for the delay. It has been a busy time.

So I Think I was able to upgrade the AWS Tools version by using the AWS.Tools.Installer for PowerShell. I tried to do an Import-Module AWS.Tools.S3 however I received an error that goes "Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.14.0\AWSSDK.Core.dll' or one of its dependencies. Operation is not supported."

Any thoughts?

Thank you.

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra, apologies for the delay. It has been a busy time.
> 
> So I Think I was able to upgrade the AWS Tools version by using the AWS.Tools.Installer for PowerShell. I tried to do an Import-Module AWS.Tools.S3 however I received an error that goes "Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\AWS.Tools.Common\4.1.14.0\AWSSDK.Core.dll' or one of its dependencies. Operation is not supported."
> 
> Any thoughts?
> 
> Thank you.

Hi @RandomGuy2322,

Thanks for your response. In the past, we have noticed some weird issues on Windows PowerShell where it would not load modules, these errors usually self-resolve by themselves. Few suggestions:
- Please follow instructions on [Installing the AWS Tools for PowerShell on Windows](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html) to re-install `AWS.Tools` modules (like S3).
- You might want to Uninstall the existing modules first and also cleanup `file:///C:\Program Files\WindowsPowerShell\Modules` and `C:\Users\username\Documents\WindowsPowerShell` directories.
- Launch PowerShell prompt as `Administrator`.
- As a last resort, please try using PowerShell 7+, installing the AWS Tools module there.

Hope this helps.

Thanks,
Ashish
