### ISSUE TITLE
AWS Security Hub - import custom findings using Import-SHUBFindingsBatch 

### ISSUE THREAD

**Issue by jzold** [aws/aws-tools-for-powershell#23]
**Expected Behavior**
Using the Import-SHUBFindingsBatch using JSON as input (compliant as per https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-providers.html#securityhub-custom-providers) the import should return a HTTP 200 response
**Current Behavior**
> Import-SHUBFindingsBatch -Finding $json
Import-SHUBFindingsBatch : Cannot bind parameter 'Finding'. Cannot convert the "{
    "Findings":  [
                     {...
}
}" value of type "System.String" to type "Amazon.SecurityHub.Model.AwsSecurityFinding".
At line:1 char:35
+ Import-SHUBFindingsBatch -Finding $json
+                                   ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-SHUBFindingsBatch], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Amazon.PowerShell.Cmdlets.SHUB.ImportSHUBFindingsBatchCmdlet

It looks like the JSON string is not casted properly into an Amazon.SecurityHub.Model.AwsSecurityFinding object. When trying to cast the JSON string it gives the following error:

>[Amazon.SecurityHub.Model.AwsSecurityFinding]$json 
Cannot convert the "{
    "Findings":  [...
... ]
}" value of type "System.String" to type "Amazon.SecurityHub.Model.AwsSecurityFinding".
At line:1 char:1
+ [Amazon.SecurityHub.Model.AwsSecurityFinding]$json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException

**Possible Solution**
This could be a mistake on my side or maybe a .NET SDK issue?

**Steps to Reproduce (for bugs)**
note: sensitive data has been removed (AwsAccountId, ProductArn)
$json = @'
{
    "Findings": [{
        "AwsAccountId": "12345678912",
        "CreatedAt": "2019-06-27T19182:58Z",
        "Description": "This is a custom finding",
        "GeneratorId": "api-test",
        "Id": "eu-west-2/12345678912/98aebb2207407c87f51e89943f12b1ef",
        "ProductArn": "arn:aws:securityhub:eu-west-2:12345678912:product/12345678912/default",
        "Resources": [{
            "Type": "Other",
            "Id": "i-dsdfhsefdj"
        }],
        "SchemaVersion": "2018-10-08",
        "Severity": {
            "Product": 2.5,
            "Normalized": 11
        },
        "Title": "Security Finding from Custom Software",
        "Types": [
            "Software and Configuration Checks/Vulnerabilities/CVE"
        ],
        "UpdatedAt": "2019-06-27T22:22:58Z"
    }]
}
'@
> Import-SHUBFindingsBatch -Finding $json
Import-SHUBFindingsBatch : Cannot bind parameter 'Finding'. Cannot convert the "{
    "Findings": [{
        "AwsAccountId": "12345678912",
        "CreatedAt": "2019-06-27T19182:58Z",
        "Description": "This is a custom finding",
        "GeneratorId": "api-test",
        "Id": "eu-west-2/12345678912/98aebb2207407c87f51e89943f12b1ef",
        "ProductArn": "arn:aws:securityhub:eu-west-2:12345678912:product/12345678912/default",
        "Resources": [{
            "Type": "Other",
            "Id": "i-dsdfhsefdj"
        }],
        "SchemaVersion": "2018-10-08",
        "Severity": {
            "Product": 2.5,
            "Normalized": 11
        },
        "Title": "Security Finding from Custom Software",
        "Types": [
            "Software and Configuration Checks/Vulnerabilities/CVE"
        ],
        "UpdatedAt": "2019-06-27T22:22:58Z"
    }]
}" value of type "System.String" to type "Amazon.SecurityHub.Model.AwsSecurityFinding".
At line:1 char:35
+ Import-SHUBFindingsBatch -Finding $json
+                                   ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-SHUBFindingsBatch], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Amazon.PowerShell.Cmdlets.SHUB.ImportSHUBFindingsBatchCmdlet
**Context**
Not able to import custom findings into AWS Security Hub

**Your Environment**
* Affected module: AWSPowerShell 
* Module version as reported by `Get-AWSPowerShellVersion`: Version 3.3.522.0
* Operating System and version as reported by `$PSVersionTable.OS`: $psversiontable does not have an OS property (at least on my version of W10 ) but:
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0       
* PowerShell verions as reported by `$PSVersionTable.PSEdition`:
PSVersion                      5.1.17763.503
PSEdition                      Desktop

**Comment by matteo-prosperi** [comment]
Hello,
if you check `Get-Help Import-SHUBFindingsBatch` it shows that `Import-SHUBFindingsBatch` doesn't take a json string but an [Amazon.SecurityHub.Model.AwsSecurityFinding](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecurityHub/TAwsSecurityFinding.html) object.
This is why the error contains `Cannot convert the [...] value of type "System.String" to type "Amazon.SecurityHub.Model.AwsSecurityFinding"`.

You should instead create the object like this:
```
$finding = [Amazon.SecurityHub.Model.AwsSecurityFinding] @{
  AwsAccountId = '012345678912';
  Compliance = @{
    Status = 'PASSED' };
  CreatedAt = '2019-06-27T19182:58Z';
  Resources = @(
    @{
      Type = 'Other';
      Id = 'i-dsdfhsefdj' } ) }
```

**Comment by jzold** [comment]
hi @matteo-prosperi,

Thanks for the quick response and help, much appreciated. When I'm trying to create the object based on your advice it still doesn't work - surely I'm missing something obvious:
```
$finding = [Amazon.SecurityHub.Model.AwsSecurityFinding] @{
  AwsAccountId = 012345678912;
  CreatedAt = '2019-06-13T22:22:58Z';
  Description = ' this is a test!';
  GeneratorId = 'Some-TestID';
  Id = 'us-east-1/012345678912/98aebb2207407cg7f51e81943f13b1ef';
  ProductArn = 'arn:aws:securityhub:us-east-1:012345678912:product/012345678912/default';
  Resources = @(
    @{
      Id = 'testsdgsd';
      Type = 'Other';
      });
  SchemaVersion = '2018-10-08';
  Severity = @{
      Product = 2.5;
      Normalized = 11
    };
   Title = 'Some test Title!';
   UpdatedAt = '2019-06-13T22:22:58Z';
   Types = @('Unusual Behaviors/Process')
}
Cannot create object of type "Amazon.SecurityHub.Model.AwsSecurityFinding". Cannot convert the "System.Object[]" value of type "System.Object[]" to type "Amazon.SecurityHub.Model.Resource".
At line:1 char:1
+ $finding = [Amazon.SecurityHub.Model.AwsSecurityFinding] @{
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ObjectCreationError
```

Thanks for the help in advance

**Comment by matteo-prosperi** [comment]
I checked and you code snippet works fine on PowerShell 6. On PowerShell 5 I get the same error as you.
I can solve the problem by specifying the type of the array I create for the `Resources` field (just add `[Amazon.SecurityHub.Model.Resource[]]` before `@(`).

```
$finding = [Amazon.SecurityHub.Model.AwsSecurityFinding] @{
  AwsAccountId = 012345678912;
  CreatedAt = '2019-06-13T22:22:58Z';
  Description = ' this is a test!';
  GeneratorId = 'Some-TestID';
  Id = 'us-east-1/012345678912/98aebb2207407cg7f51e81943f13b1ef';
  ProductArn = 'arn:aws:securityhub:us-east-1:012345678912:product/012345678912/default';
  Resources = [Amazon.SecurityHub.Model.Resource[]] @(
    @{
      Id = 'testsdgsd';
      Type = 'Other';
      });
  SchemaVersion = '2018-10-08';
  Severity = @{
      Product = 2.5;
      Normalized = 11
    };
   Title = 'Some test Title!';
   UpdatedAt = '2019-06-13T22:22:58Z';
   Types = @('Unusual Behaviors/Process')
}
```

**Comment by jzold** [comment]
thanks @matteo-prosperi, it works great :)
