### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by amehta-rms** [aws/aws-tools-for-powershell#231]
## The Question

Hi, the latest version was released on June 25th and since then, there have been many releases of AWS CLI. 
Are there plans to release a new version with updates and fixes anytime soon?

Thanks.

**Comment by ashishdhingra** [comment]
@amehta-rms Yes, we plan on updating as soon as possible. We are working on some internal changes before we can do the release.

**Comment by ashishdhingra** [comment]
Closing this issue for now. Please check for the updates in change log when the new release is done.

**Comment by ashishdhingra** [comment]
New AWS Tools for PowerShell `4.1.15.0` has been released.
