### ISSUE TITLE
Update-AWSToolsModule / Install-Module Causing Signature Error On Upgrade to 4.1.15.0

### ISSUE THREAD

**Issue by klementi** [aws/aws-tools-for-powershell#232]
## The Question

When updating to 4.1.15.0 using Update-AWSToolsModule in AWS.Tools.Installer module the following error may occur:

Error validating manifest signature for AWS.Tools.Common

To fix this problem update to version 1.0.2.2 or higher of the AWS.Tools.Installer (Install-Module AWS.Tools.Installer -SkipPublisherCheck -Force) and run the command as:

Update-AWSToolsModule -SkipPublisherCheck

This issue can also occur if you have an existing version of AWS PowerShell installed and try to Install-Module MODULE_NAME -Force. The following error will be reported:

     | Authenticode issuer 'CN="Amazon Web Services, Inc.", OU=SDKs and Tools, O="Amazon Web Services, Inc.", L=Seattle, S=Washington, C=US,
     | SERIALNUMBER=4152954, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US, OID.2.5.4.15=Private Organization' of the new module
     | 'AWS.Tools.Installer' with version '1.0.2.2' from root certificate authority 'CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc,
     | C=US' is not matching with the authenticode issuer 'CN="Amazon Web Services, Inc.", OU=AWS, O="Amazon Web Services, Inc.", L=Seattle, S=Washington,
     | C=US' of the previously-installed module 'AWS.Tools.Installer' with version '1.0.2.1' from root certificate authority 'CN=DigiCert Assured ID Root
     | CA, OU=www.digicert.com, O=DigiCert Inc, C=US'. If you still want to install or update, use -SkipPublisherCheck parameter.

To fix this problem run Install-Module MODULE_NAME -Force -SkipPublisherCheck

**Comment by nsandar** [comment]
I saw the same thing. I did a full uninstall of all the prior modules AND installers, installed the fresh `AWS.Tools.Installer` and was able to make it go, but it definitely took 30+ minutes of beating my head against the wall to make it work.

Not great.

**Comment by jbilinski** [comment]
It's my belief that CA changes like this need to be overt. I appreciate the Announcement label from @klementi and trust this is a legitimate change. But next time it may not be, and it would be good policy to announce this at top of release notes and as publicly as possible on a secondary trusted platform -- perhaps on docs.aws.amazon.com: 
https://docs.aws.amazon.com/powershell/latest/userguide/pstools-security.html 
and the PowerShell galley:
https://www.powershellgallery.com/packages/AWS.Tools.Common/

**Comment by kimvais** [comment]
For future reference, to fix this for _all_ installed modules:

```powershell
foreach ($mod in Get-InstalledMoule AWS.Tools.*) { Install-module $mod.name -Force -SkipPublisherCheck }
```
