### ISSUE TITLE
Add retry and backoff options

### ISSUE THREAD

**Issue by ryancbutler** [aws/aws-tools-for-powershell#233]
All commands currently require handling and adding backoffs of `RATE EXCEEDED` errors which can be tedious when utilizing numerous commands. Boto3 has this feature [built-in](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html) which would be great to see in the PowerShell module

## Describe the Feature
Add a global retry variable and function to handle errors such as `RATE EXCEEDED`

### Is your Feature Request related to a problem?
Having to handle each and every command is very time-consuming and frustrating. Especially with the commands that have built-in pagination like `get-wksworkspace` where the token needs to be manually handled along with any errors for each command. 

## Proposed Solution
Each command should handle basic errors where a retry and backoff is needed and allow the retry amount to be configurable

### Describe alternatives you've considered
Not so much a solution but the current workaround is catching `RATE EXCEEDED` error and retrying with [backoff](https://docs.aws.amazon.com/general/latest/gr/api-retries.html) 

## Additional Context
It would greatly speed up development with Powershell if I could expect to return results every time I run a command and not have to deal with hitting rate limits or not. This seems especially problematic with the Workspaces service.

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @ryancbutler,

Good morning.

Could you please refer guidance in https://github.com/aws/aws-tools-for-powershell/issues/179#issuecomment-718115199 and see if the retry option available in AWS SDK for .NET works for you? AWS Tools for PowerShell is built on top of AWS .NET SDK and the available retry options should work.

Thanks,
Ashish

**Comment by BradyShober** [comment]
The AWS_MAX_ATTEMPTS and AWS_RETRY_MODE environment variables still do not appear to work in AWS PowerShell for handling Rate exceeded errors.
