### ISSUE TITLE
Get-SQServiceQuotaList -ServiceCode events|ecs returns no data

### ISSUE THREAD

**Issue by tomcart90** [aws/aws-tools-for-powershell#239]
## Description
I'm using the AWS.Tools.ServiceQuotas module and have found that no data is returned when attempting to lookup service quota information for ecs and event bridge, both of the following simply return nothing:
`Get-SQServiceQuotaList -ServiceCode events`
`Get-SQServiceQuotaList -ServiceCode ecs`

## Reproduction Steps
With an authenticated session run the following commands:
`Get-SQServiceQuotaList -ServiceCode events`
`Get-SQServiceQuotaList -ServiceCode ecs`

### Logs
No logging here unfortunately, the lack of any results is all I have to go off.

### Environment
* Build Version: AWS.Tools.ServiceQuotas build 4.1.15.0
* OS Info:
```
> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @tomcart90,

Good afternoon.

Could you please confirm the following:
- If the same command works using AWS CLI, i.e., by using `aws service-quotas list-service-quotas --service-code ecs`, for example?
- You may also enable detailed PowerShell response logging using guidance provided in article [Response Logging in AWS Tools for Windows PowerShell](https://aws.amazon.com/blogs/developer/response-logging-in-aws-tools-for-windows-powershell/), which could help troubleshoot the issue at service response level.

Thanks,
Ashish
