### ISSUE TITLE
Write-S3Object throws error when using the -Stream parameter

### ISSUE THREAD

**Issue by pcgeek86** [aws/aws-tools-for-powershell#244]
## Description

Streaming a file from an HTTP download source to the `Write-S3Object` command fails with error.

> Write-S3Object: Specified method is not supported.

⚠️ The [documentation for Write-S3Object](https://docs.aws.amazon.com/powershell/latest/reference/items/Write-S3Object.html) doesn't include an example for using the `-Stream` parameter.

![image](https://user-images.githubusercontent.com/466713/144769895-ab9919bf-2552-4461-9995-d89fec161669.png)

## Reproduction Steps

1. Run a fresh PowerShell Container, bind mounting your local AWS credentials file

```
docker run --rm -it --mount "type=bind,src=$HOME//.aws//,dst=/root/.aws" mcr.microsoft.com/powershell
```

2. Install AWS PowerShell Module

```powershell
Install-Module -Name AWS.Tools.S3 -Scope CurrentUser -Force
```

3. Send a .NET Stream Directly to S3

```powershell
$TargetBucket = 'YOURBUCKETNAMEGOESHERE'
$src = 'https://releases.ubuntu.com/20.04.3/ubuntu-20.04.3-desktop-amd64.iso'
$webclient = [System.Net.WebClient]::new()
$srcstream = $webclient.OpenRead($src)
Write-S3Object -BucketName $TargetBucket -Key ubuntu-20.04.3-desktop-amd64.iso -Stream $srcstream
```

### Environment
* Windows 11
* Docker Desktop 

```
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:47:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @pcgeek86,

Good morning.

The probable explanation on why this doesn't work is that the underlying stream returned by is not seekable.

```PowerShell
PS /> $src = 'https://releases.ubuntu.com/20.04.3/ubuntu-20.04.3-desktop-amd64.iso'
PS /> $webclient = [System.Net.WebClient]::new()
PS /> $srcstream = $webclient.OpenRead($src)
PS /> $srcstream.CanSeek
False
``` 

The `Write-S3Object` CmdLet uses `AWSSDK.Core` and `AWSDK.S3` behind the scenes. It makes use of `TransferUtility` which requires stream to be seekable. Kindly try using `Write-S3Object` CmdLet using the seekable stream (e.g. stream created from a file on your local disk), it should work.

Also refer existing feature request https://github.com/aws/aws-sdk-net/issues/675, which also suggests a workaround in https://github.com/aws/aws-sdk-net/issues/675#issuecomment-571725444, not sure how easily it could be ported to your PowerShell code.

Thanks,
Ashish

**Comment by pcgeek86** [comment]
Thanks for sharing the root cause. I am not sure how to create a seekable stream for a file download, but I will have to defer that to another time.
