### ISSUE TITLE
Problem with private nuget repository and short version numbers

### ISSUE THREAD

**Issue by TPoessel** [aws/aws-tools-for-powershell#245]
## Description
In nuspec version numbers are defined without full digits (e.g. 4.1.17 instead of 4.1.17.0). In pds1 the module version is defined with full digits (e.g. 4.1.17.0). When installing e.g. AWSPowershell.Netcore with PSGallery everything works fine. Then save the nuget package and publish it to any private nuget repository. When installing the package with private repository installing works fine but Import-Module fails with message "The specified module 'AWSPowershell.Netcore' was not loaded because no valid module file was found in any module directory."
The problem is caused by version number in module folder. There the version number is store as e.g. 4.1.17. This causes the error because the version that is needed would be 4.1.17.0. after renaming the folder importing is possible.

## Reproduction Steps
- Move AWSPowershell.Netcore to any private nuget repository (even local file system is possible)
- install module 
- try to load the module
- look at the version number in file system e.g. c:\Program Files\WindowsPowerShell\Modules\AWSPowerShell.NetCore\

### Environment
- OS Info: Windows 10 / Windows Server 2019
- PSVersion: 5.1.17763.2268
- all other installed tools in enterprise ready LT versions

## Resolution
- sync version number in nuspec and psd1 module information

**Comment by ashishdhingra** [comment]
Hi @TPoessel,

Good morning.

As mentioned in the issue https://github.com/aws/aws-tools-for-powershell/issues/161#issuecomment-833114368, the mentioned behavior (where 4th part in the version number is sometimes missing) is sometimes seen on Windows PowerShell 5.0 and we cannot control this behavior. The issue disappears after certain number of retries. Could you try replicating the same behavior on PowerShell Core 7+?

Thanks,
Ashish

**Comment by TPoessel** [comment]
I did a test with ps 7.2.1 x64. There the problem is fixed and everything is fine. So no more need to leave this issue open.
