### ISSUE TITLE
Write-S3Object doesnt complete for large files

### ISSUE THREAD

**Issue by Rolf-Herbert** [aws/aws-tools-for-powershell#246]
## Description

When initiating an upload using Write-S3Object for a large file (20-40gb) the transfer starts and then at some random point fails with

Write-S3Object : Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service.

## Reproduction Steps
Just start a Write-S3Object to a valid bucket and using valid profiles

### Environment
Windows server 2019
powershell
build 4.1.18.0

Thanks for any help.
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @Rolf-Herbert,

Good morning.

Thanks for reporting the issue. Could you please follow the article [Response Logging in AWS Tools for Windows PowerShell](https://aws.amazon.com/blogs/developer/response-logging-in-aws-tools-for-windows-powershell/) to enable detailed logging and share the logs for further analysis? Also advise if the error occurs intermittently and the CmdLet succeeds for some large files.

Thanks,
Ashish

**Comment by Rolf-Herbert** [comment]
Ok ill see if I can get that extra debug info out.

**Comment by Rolf-Herbert** [comment]
It just started working again, which is good I guess, but not knowing why it failed is not so good =)

thanks

**Comment by ashishdhingra** [comment]
Closing this issue for now. Feel free to reopen in case error happens again.
