### ISSUE TITLE
Get-EC2FlowLog filter issue

### ISSUE THREAD

**Issue by esxi1979** [aws/aws-tools-for-powershell#249]
## Description
Is this cmdlet to check VPC flowlog status ? 

if yes i tried below 

PS /root>  Get-EC2FlowLog -Filter @{Name="resource-id ";Value="vpc-dxxx"}

Get-EC2FlowLog: Cannot bind parameter 'Filter'. Cannot create object of type "Amazon.EC2.Model.Filter". The Value property was not found for the Amazon.EC2.Model.Filter object. The available property is: [Name <System.String>] , [Values <System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>]
PS /root>

Google search do not give any clue. 
Pls suggest , thanks 

## Reproduction Steps
Pls see above 
### Logs
Pls see above 

### Environment

CentOS 7

PS /root> Get-AWSPowerShellVersion

AWS Tools for PowerShell
Version 4.1.29.0
Copyright 2012-2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.7.8.1
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License
[http://logging.apache.org/log4net/license.html]

## Resolution
NA

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @esxi1979,

Good morning.

The `Filter` object expects a **List of values** in `Values` property. Kindly refer service API documentation at https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Filter.html and AWS PowerShell documentation at https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TFilter.html. For your scenario, `Get-EC2FlowLog` needs to have `-Filter` as shown below:
```PowerShell
Get-EC2FlowLog -Filter @{Name="resource-id ";Values="vpc-dxxx"}
```

For passing multiple values for `Values` property, you could use something like below:
```PowerShell
Get-EC2FlowLog -Filter @{Name="resource-id ";Values="vpc-dxxx","vpc-dxyz"}
```

Hope this helps. Closing this issue as guidance.

Thanks,
Ashish

**Comment by esxi1979** [comment]
@ashishdhingra 

Thanks for the response. I think you overlooked my message , i did what you sating to start with & got the error & hence i raise this bug, pls check 

PS /root> Get-EC2FlowLog -Filter @{Name="resource-id ";Value="vpc-dxxx"}

Get-EC2FlowLog: Cannot bind parameter 'Filter'. Cannot create object of type "Amazon.EC2.Model.Filter". The Value property was not found for the Amazon.EC2.Model.Filter object. The available property is: [Name <System.String>] , [Values <System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>]
PS /root>

**Comment by ashishdhingra** [comment]
@esxi1979 From the screenshot it appears that you are still using the incorrect property name `Value`. Please review my comment, you need to use `Values` (notice extra `s` at the end).

**Comment by esxi1979** [comment]
@ashishdhingra  Thank You.
