### ISSUE TITLE
Get-EC2FlowLog filter issue #249

### ISSUE THREAD

**Issue by esxi1979** [aws/aws-tools-for-powershell#250]
## Description

It seems the solution suggested in #249 , is what i already tried. I updated the #249 

But as that is closed. I raised this new one. 

Again here is the error , pls suggest if i am doing anything wrong 

Set-AWSCredential & Initialize-AWSDefaultConfiguration was set already

This is Ubuntu OS : ( WSL ) 

PS /root> Get-AWSPowerShellVersion

AWS Tools for PowerShell
Version 4.1.16.0
Copyright 2012-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.7.5.0
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

![image](https://user-images.githubusercontent.com/6848403/156042364-3f07bc18-0042-47bc-815c-12339ac09181.png)

**Comment by ashishdhingra** [comment]
@esxi1979 From the screenshot it appears that you are still using the incorrect property name `Value`. Please review my comment, you need to use `Values` (notice extra `s` at the end).

**Comment by esxi1979** [comment]
@ashishdhingra  Thank You.
