### ISSUE TITLE
Read-S3Object with -KeyPrefix doesn't work

### ISSUE THREAD

**Issue by rpmrmartin** [aws/aws-tools-for-powershell#265]
### Describe the bug

`Read-S3Object` doesn't download any objects when `-KeyPrefix` is specified.

### Expected Behavior

All the objects in the specified bucket with the specified key prefix are downloaded to the specified folder.

### Current Behavior

No objects are downloaded.

![image](https://user-images.githubusercontent.com/49652977/169600650-36c4ba36-eaa5-4446-9de6-5328f93a42f4.png)

### Reproduction Steps

Run `Read-S3Object`, specifying `-BucketName`, `-KeyPrefix`, and `-Folder`.

### AWS Tools for PowerShell version used

4.1.89

### PowerShell version used

| Name           |                Value |
| ----   |                        ----- |
| PSVersion  |                    7.2.4 |
PSEdition          |            Core
GitCommitId       |             7.2.4
OS                 |            Microsoft Windows 10.0.19044
Platform         |              Win32NT
PSCompatibleVersions          | {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion  |    2.3
SerializationVersion          | 1.1.0.1
WSManStackVersion         |     3.0

### Operating System and version

Windows 10 Pro for Workstations 21H2 19044.1706

**Comment by ashishdhingra** [comment]
Reproducible.

- PS command ` Get-S3Object -BucketName <<bucketname>> -KeyPrefix 'rpmdev/2022-04-29' | Format-Table` returns the following output:
```
ChecksumAlgorithm ETag                               BucketName           Key                          LastModified         Owner                 Size StorageClass
----------------- ----                               ----------           ---                          ------------         -----                 ---- ------------
{}                "e02808103e9d31d114e876004e9e604c" <<bucketname>> rpmdev/2022-04-29-ABCDEF.txt 5/20/2022 4:00:13 PM Amazon.S3.Model.Owner 3139 STANDARD
{}                "e02808103e9d31d114e876004e9e604c" <<bucketname>> rpmdev/2022-04-29-ABCDUI.txt 5/20/2022 4:00:13 PM Amazon.S3.Model.Owner 3139 STANDARD
{}                "e02808103e9d31d114e876004e9e604c" <<bucketname>> rpmdev/2022-04-29-ACEFGH.txt 5/20/2022 4:00:14 PM Amazon.S3.Model.Owner 3139 STANDARD
{}                "e02808103e9d31d114e876004e9e604c" <<bucketname>> rpmdev/2022-04-29-ZRTYUI.txt 5/20/2022 4:00:14 PM Amazon.S3.Model.Owner 3139 STANDARD
```
- Turning on verbose logging using PS command `Read-S3Object -BucketName <<bucketname>> -KeyPrefix 'rpmdev/2022-04-29' -Folder '<<full_path_to_folder>>' -Verbose` produces the following output:
```
VERBOSE: Invoking Amazon S3 object download APIs in region 'us-east-2'
VERBOSE: Downloaded 0 object(s) from bucket '<<bucketname>>' with keyprefix 'rpmdev/2022-04-29' to '<<full_path_to_folder>>'
```
- Executing the below .NET Core (using `AWSSDK.S3` version `3.7.9.4`) doesn't download anything:
```C#
using Amazon.S3;
using Amazon.S3.Transfer;

namespace TransferUtilityDownloadDirectoryTest
{
    class Program
    {
        static string bucketName = "<<bucketname>>";
        static string localDirectory = "<<full_path_to_folder>>";
        static string keyPrefix = "rpmdev/2022-04-29";

        static void Main(string[] args)
        {
            var request = new TransferUtilityDownloadDirectoryRequest
            {
                BucketName = bucketName,
                LocalDirectory = localDirectory,
                S3Directory = keyPrefix
            };

            using (var tu = new TransferUtility(new AmazonS3Client()))
            {
                tu.DownloadDirectory(request);
            }
        }
    }
}
```

**Comment by ashishdhingra** [comment]
We have implemented new parameter `DisableSlashCorrection` for `Read-S3Object` in the AWS Tools for PowerShell version `4.1.132`. Please set this parameter to `$true` for your scenario which would then not add trailing `/` to the `KeyPrefix` value.
