### ISSUE TITLE
Feature Request: Add option to always use proxy for AWS Powershell commands without Set-AWSProxy

### ISSUE THREAD

**Issue by Risae** [aws/aws-tools-for-powershell#266]
### Describe the feature

Currently its only possible to use "Set-AWSProxy Cmdlet" to move the command through a proxy, but once the powershell window is closed the proxy is not used anymore. For environment that needs to always let the AWS commands travel through a proxy it would help to force the use of the proxy whenever a AWSPowershell command is executed. The AWS SSM Agent already supports this but not AWSPowershell.

### Use Case

Multi-cloud or Cloud + on premise enviroments with proxy setups for AWS communication will benefit from this feature. Already supported by the AWS SSM Agent.

### Proposed Solution

Maybe a simple config file where you can specify the proxy you want to use?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

AWS Poweshell 4.1.54

### PowerShell version used

PowerShell 5.1

### Operating System and version

Windows Server 2016/2019

**Comment by Clifra-Jones** [comment]
You could add it to your profile file?
Using VS Code
`PS> code $profile`
Add the appropriate commands to the profile
Save the file.
This might not meet all your needs but it would be a quick fix.

**Comment by Risae** [comment]
> @Risae Thanks for submitting the feature request. May be using proxy by default should be controlled by some sort of flag, may be in environment variable, since using it by default would be a breaking change for existing customers. This feature request needs to be reviewed with the team for further consideration and assigning priority.

Awesome, hope you can incorporate some kind of flag/option to always use the SSM Agent proxy configuration (the SSM Agent saves the proxy config in the windows registry)
