### ISSUE TITLE
Cannot assume roles interactively through SAML if there are more than 26 options

### ISSUE THREAD

**Issue by mitchellrj** [aws/aws-tools-for-powershell#27]
**Expected Behavior**
Assuming a role via SAML should allow the user to use any role in the returned claim.

**Current Behavior**
1. Use `Set-AWSSamlRoleProfile` to authenticate and get a list of roles that may be assumed
2. The list of roles is displayed in the console, with a letter of the alphabet next to each one, used to select it
3. After `Z`, the options are displayed, but there is no means of selecting them.

**Possible Solution**
* Use numbers for the selection instead.
* Fall back to allowing the role ARN to be entered as input after displaying the list

**Steps to Reproduce (for bugs)**
1. Create and integrate a SAML provider
2. Create a user credential that returns > 26 values for the role claim
3. Authenticate via `Set-AWSSamlRoleProfile`

**Context**
Workaround is to specify the role on the command line using the `-PrincipleArn` and `-RoleArn` options, but this is not very user friendly.

**Your Environment**
Include as many relevant details about the environment where the bug was discovered.
* Affected module (AWSPowerShell or AWSPowerShell.NetCore):  ¯\_(ツ)_/¯
* Module version as reported by `Get-AWSPowerShellVersion`: 3.3.542.0
* Operating System and version as reported by `$PSVersionTable.OS`: Windows 10 (1809) (suggested command returns no value)
* PowerShell verions as reported by `$PSVersionTable.PSEdition`: 5.1.17763.1 (Desktop)

**Comment by bogdanpopey** [comment]
i think this is more an issue than an enhancement :). Thanks Richard for reporting this.

**Comment by matteo-prosperi** [comment]
PowerShell (PromptForChoice)[https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.promptforchoice] capability is limited to shortcuts being a single character and case insensitive.

In order to address this we would need to reimplement PromptForChoice. I will investigate this further.

**Comment by 0ni0nrings** [comment]
hello, any update on this issue? I have got the same problem, I am using AWS tools for PowerShell and have more than 26 roles to assume. The alphabets run out after [Z] and the remaining roles show up without any character.
