### ISSUE TITLE
Unable to pipe (Get-ECRLoginCommand).Password to --password-stdin

### ISSUE THREAD

**Issue by Eternal21** [aws/aws-tools-for-powershell#270]
### Describe the bug

AWS documentation states that in order to authenticate with docker the following command should be used using Powershell:
`(Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`

That command fails with the following error:
`Error response from daemon: login attempt to https://aws_account_id.dkr.ecr.us-east-1.amazonaws.com/v2/ 
failed with status: 400 Bad Request`

You will also get the same error if trying the AWS CLI version within Powershell terminal:
`aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`

The AWS CLI version works correctly from CMD terminal.

Googling around I found that the reason for the failure is that the first part of the script before the pipe, is appending a newline to the password, before it's being piped to the second part of the script.  You can work around it using the following:
`$password = (Get-ECRLoginCommand).Password`
`docker login --username AWS --password $password aws_account_id.dkr.ecr.region.amazonaws.com`
The problem with this workaround is that you end up with the following warning:
`WARNING! Using --password via the CLI is insecure. Use --password-stdin.`

I was able to figure out a hack that bypasses the warning by taking advantage of the fact that this bug does not exist in CMD terminal, and calling CMD version of the command from Powershell instead:
`cmd.exe \c "your command"`
`cmd.exe \c "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.us-east-1.amazonaws.com"`

### Expected Behavior

I expected the command to return:
`Login Succeeded`

### Current Behavior

I got the following error instead:
`Error response from daemon: login attempt to https://aws_account_id.dkr.ecr.us-east-1.amazonaws.com/v2/ 
failed with status: 400 Bad Request`

### Reproduction Steps

1. Run the following command in Powershell:
`(Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`

2. Alternatively run the AWS CLI version of the command in Powershell:
`aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`

### Possible Solution

Some solutions may be:
1. Prevent the (Get-ECRLoginCommand).Password from appending newline before piping it to --password-stdin
2. Have --password-stdin trim the appended newline
3. Add some pipe in-between to trim the newline

### Additional Information/Context

It's most likely because `echo` always appends a newline: https://stackoverflow.com/questions/9280591/avoid-newline-in-echo

### AWS Tools for PowerShell version used

AWS.Tools 4.1.100

### PowerShell version used

5.1.19041.1682

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @Eternal21,

Good afternoon.

Thanks for reporting the issue. Looks like you are referring to the **Step 2** section documentation link [Using Amazon ECR with the AWS CLI](https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html).

Upon investigating further, looks like you also need to use the `-Region` parameter in `Get-ECRLoginCommand` CmdLet. For example, both commands for PowerShell CmdLet and AWS CLI from PowerShell prompt works (tried this on Mac terminal):
```PowerShell
PS /tmp> aws ecr get-login-password --region <<region>> | docker login --username AWS --password-stdin <<aws_account_id>>.dkr.ecr.<<region>>.amazonaws.com
Login Succeeded
PS /tmp> (Get-ECRLoginCommand -Region <<region>>).Password | docker login --username AWS --password-stdin <<aws_account_id>>.dkr.ecr.<<region>>.amazonaws.com
Login Succeeded
```

Also, not using `-Region` parameter in your workaround also doesn't work.
```PowerShell
PS /tmp> $password = (Get-ECRLoginCommand).Password
PS /tmp> docker login --username AWS --password $password <<aws_account_id>>.dkr.ecr.<<region>>.amazonaws.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to https://<<aws_account_id>>.dkr.ecr.<<region>>.amazonaws.com/v2/ failed with status: 400 Bad Request
PS /tmp> $password = (Get-ECRLoginCommand -Region <<region>>).Password
PS /tmp> docker login --username AWS --password $password <<aws_account_id>>.dkr.ecr.<<region>>.amazonaws.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
PS /tmp>  
```

Could you please verify that using `-Region` parameter works for you? This appears to be a documentation issue. Thereafter, please also use [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AmazonEC2ContainerRegistry&topic_url=http://docs.aws.amazon.com/en_us/AmazonECR/latest/userguide/getting-started-cli.html) link at the bottom of the page to submit your feedback for missing `-Region` parameter in PowerShell CmdLet usage.

Thanks,
Ashish

**Comment by Eternal21** [comment]
Thanks for looking into this @ashishdhingra 

Adding `-Region` parameter results in the same error.  I also double-checked my original finding of splitting the query into two parts (and not using `-Region`).  I confirmed it works (with the insecure warning).

I believe the problem is I am doing this on a Windows machine, while you are trying to reproduce the issue on a Mac.  Unfortunately I do not have a Mac available.  I am fairly certain the issue will turn out to be that extra new-line appended to the password.  I am not sure how Powershell handles producing/piping output behind the scenes, but if it's using `echo` then the behavior will be different on Windows vs. Mac: https://apple.stackexchange.com/a/173837

**Comment by Eternal21** [comment]
I found a stack-overflow issue discussing the pipe line-feed problem: https://stackoverflow.com/questions/28504847/powershells-pipe-adds-linefeed

The `cmd \c "command"` method I stumbled upon via trial and error, is listed as one of the potential workarounds

**Comment by ashishdhingra** [comment]
Need to compare the behavior between Windows PowerShell 5.x and PowerShell Core 7.x. BTW, Windows PowerShell doesn't get any updates.

@Eternal21 Could you also try to reproduce the issue using PowerShell Core 7.x on Windows machine and see if it works?

**Comment by Eternal21** [comment]
@ashishdhingra I confirmed it works fine with PowerShell Core 7.2.5 on Windows, so the issue can only be reproduced with PowerShell 5.x.  Sadly since Microsoft refuses to install PowerShell Core on Windows Desktop and Server machines by default, and insists on only installing 5.x, we're stuck with it for a few more years at least (that beside the fact that Core only supports a subset of 5.x functionality).

**Comment by Eternal21** [comment]
@ashishdhingra I can no longer reproduce the issue.  The only change I made on my end since reporting this, is updating docker recently, so perhaps their cli is now working around newlines in objects passed via `--password-stdin` (I did not see any references to that in release notes).  Either that or something changed on AWS ECR backend authentication.  Closing this, since it appears to work correctly now.

**Comment by Costello90** [comment]
I ran the Get-ECRLoginCommand command. The answer showed me the possible use cases for Get-ECRLoginCommand: Username, Password, Endpoints, Command...
Executed the command (Get-ECRLoginCommand).Command. I was given a command with a password that I need to copy and execute.
As an example
docker login --username AWS --password ey.............V9 https://.........dkr.ecr.us-east-1.amazonaws .com
-> Enter
Answer
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
This is an analogy to how @Eternal21 did

**Comment by ymartin59** [comment]
Forget about it, the definitive solution is [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper). You may read https://wadehuang36.medium.com/use-aws-ecr-credential-helper-with-multiple-accounts-4c38b7ee37d

**Comment by ymartin59** [comment]
Or else I have found this work-around, sending command to `cmd.exe`:
```
"aws ecr get-login-password --region ${Env:CDK_DEFAULT_REGION} | docker login --username AWS --password-stdin ${Env:CDK_DEFAULT_ACCOUNT}.dkr.ecr.${Env:CDK_DEFAULT_REGION}.amazonaws.com" | cmd.exe
```

**Comment by a-harbuz** [comment]
Another dance with tambourines. It seems that the AWS team does not test their code at all, and is not responsible for what is written in the manual. It’s easier to set up your own server and administer it than to use such a cloud service. In terms of time, it takes significantly less time.
