### ISSUE TITLE
Write-EVBEvent: Cannot find type [PutEventsRequestEntry]

### ISSUE THREAD

**Issue by comfytoday** [aws/aws-tools-for-powershell#273]
### Describe the bug

Full error:

`New-Object : Cannot find type [PutEventsRequestEntry]: verify that the assembly containing this type is loaded`

PowerShell version:
5.1.19041.1682

### Expected Behavior

Attempt to send the $entry in $events. 

### Current Behavior

Fails to send, citing the Type for $entry does not exist on the system. 

### Reproduction Steps

Sometimes the code works, sometimes it doesn't. I haven't been able to isolate what the root cause is though. Assuming it is something to do with the installation and underlying system changes. 

Installation steps:

```
Install-Module -Name AWS.Tools.EventBridge
```

OR

```
Install-Module -Name AWS.Tools.Installer
Install-AWSToolsModule -Name EventBridge -CleanUp
```

Code:

```
$entry = New-Object -Type Amazon.EventBridge.Model.PutEventsRequestEntry

$entry.Detail = $detailObject
$entry.Source = "inbound"
$entry.DetailType = "record sent"
$entry.Time = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"

Write-EVBEvent -ProfileName $awsProfile -Region $region -Entry $events -Select "*" 

```

### AWS Tools for PowerShell version used

**# Machine 1:**

 4.1.97     AWS.Tools.Common
 4.1.97     AWS.Tools.EventBridge
 1.0.2.4    AWS.Tools.Installer

**# Machine 2:**

4.1.111    AWS.Tools.Common                 
4.1.111    AWS.Tools.EventBridge

### PowerShell version used

**# Machine 1:**

Name                           Value
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**# Machine 2 (AWS WorkSpaces)**

Name                           Value                                                                                                                                                                      
PSVersion                      5.1.14393.5127                                                                            
PSEdition                      Desktop                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                   
BuildVersion                   10.0.14393.5127                                                                           
CLRVersion                     4.0.30319.42000                                                                           
WSManStackVersion              3.0                                                                                       
PSRemotingProtocolVersion      2.3                                                                                       
SerializationVersion           1.1.0.1

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@comfytoday The problem appears to be with the Windows PowerShell 5.x. I have seen instances where the new modules are installed in the incorrect version directory which causes other related issues. The issue self-resolves by itself after multiple retries to install a module. This behavior is not controlled by AWS modules installer. Have you tried using PowerShell Code 7.x, which is more consistent?

Thanks,
Ashish

**Comment by comfytoday** [comment]
@Ashish thanks, yes I started to go down the path of trying PowerShell 7.. it's not ideal though as the final production workload is running on an external machine, so it's even more stuff we'll have to install/ask permission for..... argh. 

> The issue self-resolves by itself after multiple retries to install a module

I'm assuming no one has successfully figured out exactly how to solve this issue? Are you suggesting to just uninstall/reinstall over and over until it works? Or keep doing install with -AllowClobber?

Thanks

**Comment by comfytoday** [comment]
@ashishdhingra I switched over to PS 7, and the same problem persists.

Uninstalled all traces of AWS.Tools modules, reinstalled using both options. No change.

> Cannot find type [PutEventsRequestEntry]: verify that the assembly containing this type is loaded.

----

Name                           Value
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by ashishdhingra** [comment]
> @ashishdhingra I switched over to PS 7, and the same problem persists.
> 
> Uninstalled all traces of AWS.Tools modules, reinstalled using both options. No change.
> 
> > Cannot find type [PutEventsRequestEntry]: verify that the assembly containing this type is loaded.
> 
> Name Value PSVersion 7.2.4 PSEdition Core GitCommitId 7.2.4 OS Microsoft Windows 10.0.14393 Platform Win32NT PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} PSRemotingProtocolVersion 2.3 SerializationVersion 1.1.0.1 WSManStackVersion 3.0

@comfytoday Looks like module is not auto-loaded by the PowerShell session. Please execute `Import-Module AWS.Tools.EventBridge` prior to executing above script and it works.

Thanks,
Ashish
