### ISSUE TITLE
Send-SSMCommand: document AWS-ConfigureAWSPackage does not support parameters

### ISSUE THREAD

**Issue by taylorchurch** [aws/aws-tools-for-powershell#276]
### Describe the bug

Running Send-SSMCommand with document AWS-ConfigureAWSPackage with parameter or parameters flag reports error as unsupported by document. But this is required to pass the name of the package. 

![RunCommand_InstallCloudWatch_Broken](https://user-images.githubusercontent.com/73327482/176772414-c5f2be10-1906-4d95-9426-a5b5b0322d09.JPG)

aws cli works 

![RunCommand_InstallCloudWatch_WorkingAWScli](https://user-images.githubusercontent.com/73327482/176772461-7bb34eba-7232-4e25-b5b9-9e52d7146f38.JPG)

### Expected Behavior

succesfuuly runs. 

### Current Behavior

Errors out. 

### Reproduction Steps

Try command in the screenshot. awscli works with parameters. 

### AWS Tools for PowerShell version used

AWS.Tools.SimpleSystemsManagement 4.1.42

### PowerShell version used

7.2.5

### Operating System and version

Windows 10

**Comment by taylorchurch** [comment]
I originally submitted this bug but I got a 404 so I tried a test and it went through, thats why I came back and edited to correct it.

**Comment by ashishdhingra** [comment]
@taylorchurch Thanks for opening the bug report. Could you try using the latest version of `AWS.Tools.SimpleSystemsManagement` package. I tried using the current version `4.1.118.0` (installed using `Install-AWSToolsModule AWS.Tools.SimpleSystemsManagement -Cleanup`) and it worked successfully:

```PowerShell
❯ $params='{"action":["Install"],"installationType":["Uninstall and reinstall"],"version":[""],"additionalArguments":["{}"],"name":["AmazonCloudWatchAgent"]}' | ConvertFrom-Json -AsHashtable

❯ $params

Name                           Value
----                           -----
installationType               {Uninstall and reinstall}
action                         {Install}
additionalArguments            {{}}
version                        {}
name                           {AmazonCloudWatchAgent}

❯  Send-SSMCommand -DocumentName "AWS-ConfigureAWSPackage" -InstanceId "i-0ff2e6a1625b66fc6" -Parameter $params -CloudWatchOutputConfig_CloudWatchOutputEnabled $true -Region us-east-2

CloudWatchOutputConfig : Amazon.SimpleSystemsManagement.Model.CloudWatchOutputConfig
CommandId              : 3486e6ce-5788-4251-82be-82ee77cb9db7
Comment                :
CompletedCount         : 0
DeliveryTimedOutCount  : 0
DocumentName           : AWS-ConfigureAWSPackage
DocumentVersion        : $DEFAULT
ErrorCount             : 0
ExpiresAfter           : 7/5/2022 9:55:21 PM
InstanceIds            : {i-0ff2e6a1625b66fc6}
MaxConcurrency         : 50
MaxErrors              : 0
NotificationConfig     : Amazon.SimpleSystemsManagement.Model.NotificationConfig
OutputS3BucketName     :
OutputS3KeyPrefix      :
OutputS3Region         : us-east-2
Parameters             : {[action, Amazon.Runtime.Internal.Util.AlwaysSendList`1[System.String]], [additionalArguments,
                         Amazon.Runtime.Internal.Util.AlwaysSendList`1[System.String]], [installationType,
                         Amazon.Runtime.Internal.Util.AlwaysSendList`1[System.String]], [name,
                         Amazon.Runtime.Internal.Util.AlwaysSendList`1[System.String]]…}
RequestedDateTime      : 7/5/2022 6:55:21 PM
ServiceRole            :
Status                 : Pending
StatusDetails          : Pending
TargetCount            : 1
Targets                : {}
TimeoutSeconds         : 3600
```

Kindly note that your EC2 instance should be a managed SSM node (refer https://aws.amazon.com/premiumsupport/knowledge-center/systems-manager-ec2-instance-not-appear/ for troubleshooting purposes).

Thanks,
Ashish

**Comment by taylorchurch** [comment]
Hello,

It is working with latest version 4.1.119, I will accept that. thank you!!
