### ISSUE TITLE
Set-AwsCredential -StoreAs "profileName" should update both location in Windows

### ISSUE THREAD

**Issue by Clifra-Jones** [aws/aws-tools-for-powershell#278]
### Describe the feature

In Windows Set-AwsCredential with the -StoreAs parameter in Windows only updates the SDKStore credentials and not the credentials in the shared file in .aws/credentials.

If you are running a script to update the credential profiles this is fine if all you are doing is using PowerShell or .Net But if you are updating these credentials for use with the CLI this will not work.

To update the shared file you must use the -ProfileLocation parameter, which does not update the encrypted .Net location. This has the potential for these 2 locations to get out of sync. 

Thus, by default Get-AwsCredential pulls from the SDKStore first, so if you use the -StoreLocation and later use Get-AwsCredential you will possibly pull older credentials.

I understand that some may not want the shared file to get populated and that's fine but I believe it would make more sense if that were an extra parameter i.e. -SdkStoreAs

-StoreAs stores in the text file in .aws and the SDKStore
-SdkStoreAs stores only in the SDKStore

This would make the scripts that use Set-AWSCredential more cross platform friendly are the behavior in Linux is that -StoreAs saves to the text file in .aws.

### Use Case

I am writing Powershell scripts that pull access keys from SecretsManager and then update the local profile so other scripts can use these credentials. This allows us to automate rotating credentials. I noticed that the scripts works as expected in Linux but in Windows the text file in .aws was not getting updated which has the potential to make CLI commands to fail when the older credentials get inactivated.

### Proposed Solution

Make the -StoreAs parameter save to both the SDKStore and the shared file .aws/credential.
Add a new parameter -AskStoreAs that only stores to the SDKStore.

What I've had to do to keep the 2 locations in sync is use 2 statements, one with the -StoreLocation and one without.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

Aws.Tools.Common version 4.1.115

### PowerShell version used

Core 7.2.5

### Operating System and version

Windows and Linux

**Comment by Clifra-Jones** [comment]
Just so I fully understand, Using the -ProfileLocation parameter updates the shared credential file but not the encrypted store? Or does it update both? If the former in order for them to be in sync I need to issue the command twice, as I am doing now.

**Comment by ashishdhingra** [comment]
> Set-AWSCredential

@Clifra-Jones If you refer documentation for `-ProfileLocation` at [Set-AWSCredential](https://docs.aws.amazon.com/powershell/latest/reference/items/Set-AWSCredential.html), it specifies that:
- If this optional parameter is omitted this cmdlet will search the encrypted credential file used by the AWS SDK for .NET and AWS Toolkit for Visual Studio first.
- If the profile is not found then the cmdlet will search in the ini-format credential file at the default location: (user's home directory)\.aws\credentials.
- If this parameter is specified then this cmdlet will **only** search the ini-format credential file at the location given.

So yes, you would need to issue the command twice.

The above behavior is controlled by the underlying AWS SDK for .NET, and not at the CmdLet level.

Thanks,
Ashish
