### ISSUE TITLE
Get-CFResourceTag's output only shows Keys

### ISSUE THREAD

**Issue by matteo-prosperi** [aws/aws-tools-for-powershell#29]
Because of the double level of incapsulation in `Amazon.CloudFront.Model.ListTagsForResourceResponse`, Get-CFResourceTag's output only shows Keys.

**Possible Solution**
Implement a custom formatter for `Amazon.CloudFront.Model.ListTagsForResourceResponse`

**Steps to Reproduce (for bugs)**
Invoke `Get-CFResourceTag` or
```
$tags = [Amazon.CloudFront.Model.Tags] @{}
$tags.Items.Add( [Amazon.CloudFront.Model.Tag] @{Key = 'k1'; Value = 'v1'} )
$tags.Items.Add( [Amazon.CloudFront.Model.Tag] @{Key = 'k2'; Value = 'v2'} )
$tags
```
**Expected Behavior**
```
Key Value
--- -----
k1  v1
k2  v2
```
**Current Behavior**
```
Items
-----
{k1, k2}
```
**Context**
A workaround is available:
```
(Get-CFResourceTag ...).Items
```
or 
```
Get-CFResourceTag ... |  Select-Object -ExpandProperty Items
```
show the expected list with both keys and values

**Comment by ashishdhingra** [comment]
We might need to write formatting file and link it to PowerShell module, reference https://docs.microsoft.com/en-us/powershell/scripting/developer/format/formatting-file-overview?view=powershell-7.1
