### ISSUE TITLE
Get-CAAuthorizationToken  is throwing error

### ISSUE THREAD

**Issue by ashishdhingra** [aws/aws-tools-for-powershell#299]
### Discussed in https://github.com/aws/aws-tools-for-powershell/discussions/296

<div type='discussions-op-text'>

<sup>Originally posted by **rjacquemin** October  6, 2022</sup>
### Describe the bug

using powershelltool for some CI scripts since a while

Everything was working fine but suddenly  `Get-CAAuthorizationToken`  is showing error 
After some investigation look like a breaking change was introduce in version  4.1.165

Error message 
```
Get-CAAuthorizationToken: Value cannot be null. (Parameter 'Options property cannot be empty: ClientName')
```

### Expected Behavior

Considering we are logged in with AWS SSO 
We should be able to get the Auth Token without pbm using aws powershel tool

```
aws sso login
aws codeartifact login --tool dotnet --repository xxxx  --domain xxxx --domain-owner xxxxx 

Install-Module -Name AWS.Tools.Installer -Force -MaximumVersion 1.0.2.4
Install-AWSToolsModule AWS.Tools.SSO -CleanUp -Force 
Install-AWSToolsModule AWS.Tools.SSOOIDC -CleanUp -Force 
Install-AWSToolsModule AWS.Tools.CodeArtifact -CleanUp -Force 
Import-Module -Name AWS.Tools.SSO, AWS.Tools.SSOOIDC
Get-CAAuthorizationToken -Region us-east-1 -Domain "xxxxx" -DomainOwner "xxxxx" -Select "AuthorizationToken"
```

It was working before but stop working lately

### Current Behavior

to facilitate the repro 
i used docker image 
```
aws sso login
aws codeartifact login --tool dotnet --repository xxxx  --domain xxxx --domain-owner xxxxx 

docker run --rm -it -v C:\Users\xxxxxx/.aws:/root/.aws:ro mcr.microsoft.com/dotnet/core/sdk:3.1 pwsh
```

```
Install-Module -Name AWS.Tools.Installer -Force -MaximumVersion 1.0.2.4
Install-AWSToolsModule AWS.Tools.SSO -CleanUp -Force 
Install-AWSToolsModule AWS.Tools.SSOOIDC -CleanUp -Force 
Install-AWSToolsModule AWS.Tools.CodeArtifact -CleanUp -Force 
Import-Module -Name AWS.Tools.SSO, AWS.Tools.SSOOIDC
Get-CAAuthorizationToken -Region us-east-1 -Domain "xxxxx" -DomainOwner "xxxxx" -Select "AuthorizationToken"
```

Giving following error 
```
Get-CAAuthorizationToken: Value cannot be null. (Parameter 'Options property cannot be empty: ClientName')
```

### Reproduction Steps

Checking with version 4.1.164 is success 

```
Install-Module -Name AWS.Tools.Installer -Force -MaximumVersion 1.0.2.4
Install-AWSToolsModule AWS.Tools.SSO -CleanUp -Force -MaximumVersion 4.1.164
Install-AWSToolsModule AWS.Tools.SSOOIDC -CleanUp -Force -MaximumVersion 4.1.164
Install-AWSToolsModule AWS.Tools.CodeArtifact -CleanUp -Force -MaximumVersion 4.1.164
Import-Module -Name AWS.Tools.SSO, AWS.Tools.SSOOIDC

Get-CAAuthorizationToken -Region us-east-1 -Domain "xxxxx" -DomainOwner "xxxxx" -Select "AuthorizationToken"
```

Checking with latest is Failed
```
Install-Module -Name AWS.Tools.Installer -Force -MaximumVersion 1.0.2.4
Install-AWSToolsModule AWS.Tools.SSO -CleanUp -Force 
Install-AWSToolsModule AWS.Tools.SSOOIDC -CleanUp -Force 
Install-AWSToolsModule AWS.Tools.CodeArtifact -CleanUp -Force 
Import-Module -Name AWS.Tools.SSO, AWS.Tools.SSOOIDC

Get-CAAuthorizationToken -Region us-east-1 -Domain "xxxxx" -DomainOwner "xxxxx" -Select "AuthorizationToken"
```

### AWS Tools for PowerShell version used

AWS.Tools.Installer  1.0.2.4
AWS.Tools.SSO -CleanUp -Force -MaximumVersion 4.1.164  vs latest
AWS.Tools.SSOOIDC -CleanUp -Force -MaximumVersion 4.1.164 vs latest
AWS.Tools.CodeArtifact -CleanUp -Force -MaximumVersion 4.1.164 vs latest

### PowerShell version used

Name                           Value
----                           -----
PSVersion                      7.0.12
PSEdition                      Core
GitCommitId                    7.0.12
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Operating System and version

Windows 10</div>

**Comment by ashishdhingra** [comment]
Please refer discussion https://github.com/aws/aws-tools-for-powershell/discussions/296 for more details. Looks like customer is doing SSO login from the host machine and then mounting the credentials folder in docker.

**Comment by ashishdhingra** [comment]
Similar issue in .NET SDK https://github.com/aws/aws-sdk-net/issues/2477.

**Comment by CamileDahdah** [comment]
Closing ticket since a fix has been [pushed](https://github.com/aws/aws-sdk-net/commit/6c689283c6e8b299ff6923908e24521fdde8d3c6).

Thank you.
