### ISSUE TITLE
A seperate support tool to Uninstall each version on Windows, Linux, and on Macos

### ISSUE THREAD

**Issue by milldogtjm** [aws/aws-tools-for-powershell#317]
### Describe the feature

I need a tool to uninstall each version on a system totally. 

### Use Case

Cause I'm a noob when it comes to using cdmlets in powershell and or using the windows comand-line tools or commands.
So I'm asking on if a gui guided support program could be made to uninstall all versions of your tool on a supported OS that the tool is installed to.

### Proposed Solution

Don't know of one so thats why I'm asking for this.

### Other Information

Just found the AWSToolkit folder in my local user data folder on my Windows computer without ever installing any of your software before. This is very suspicious to me as I don't really use powershell that munch on my computer so I could have unforseen infection which I to inspect and get rid of but in the mean time a tool that check to see if a product version is installed on a system and if so then start the uninstall procedure to delete the product and its related reg entries  

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

This support tool would used for all versions.

### PowerShell version used

This support tool would used for all versions.

### Operating System and version

Windows 10 x64, Windows 11 x64, OSX, different Linux versions

**Comment by ashishdhingra** [comment]
@milldogtjm Thanks for submitting the feature request. Just for your reference, the `AWS.Tools.Installer` module supports the following CmdLets what could be useful for your use case:
- `Install-AWSToolsModule` by default also updates all currently installed `AWS.Tools` modules. It also supports `-Cleanup` parameter which would ensure that after a successful install, all other versions of the AWS Tools modules should be uninstalled. This provides an indirect way to uninstall old versions.
- `Update-AWSToolsModule -CleanUp` also exhibits the same behvious.
- `Uninstall-AWSToolsModule` uninstalls all currently installed `AWS.Tools` modules.

You could try using `Uninstall-AWSToolsModule` to uninstall all `AWS.Tools` modules. Please let me know if it doesn't work.

Thanks,
Ashish

**Comment by milldogtjm** [comment]
Thanks will try that out.
