### ISSUE TITLE
Write-S3Object is failing on S3 compatible bucket

### ISSUE THREAD

**Issue by p0macs** [aws/aws-tools-for-powershell#320]
### Describe the bug

Hi @ashishdhingra 

I found this conversation about Write-S3Object failing on S3 compatible bucket: #165 
I have similar issue, but with different error code.

My S3 compatible bucket is hosted on Oracle Cloud, in eu-frankfurt-1 region.
I'm using the EndpointUrl, AccessKey and SecretKey parameters to access my bucket.
Everything works fine, I can use Get-S3Object to get the list of objects store in the bucket and Copy-S3Object to copy an object from S3 into the local filesystem.

When I want to use Write-S3Object to write a local file (-File), or multiple files (-Folder) or a non-empty content (-Content), I get an error message: Http Status Code BadRequest

When I use the aws cli command using the same parameters, the object is written to the bucket without issues.
`aws s3api put-object `

Similarly, using 3rd party tools (like S3 Browser) I can write to the bucket using the same credentials. 
 

### Expected Behavior

The file is written to the target bucket.

### Current Behavior

Write-S3Object: Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service.

`Exception             : 
    Type           : Amazon.S3.AmazonS3Exception
    Message        : Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the 
service.
    ErrorCode      : BadRequest
    RequestId      : fra-1:0op9MzbexiHFc_aZ-paCJmq-zKY_bNPwrQCE5XRuCFQClnn6B33rN4hxBfZJVmnk
    StatusCode     : BadRequest
    TargetSite     : 
        Name          : Run
        DeclaringType : Amazon.PowerShell.Utils.ProgressRunner
        MemberType    : Method
        Module        : AWS.Tools.Common.dll
    InnerException : 
        Type       : Amazon.Runtime.Internal.HttpErrorResponseException
        Response   : Amazon.Runtime.Internal.Transform.HttpClientResponseData
        TargetSite : 
            Name          : MoveNext
            DeclaringType : Amazon.Runtime.HttpWebRequestMessage+<GetResponseAsync>d__20, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, 
PublicKeyToken=885c28607f98e604
            MemberType    : Method
            Module        : AWSSDK.Core.dll
        Message    : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
        Source     : AWSSDK.Core
        HResult    : -2146233088
        StackTrace : 
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
    Source         : AWS.Tools.Common
    HResult        : -2146233088
    StackTrace     : 
   at Amazon.PowerShell.Utils.ProgressRunner.Run(Action action, ProgressTracker tracker)
   at Amazon.PowerShell.Utils.ProgressRunner.SafeRun(Action action, ProgressTracker tracker, CmdletOutput output)
   at Amazon.PowerShell.Utils.ProgressRunner.SafeRun(Action action, ProgressTracker tracker)
   at Amazon.PowerShell.Cmdlets.S3.WriteS3ObjectCmdlet.UploadFileToS3(ExecutorContext context)
   at Amazon.PowerShell.Cmdlets.S3.WriteS3ObjectCmdlet.Execute(ExecutorContext context)
   at Amazon.PowerShell.Cmdlets.S3.WriteS3ObjectCmdlet.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord() in /builddir/build/BUILD/PowerShell-7.2.1/src/System.Management.Automation/engine/cmdlet.cs:line 
173
   at System.Management.Automation.CommandProcessor.ProcessRecord() in 
/builddir/build/BUILD/PowerShell-7.2.1/src/System.Management.Automation/engine/CommandProcessor.cs:line 387
CategoryInfo          : NotSpecified: (:) [Write-S3Object], AmazonS3Exception
FullyQualifiedErrorId : Amazon.S3.AmazonS3Exception,Amazon.PowerShell.Cmdlets.S3.WriteS3ObjectCmdlet
InvocationInfo        : 
    MyCommand        : Write-S3Object
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 22
    Line             : Write-S3Object -EndpointUrl $EndPointUrl -AccessKey $AccessKey -SecretKey $SecretKey -BucketName $BucketName -Key testfile.txt -File 
testfile.txt
    PositionMessage  : At line:1 char:1
                       + Write-S3Object -EndpointUrl $EndPointUrl -AccessKey $AccessKey -Secre …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Write-S3Object
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1`

### Reproduction Steps

Write-S3Object -EndpointUrl $EndPointUrl -AccessKey $AccessKey -SecretKey $SecretKey -BucketName $BucketName -Key testfile.txt -File testfile.txt

### Additional Information/Context

When I use the aws cli command using the same parameters, the object is written to the bucket without issues.
`aws s3api put-object `

Similarly, using 3rd party tools (like S3 Browser) I can write to the bucket using the same credentials. 

### AWS Tools for PowerShell version used

I'm using the AWS Tools for PowerShell, Version 4.1.320

### PowerShell version used

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 4.14.35-2047.524.5.el7uek.x86_64 #2 SMP Wed Mar 29 15:42:02 PDT 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

The same error happans with newer PS version as well, like 7.3.4

### Operating System and version

Ubuntu, Windows, GNU/Linux

**Comment by p0macs** [comment]
Additional information.
Using Fiddler, I found a more detailed error message returned by the S3 endpoint:
`<?xml version="1.0" encoding="UTF-8"?><Error><Message>STREAMING-AWS4-HMAC-SHA256-PAYLOAD is not supported.</Message><Code>InvalidRequest</Code></Error>`

This was the request header:
`User-Agent: AWSPowerShell.Common/4.1.320.0 .NET_Core/7.0.5 OS/Microsoft_Windows_10.0.22624 PowerShellCore/7.-1 ClientAsync
amz-sdk-invocation-id: ea9301f4-25eb-4826-837f-2b0638ab5a41
amz-sdk-request: attempt=1; max=5
Host: frydrbw50foi.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
X-Amz-Date: 20230426T152511Z
X-Amz-Decoded-Content-Length: 12
X-Amz-Content-SHA256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
Authorization: AWS4-HMAC-SHA256 Credential=36c6d12c34106c26707408ed2afaa12d2c2869c4/20230426/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=9247ff6b296aac7a2e18e5f9dde7c0352166bb402c3afdd8dff8d470e10f3e39
Content-Length: 184
Content-Type: text/plain`

**Comment by ashishdhingra** [comment]
Hi @p0macs,

Good morning.

As mentioned in similar tickets, although for most of the cases, AWS SDK for .NET (including PowerShell tools) might work fine with 3rd party S3 like compatible services, there might be some cases it might not work. Unfortunately, we do not support troubleshooting issues with 3rd party services.

I will try to provide some guidance wherever I could. Could you please share the following:
- What is the size of object you are uploading?
- What does your EndpointUrl looks like?
- Are you getting similar issue when:
  - Using .NET code (developed using AWS SDK for .NET) directly, rather than using PowerShell CmdLet?
  - Using AWS S3 bucket?
- Could you try using the `-ClientConfig` parameter and explicitly specifying the `SignatureVersion` as `SigV4` (refer [Using the ClientConfig parameter in cmdlets](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-clientconfig.html))

Thanks,
Ashish

**Comment by p0macs** [comment]
Hi @ashishdhingra 
Thank you for your reply.
I made some more research (as you can see my comments above) - and unfortunately the S3 compatibility of the Oracle Cloud Buckets is limited, it does not supports all the x-amz-content-sha256 values used by AWS Signature V4.

One of the error message captured by Fiddler shows this:

**x-amz-content-sha256 must be UNSIGNED-PAYLOAD or a valid sha256 value.**

So it looks like I cannot use this bucket with the S3 Powershell modules (unless there is a hidden way to use an unsigned payload option)

I guess you can close this issue - as the error is resulting from the limitation of the 3rd party service.

**Comment by ashovlin** [comment]
We do offer an `DisablePayloadSigning` parameter on the underlying .NET SDK [PutObjectRequest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TPutObjectRequest.html) object. We don't expose it in AWS Tools for PowerShell currently, but could explore adding it as a feature request.

**Comment by p0macs** [comment]
As far as I can see, the `DisablePayloadSigning` is available for [PutObjectRequest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TPutObjectRequest.html) and for [TransferUtilityUploadRequest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TTransferUtilityUploadRequest.html) as well, but not for [TransferUtilityUploadDirectoryRequest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TTransferUtilityUploadDirectoryRequest.html) - which is used when starting Write-S3Object with the `-Folder` parameter.

**Comment by Blacknight1260** [comment]
We are yet g to open this , if someone can help would be great I am Bob
Wilson and I did not make these accounts I never heard of GitHub” until
this cloud thing happened we’d like ti know what this is about since I’m
being charged on Amazon ?!

**Comment by kellertk** [comment]
Hi @Blacknight1260, please contact [AWS Billing/Account support](https://aws.amazon.com/contact-us/) for these questions. We do not have the ability to look at your AWS account usage on GitHub.

**Comment by Blacknight1260** [comment]
I have no idea what all this is computer was hacked please delete or take
me off lists!
