### ISSUE TITLE
The AWS.Tools.Installer command Install-AWSToolsModule description is incorrect.

### ISSUE THREAD

**Issue by KaylorDave** [aws/aws-tools-for-powershell#322]
### Describe the issue

Right now the `AWS.Tools.Installer` module command's `Install-AWSToolsModule` description shows:

> This cmdlet uses Install-Module to install AWS.Tools modules. Unless -SkipUpdate is specified, this cmdlet also updates all other currently installed AWS.Tools modules to the version being installed.

This is incorrect. On inspection of the code, there are no references to Install-Module, it appears that was removed in a previous update.

### Links

https://docs.aws.amazon.com/powershell/latest/reference/items/Install-AWSToolsModule.html

**Comment by ashishdhingra** [comment]
@KaylorDave Upon insvestigation of the `Install-AWSToolsModule` code, it does call [Install-Module](https://github.com/aws/aws-tools-for-powershell/blob/813f03aeefdfcde5d31f80db708a18c17775cbff/modules/Installer/AWS.Tools.Installer.psm1#LL649C43-L649C50) to install the PowerShell modules.

Thanks,
Ashish
