### ISSUE TITLE
Pipe Output from Get-AWSService to Install-AWSToolsModule for ease of use

### ISSUE THREAD

**Issue by ccharland** [aws/aws-tools-for-powershell#325]
### Describe the feature

I want to pipe the output from Get-AWSService directly to Install-AWSToolsModule

As of version 4.1.350, this is the output:

```
PS C:\Program Files\PowerShell\Modules> Get-AWSService -Service EFS | Install-AWSToolsModule -Scope AllUsers
Exception: The Name parameter must contain only AWS.Tools modules.`
```
Converting the output from Get-AWSService is ugly but works. 
```
PS C:\Program Files\PowerShell\Modules> Get-AWSService -Service EFS |Select-Object @{Name="Name";Expression={$_.ModuleName}} |Install-AWSToolsModule -Scope AllUsers

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-AWSToolsModule" on target "AWS Tools version 4.1.350.0".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
Installing module AWS.Tools.ElasticFileSystem version 4.1.350.0
PS C:\Program Files\PowerShell\Modules>
```

### Use Case

I discovered the Get-AWSService cmdlet when I reviewed [this page](https://docs.aws.amazon.com/powershell/latest/userguide/v4migration.html)

It's logical that you should be able to pipe the output of Get-AWSService to Install-AWSToolsModule or Install-Module, given the description on the page.

### Proposed Solution

Change the output of Get-AWSService from a PsCustomObject to a named object type, such as used by other AWS PowerShell modules.  

```
PS C:\Program Files\PowerShell\Modules> (Get-AWSService)[0].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object

PS C:\Program Files\PowerShell\Modules> (Get-S3Bucket)[0].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    S3Bucket                                 System.Object

```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

```
ModuleType Version    PreRelease Name   
---------- -------    ---------- ----                
Binary     4.1.350               AWS.Tools.Common
Script     1.0.2.4               AWS.Tools.Installer    
```

### PowerShell version used

```
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Operating System and version

Windows Server 2019 (AWS Workspace)

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by afroz429** [comment]
Thanks for creating the feature request. The latest version of AWS.Tools.Installer module (1.0.2.5) supports installing tools modules by piping the output of `Get-AWSService` to  `Install-AWSToolsModule`. e.g `Get-AWSService -Service EFS | Install-AWSToolsModule`
