### ISSUE TITLE
Using aws cmdlets with s3 compatible storage has a 15 second delay before communicating with the endpointurl

### ISSUE THREAD

**Issue by nocentino** [aws/aws-tools-for-powershell#330]
### Describe the bug

Using `Get-S3Object` (or any s3 cmdlet) in conjunction with the `-endpointurl` parameter the cmdlet attempts to retrieve instance metadata. Since this execution is not on an EC2 instance there is a delay which the attempt to get instance metadata times out. This is approximately 15 seconds. Once it times out the connection to s3 compatible storage works fine. If you specify a -Region parameter with any value the cmdlet works properly, in a timely fashion.

### Expected Behavior

When using the `-endpointurl` parameter I would expect the ability to disable the instance metadata check.

### Current Behavior

There is a 15 second delay due to connection retry attempts on retrieving instance metadata

### Reproduction Steps

`Get-S3Object -BucketName sql-dumps -SecretKey $SecretKey -AccessKey $AccessKey -endpointurl https://PRIVATEENDPOINTURL `

### Possible Solution

Allow a `-Region` parameter value of `None` to be set to bypass the instance metadata check

### AWS Tools for PowerShell version used

AWSPowerShell 4.1.348

### PowerShell version used

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.4467
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.4467
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Operating System and version

Windows 2016 Server

**Comment by ashishdhingra** [comment]
Hi @nocentino,

Good morning. Thanks for reporting the issue. Just FYI, we do not support troubleshooting issues when AWS .NET SDK or PowerShell tools is used with 3rd party AWS like services.

In AWS, all S3 operations require credentials, hence .NET SDK (or any other SDK) would use order mentioned in [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) to resolve credentials. In your case, since you are explicitly passing the credentials, it should have resolved the same resolved it at first step.

In the proposed solution you mentioned to allow `-Region` parameter value of `None` to be set to bypass the instance metadata check. Is it the region resolution or credential resolution that is causing delay?

Could you please try following steps in [Response Logging in AWS Tools for Windows PowerShell](https://aws.amazon.com/blogs/developer/response-logging-in-aws-tools-for-windows-powershell/) to get the detailed logs and share these for investigation?

You may also try is explicitly `EndpointDiscoveryEnabled` on `AmazonS3Config` object helps mitigate the issue (follow instructions in [Using the ClientConfig parameter in cmdlets](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-clientconfig.html)).

```PowerShell
$s3Config = New-Object -TypeName Amazon.S3.AmazonS3Config
$s3Config.EndpointDiscoveryEnabled = $false
Get-S3Object -BucketName <BUCKET_NAME> -SecretKey $SecretKey -AccessKey $AccessKey -ClientConfig $s3Config
```

Thanks,
Ashish

**Comment by nocentino** [comment]
Hi Ashish, 
  Thank you for the assistance here.  This is also happening when I point to an actual AWS S3 Bucket from a non-EC2 PowerShell client.
  
Here's what I'm seeing when I enable logging. 
  
 ```
Amazon Information: 0 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].
Amazon Verbose: 0 : Single encoded /aen-sql-dumps/ with endpoint https://MYENDPOINT / for canonicalization: /BUCKNETNAME/
Amazon Error: 0 : Unable to contact EC2 Metadata service to obtain a metadata token. Attempting to access IMDS without a token., System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
   at Amazon.Util.EC2InstanceMetadata.FetchApiToken(Int32 tries)
Amazon Error: 1 : Unable to contact EC2 Metadata service., System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
Amazon Information: 1 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].
```

When I try using the `Amazon.S3.AmazonS3Config` config you recommend above here's the error that goes into the log 

```
Amazon Verbose: 1 : Single encoded /aen-sql-dumps/ with endpoint https:/// for canonicalization: /BUCKETNAME/
Amazon Error: 2 : Unable to contact EC2 Metadata service., System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
Amazon Error: 3 : Unable to contact EC2 Metadata service., System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
Amazon Information: 2 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].
Amazon Verbose: 2 : Single encoded /aen-sql-dumps/ with endpoint https://sn1-fb-c07-23-data-vip1.fsa.lab/aen-sql-dumps/ for canonicalization: /aen-sql-dumps/
```

Thank you,
    Anthony

**Comment by ashishdhingra** [comment]
> Hi Ashish, Thank you for the assistance here. This is also happening when I point to an actual AWS S3 Bucket from a non-EC2 PowerShell client.
> 
> Here's what I'm seeing when I enable logging.
> 
> ```
> Amazon Information: 0 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].
> Amazon Verbose: 0 : Single encoded /aen-sql-dumps/ with endpoint https://MYENDPOINT / for canonicalization: /BUCKNETNAME/
> Amazon Error: 0 : Unable to contact EC2 Metadata service to obtain a metadata token. Attempting to access IMDS without a token., System.Net.WebException: The operation has timed out
>   at System.Net.HttpWebRequest.GetResponse()
>   at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
>   at Amazon.Util.EC2InstanceMetadata.FetchApiToken(Int32 tries)
> Amazon Error: 1 : Unable to contact EC2 Metadata service., System.Net.WebException: The operation has timed out
>   at System.Net.HttpWebRequest.GetResponse()
>   at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
>   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
> ```
> 
> When I try using the `Amazon.S3.AmazonS3Config` config you recommend above here's the error that goes into the log
> 
> ```
> Amazon Information: 1 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].
> Amazon Verbose: 1 : Single encoded /BUCKETNAME/ with endpoint https://MYENDPOINT/ for canonicalization: /BUCKETNAME/
> Amazon Error: 2 : Unable to contact EC2 Metadata service., System.Net.WebException: The operation has timed out
>    at System.Net.HttpWebRequest.GetResponse()
>    at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
>    at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
> Amazon Error: 3 : Unable to contact EC2 Metadata service., System.Net.WebException: The operation has timed out
>    at System.Net.HttpWebRequest.GetResponse()
>    at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
>    at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
> Amazon Information: 2 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].
> Amazon Verbose: 2 : Single encoded /BUCKETNAME/ with endpoint https://MYENDPOINT/ for canonicalization: /BUCKETNAME/
> ```
> 
> Thank you, Anthony

@nocentino Thanks for your reply. For accessing AWS S3 bucket on a non-EC2 instance, how are the credentials configured. AWS SDK for .NET uses the credential resolution order mentioned in [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) (notice that the last one is EC2 instance metadata). Looking at your log, it looks like credentials are not successfully resolved, since it's querying EC2 instance metadata, it was unable to resolve credentials via other providers earlier.

Thanks,
Ashish

**Comment by jgard** [comment]
@nocentino (and anyone else who runs into this):
I had a similar issue where using `-ProfileName` in various cmdlets (including `Get-STSCallerIdentity`) resulted in the observed 15 second delay (even though the logging indicates a 5 second timeout):
```
Amazon Information: 0 : Resolved DefaultConfigurationMode for RegionEndpoint [us-east-2] to [Legacy].
Amazon Error: 0 : Unable to contact EC2 Metadata service., System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
```
I had used `Set-DefaultAWSRegion` to my local region (us-east-2), and had `$env:aws_sts_REGIONAL_ENDPOINTS = 'regional'`.
However setting `$env:AWS_REGION` made my problem go away entirely.
