### ISSUE TITLE
Add support for IAM Identity Center (SSO) authentication

### ISSUE THREAD

**Issue by dbaileyut** [aws/aws-tools-for-powershell#332]
### Describe the feature

Implement native PowerShell features to bring feature parity from the AWS command line tools around IAM Identity Center (SSO) authentication/profiles to AWS.Tools PowerShell modules.

### Use Case

I'm frustrated by having to copy and paste IAM Identity Center (SSO) credentials or having to use 3rd party scripts to update after SSO tokens expire.

### Proposed Solution

- I should be able to do the equivalent of `aws configure sso` in PowerShell without requiring the AWS command line tools
- I should be able to do the equivalent of `aws sso login` in PowerShell without requiring the AWS command line tools
- All AWS PowerShell cmdlets should be aware of "sso" profile configurations and should be able to refresh tokens in as user friendly a way as the command line tools

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS Tools for PowerShell version used

4.1.396

### PowerShell version used

PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Needs review with the team.

@dbaileyut Are you looking for something like `Get-SSOLogin` since AWS CLI also needs to manually execute `aws sso login` for next steps to be completed in web browser?

Thanks,
Ashish

**Comment by dbaileyut** [comment]
Maybe `Connect-AWSSSO` would align with PowerShell conventions better?
It's fine (and expected) to complete steps in a browser, I just want PowerShell to have the same experience the command line tools have with respect to SSO token refresh and configuration.

I.e., implement this experience in PowerShell: https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html

**Comment by afroz429** [comment]
Happy to announce that the following new cmdlets were added starting from version 4.1.538 of `AWS.Tools.Common` module. Thanks for the feature request.

`Initialize-AWSSSOConfiguration` similar to `aws configure sso`
`Invoke-AWSSSOLogin` similar to `aws sso login`
`Invoke-AWSSSOLogout` similar to `aws sso logout`
`Set-AWSSSOSessionConfiguration` similar to `aws configure sso-session`

User guide: https://docs.aws.amazon.com/powershell/latest/userguide/creds-idc.html
