### ISSUE TITLE
Cmdlet to invoke arbitrary API action

### ISSUE THREAD

**Issue by dbaileyut** [aws/aws-tools-for-powershell#347]
### Describe the feature

A cmdlet that allows invoking arbitrary AWS API action and handles authentication, signing etc.

### Use Case

I'm frustrated when certain APIs calls are not available as their own cmdlet yet. Or, I want to do something lower level. For example, Find-IDSUserList cmdlet's -Filter parameter is deprecated and we are told to use GetUserId. However, as far as I can tell there's no cmdlet for that.

### Proposed Solution

Something like "Invoke-AWSApiAction" which would be similar to [Invoke-AzRestMethod](https://learn.microsoft.com/en-us/powershell/module/az.accounts/invoke-azrestmethod?view=azps-11.5.0) or Invoke-RestMethod with all the authentication and standard AWS parameters provided.

Parameters would be something like
*  `ApiAction` where I could specify something like "GetUserId"
* `RequestParameter` - a hash table of the request parameters that would get converted to JSON in the API call
* Profile, Region, etc. - all the standard parameters

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

AWS.Tools.Common 4.1.539

### PowerShell version used

```
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Unsure if implementing arbitrary API action CmdLet would be feasible since service APIs have varying model definitions. Needs review with the team.

**Comment by ashishdhingra** [comment]
Closing this since we have the required Identity Store CmdLets as mentioned in https://github.com/aws/aws-tools-for-powershell/issues/349 and https://github.com/aws/aws-tools-for-powershell/issues/348. We are generating CmdLets for all service APIs.
