### ISSUE TITLE
Implement Cmdlet for GetUserId

### ISSUE THREAD

**Issue by dbaileyut** [aws/aws-tools-for-powershell#348]
### Describe the feature

Find-IDSUserList's -Filter parameter is deprecated. There needs to be a non-deprecated way to search for a user efficiently.

### Use Case

I need to find users by display name or email address efficiently.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

AWS.Tools.IdentityStore 4.1.539

### PowerShell version used

```

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
@dbaileyut Per [IdentityStore: ListUsers](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListUsers.html), Filtering for a `User` by the `UserName` attribute is deprecated. Instead, use the `GetUserId` API action. Most of the CmdLets for AWS Tools for PowerShell are auto-generated. For GetUserId` API action, the corresponding CmdLet is [Get-IDSUserId](https://docs.aws.amazon.com/powershell/latest/reference/items/Get-IDSUserId.html). Please advise if you have considered using it for your use case.

Thanks,
Ashish

**Comment by dbaileyut** [comment]
Ah, my mistake! I wasn't seeing that cmdlet
