### ISSUE TITLE
Implement GetGroupId cmdlet

### ISSUE THREAD

**Issue by dbaileyut** [aws/aws-tools-for-powershell#349]
### Describe the feature

Find-IDSGroupList's -Filter parameter is deprecated. There needs to be a non-deprecated way to get a group by its name (or other attributes) efficiently.

### Use Case

I need to search for groups by name or other attributes if possible efficiently rather than getting all of them and filtering locally.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Tools for PowerShell version used

AWS.Tools.IdentityStore 4.1.539

### PowerShell version used

```

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
@dbaileyut Per [IdentityStore: ListGroups](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListGroups.html), Filtering for a `Group` by the `DisplayName` attribute is deprecated. Instead, use the `GetGroupId API` action. Most of the CmdLets for AWS Tools for PowerShell are auto-generated. For `GetGroupId` API action, the corresponding CmdLet is [Get-IDSGroupId](https://docs.aws.amazon.com/powershell/latest/reference/items/Get-IDSGroupId.html). Please advise if you have considered using it for your use case.

Thanks,
Ashish

**Comment by dbaileyut** [comment]
My mistake, I wasn't seeing the cmdlet.
