### ISSUE TITLE
AWS.S3.Write-S3Object gives signature mismatch error on Ubuntu but works on Windows

### ISSUE THREAD

**Issue by gr8tushar** [aws/aws-tools-for-powershell#356]
### Describe the bug

I have a powershell script which uses Write-S3Object method. It works absolutely fine on Windows but gives an error on Ubuntu.
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### Expected Behavior

The Write-S3Object should work in both the enviroments

### Current Behavior

Works on Windows,
Doesn't work on Ubuntu

### Reproduction Steps

$S3AccessKeyID = "" #Your Amazon S3 Access Ky ID 
$S3SecretKeyID = "" #Your Amazon S3 Secret Access Key 
$S3BucketName = "" #S3 Bucket name where the file will be stored 
$AWSRegion = "ap-south-1"

Write-S3Object -BucketName $S3BucketPath -File $ZipFileName -Key (Get-Item $ZipFileName).Name -AccessKey $S3AccessKeyID -SecretKey $S3SecretKeyID -Region $AWSRegion

### AWS Tools for PowerShell version used

4.1.629              AWS.Tools.S3                    
4.1.629              AWS.Tools.Common

### PowerShell version used

7.4.4   

### Operating System and version

Ubuntu 22.04.4

**Comment by bhoradc** [comment]
Hello @gr8tushar, 

Thanks for reporting this issue. I tried replicating this issue in Ubuntu, but couldn't reproduce the error.

`Write-S3Object` execution for file upload works fine in both windows and Ubuntu. 

**EC2 environment details:**

* OS: Ubuntu 22.04.4 LTS
* Architecture: 64 bit (x86)
* .NET SDK: 8.0.107
* AWS.Tools.S3: 4.1.629
* AWS.Tools.Common: 4.1.629
* PSVersion: 7.4.4

```ps
PS /home/ubuntu> $S3AccessKeyID = "****" 
PS /home/ubuntu> $S3SecretKeyID = "****"
PS /home/ubuntu> $S3BucketName = "****"
PS /home/ubuntu> $AWSRegion = "us-east-1"
PS /home/ubuntu> $ZipFileName = ".\psubuntusample.txt"
PS /home/ubuntu> Write-S3Object -BucketName $S3BucketName -File $ZipFileName -Key (Get-Item $ZipFileName).Name -AccessKey $S3AccessKeyID -SecretKey $S3SecretKeyID -Region $AWSRegion
```
Above execution successfully uploaded the file to S3. 

Can you please confirm if the AWS credentials are valid and been retrieved correctly in this case (on Ubuntu)? 

You can enable logging to see if it helps in identifying the issue. PowerShell logging can be enabled with below commands.

```ps
Add-AWSLoggingListener -Name "AWS Logs" -LogFilePath "/ps-logs.txt" # or any path
Set-AWSResponseLogging Always
Enable-AWSMetricsLogging
```

If you find any concerns in the logs, kindly share it with us for further review(after redacting sensitive information). 

Regards, 
Chaitanya

**Comment by gr8tushar** [comment]
@bhoradc Let me give it a try. If it doesn't work, I'll paste my code here
