### ISSUE TITLE
Unable to set credentials: Root element is missing.

### ISSUE THREAD

**Issue by KezHalls** [aws/aws-tools-for-powershell#360]
### Describe the bug

 Unable to set credentials: Root element is missing.  I get this error when I try to create a connection to AWS.
The account I am using is MFA exempted and access to aws.    I had a job logged with AWS and they said I need to log it with you as they cannot find the issue. 

Followed all posts
    https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html
    https://docs.aws.amazon.com/powershell/latest/userguide/saml-pst.html
    https://repost.aws/knowledge-center/adfs-grant-ad-access-api-cli#

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

a successful connection to aws is made

### Current Behavior

h endpoint to verify role data...
Set-AWSSamlRoleProfile:
Line |
  11 |  Set-AWSSamlRoleProfile -EndpointName $epName -NetworkCredential $cred …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to set credentials: Root element is missing.

### Reproduction Steps

```
#$credential = New-Object System.Management.Automation.PSCredential($userName, (ConvertTo-SecureString $password -AsPlainText -Force))
$Credential = Get-Credential -Message "Enter the domain credentials for the endpoint"
$endpoint = "https://launcher.myapps.microsoft.com......d"
$epName = Set-AWSSamlEndpoint -Endpoint "$endpoint" -StoreAs 'ADFS-Login' -AuthenticationType NTLM
Set-AWSSamlRoleProfile -EndpointName $epName -NetworkCredential $credential -StoreAs SAMLDemoProfile -Verbose
```

### AWS Tools for PowerShell version used

AWS.Tools.EC2            3.7.403.1
AWS.Tools.SSO           3.7.400.5
AWS.Tools.SSOOIDC   3.7.400.5

### PowerShell version used

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core 
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Operating System and version

windows 10

**Comment by ashishdhingra** [comment]
@KezHalls Good afternoon. Could you please share the following:

- Complete steps you took for your scenario? Kindly refer below reference
  - [New Support for Federated Users in the AWS Tools for Windows PowerShell](https://aws.amazon.com/blogs/developer/new-support-for-federated-users-in-the-aws-tools-for-windows-powershell/)
  - [Configure federated identity with the AWS Tools for PowerShell](https://docs.aws.amazon.com/powershell/latest/userguide/saml-pst.html)
- Enable response logging using steps [Response Logging in AWS Tools for Windows PowerShell](https://aws.amazon.com/blogs/developer/response-logging-in-aws-tools-for-windows-powershell/) and share the detailed logs.
- Try to execute `Set-AWSSamlRoleProfile` with `-Verbose` parameter and share the output along with error.

Just for reference, [Set-AWSSamlRoleProfile](https://github.com/aws/aws-tools-for-powershell/blob/8a4d1852dae440f07672eae9e6b565882cd29228/modules/AWSPowerShell/Common/CredentialsCmdlet.cs#L510) CmdLet uses `SAMLAuthenticationController` [here](https://github.com/aws/aws-tools-for-powershell/blob/8a4d1852dae440f07672eae9e6b565882cd29228/modules/AWSPowerShell/Common/CredentialsCmdlet.cs#L641). [SAMLAuthenticationController.GetSAMLAssertion()](https://github.com/aws/aws-sdk-net/blob/694f26cbfb0928f09b4677fcd65e543738871ef9/sdk/src/Services/SecurityToken/Custom/SAML/SAMLAuthenticationController.cs#L187) tries to parse response [here](https://github.com/aws/aws-sdk-net/blob/694f26cbfb0928f09b4677fcd65e543738871ef9/sdk/src/Services/SecurityToken/Custom/SAML/SAMLAuthenticationController.cs#L197).

Thanks,
Ashish

**Comment by KezHalls** [comment]
Thankyou for such a thorough response.  I think I see what you are saying in terms where the failure maybe occurring.

Unfortunately the response logging is not working... or at least not creating the log file so I am unable to share anything and am having troubleshooting that.

**Comment by KezHalls** [comment]
I wondered if there is anymore feedback on this.  After conversations with MS this method will be the only way we will be able to achieve our goal.

**Comment by ashishdhingra** [comment]
> Thankyou for such a thorough response. I think I see what you are saying in terms where the failure maybe occurring.
>
> Unfortunately the response logging is not working... or at least not creating the log file so I am unable to share anything and am having troubleshooting that.

@KezHalls I'm unsure if you are `-Source` parameter for `Add-AWSLoggingListener MyAWSLogs C:\logsaws.txt`. Also note that `c:\logsaws.txt` is path to log file and it should be writable. This could be any path.

So at high level, we would use below commands:
```PowerShell
Add-AWSLoggingListener MyAWSLogs C:\logsaws.txt
Set-AWSResponseLogging Always
Enable-AWSMetricsLogging
```

Once the logs are collected, we could turn off response logging:
```PowerShell
Disable-AWSMetricsLogging
Remove-AWSLoggingListener Amazon MyAWSLog
```

Thanks,
Ashish

**Comment by KezHalls** [comment]
Apparently we use the AWS SSO service to handle the role mapping. We don't pass on the role mapping within the SAML assertion which is why this is not working and I won't be able to get it working.  Back to the drawing board.
Thanks for the assistance.

**Comment by KezHalls** [comment]
closing
