### ISSUE TITLE
Copy-S3Object | Recursivly copying S3-objects to same bucket?

### ISSUE THREAD

**Issue by CloudViking86** [aws/aws-tools-for-powershell#40]
Looking for being able to do the exact same thing as the awscli aws s3 cp command does namely recursivley copying files from one bucket to another (or the same destination bucket) i.e.;
`aws s3 cp s3://mybucket/ s3://mybucket2/ --recursive`
or
`aws s3 cp s3://mybucket/somefolder/ s3://mybucket/somefolder-bak/ --recursive`

"Write-S3Object" has a "recurse"-switch;
https://docs.aws.amazon.com/powershell/latest/reference/index.html?page=Write-S3Object.html&tocid=Write-S3Object
which if implemented also here would accomplish the same thing.

**Expected Behavior**

When looking at:
https://docs.aws.amazon.com/powershell/latest/reference/index.html?page=Copy-S3Object.html&tocid=Copy-S3Object
under
"CopyS3ObjectToS3Object" there is no "recursive"-parameter or flag available.

**Current Behavior**

Only seems to be able to accomplish this by iterating through the files with a foreach-loop while it should be easier (as it is with aws cli and its "recursive"-flag / parameter.

**Comment by matteo-prosperi** [comment]
Marking as feature request
