### ISSUE TITLE
Cmdlets do not honor proxy environment variables

### ISSUE THREAD

**Issue by jakauppila** [aws/aws-tools-for-powershell#44]
When using the various cmdlets contained within the module, I cannot simply utilize my HTTP/HTTPS-NO_PROXY environment variables for the HTTP calls that commands are doing.

**Expected Behavior**

Module cmdlets should respect HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables of my system

**Current Behavior**

I must explicitly set the proxy via `Set-AWSProxy` passing in those values from the environment variables.

**Context**

When we utilize the module within some of our Jenkins pipelines it would be easier if we could specify the proxy configurations at the very top level and just let it propagate down to all of our HTTP calls whether they be Groovy, raw Powershell calls, or Powershell SDK module calls.

**Comment by matteo-prosperi** [comment]
Thanks for reporting this.
Marking as feature request with backward compatibility concerns.

**Comment by jakauppila** [comment]
As a potential workaround to the backwards incompatibility, could an environment variable be utilized to effectively opt-in to the behavior?

`AWS_INHERIT_SYSTEM_PROXY`

**Comment by jakauppila** [comment]
This would still be useful

**Comment by jakauppila** [comment]
This would still be useful

**Comment by ashishdhingra** [comment]
Similar issue for AWS SDK for .NET: https://github.com/aws/aws-sdk-net/issues/1977

**Comment by dscpinheiro** [comment]
Today's release of PowerShell (`4.1.488`) uses the AWS .NET SDK 3.7.720.0, where support for the `http_proxy` and `https_proxy` environment variables was added: https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2024.md#377200-2024-01-04-1956-utc

Note that proxies set via `Set-AWSProxy` will still take precedence (for backwards compatibility).
