### ISSUE TITLE
AWS Prefix, Prefix Consistency

### ISSUE THREAD

**Issue by tommymaynard** [aws/aws-tools-for-powershell#48]
**Expected Behavior**

Cmdlets that are not _specific_ to an AWS Service should _always_ use the AWS Prefix in their name, after the verb and dash, but before the singular noun, or CamelCase singular noun**s**.

**Current Behavior**

Three cmdlets have long been inconsistent with the AWS prefix, prefixed commands. These are:

* Clear-DefaultAWSRegion
* Get-DefaultAWSRegion
* Set-DefaultAWSRegion

**Possible Solution**

I recommend that the above *-DefaultAWSRegion Cmdlets be renamed, and aliases be created that resolve to the three renamed cmdlets. The aliases should use the previous cmdlet names.

| Alias | Cmdlet |
| ----- | ----- |
| Clear-DefaultAWSRegion | Clear-AWSDefaultRegion |
| Get-DefaultAWSRegion | Get-AWSDefaultRegion   |
| Set-DefaultAWSRegion | Set-AWSDefaultRegion   |

**Steps to Reproduce (for bugs)**

```
$AWSToolsCommands = Get-Command -Module AWS.Tools.Common
Foreach ($Tool in $AWSToolsCommands) {
    If ($Tool.Name -notlike '*-AWS*') {
        (Get-Command -Name $Tool.Name).Name
    } # End If.
} # End Foreach.

Clear-DefaultAWSRegion
Get-DefaultAWSRegion
Set-DefaultAWSRegion
```
**Context**

As it stands now, there is a problem with command discovery due to the incorrect placement of this prefix.
```
PS > (Get-Command -Module AWS.Tools.Common | Measure-Object).Count
31
PS > (Get-Command -Name *-*AWS* -Module AWS.Tools.Common | Measure-Object).Count
31
PS > (Get-Command -Name *-AWS* -Module AWS.Tools.Common | Measure-Object).Count
28
```

**Your Environment**

* Affected module: AWS.Tools.Common
* Module version: 3.3.563.1
* Operating System and version: Microsoft Windows 10.0.18362
* PowerShell version: Core (6.2.2 and 7.0.0-preview.3) Desktop (5.1.18362.145)

**Comment by matteo-prosperi** [comment]
I agree with your point, we will look into this.
