### ISSUE TITLE
`PolicyArn` parameter should accept strings

### ISSUE THREAD

**Issue by jakauppila** [aws/aws-tools-for-powershell#50]
**Expected Behavior**

When I am assuming a role via `Use-STSRole` I want to pass a managed policy ARN to restrict its access. I want to be able to pass a string or array of strings of those ARNs.

```powershell
Use-STSRole -RoleArn "arn:aws:iam::${targetAccount}:role/$roleName" -RoleSessionName $roleSessionName -DurationInSeconds 900 -PolicyArn 'arn:aws:iam::aws:policy/job-function/ViewOnlyAccess'
```

**Current Behavior**

`PolicyArn` is required to be of type `PolicyDescriptorType[]` per the [documentation](https://docs.aws.amazon.com/powershell/latest/reference/items/Use-STSRole.html), which means I must do the following:

```powershell
$policy = New-Object -TypeName Amazon.SecurityToken.Model.PolicyDescriptorType
$policy.Arn = 'arn:aws:iam::aws:policy/job-function/ViewOnlyAccess'

$awsCreds = Use-STSRole -RoleArn "arn:aws:iam::${targetAccount}:role/$roleName" -RoleSessionName $roleSessionName -DurationInSeconds 900 -PolicyArn $policy
```

**Possible Solution**

Ideally, the cmdlet itself could do that conversion from `string` to `Amazon.SecurityToken.Model.PolicyDescriptorType` so I don't have to be responsible for that conversion which doesn't appear to do anything of value for me anyways (like validation, etc)

**Your Environment**

3.3.563.1  AWSPowerShell

**Comment by matteo-prosperi** [comment]
Hello,
thanks for reporting this.

You could simplify your code snippet down to
```
Use-STSRole -PolicyArn @{ Arn = 'arn:aws:iam::aws:policy/job-function/ViewOnlyAccess' } #other params
```

Would that be a reasonable solution?

The reason we are not simplifying this to be a string is that this specific input modeling is provided by the STS team. We could accept 
```
Use-STSRole -PolicyArn 'arn:aws:iam::aws:policy/job-function/ViewOnlyAccess'
```
based on the fact that `Amazon.SecurityToken.Model.PolicyDescriptorType` has a single property (`Arn`) but that will break if, in the future, the STS team decides to add other properties to `PolicyDescriptorType` (this actually happens frequently).

**Comment by ashishdhingra** [comment]
Hi @jakauppila,

Please let me know if the workaround provided by @matteo-prosperi  works for you and if we could close this issue.

Thanks,
Ashish
