### ISSUE TITLE
The file is empty. Empty files cannot be added to a repository.

### ISSUE THREAD

**Issue by jda2004** [aws/aws-tools-for-powershell#54]
Write-CCFile -RepositoryName test-repo -BranchName master -FilePath /test/tst.tst -ParentCommitId abc123test -ProfileName test-profile

Write-CCFile : The file is empty. Empty files cannot be added to a repository.

I am continuously getting this error message even though the file is not empty. The goal is to write a file in codecommit using this syntax.

**Comment by matteo-prosperi** [comment]
Hello,
I think you are missing the -FileContent parameter

**Comment by jda2004** [comment]
What do i put in -FileContent, the content of the file? I have a create table DDL in this file. Sould I just copy and paste that content within a single qoute?

**Comment by matteo-prosperi** [comment]
I think the simplest way to do this is
```
-FileContent [System.IO.File]::ReadAllBytes('path to my file')
```

`-FilePath` is the relative path to the file in the repository, not the path to a local file.

I am not familiar with these CodeCommit APIs but, if I read the docs correctly, this API will create one new commit for each file you add. In case you want to add multiple files in the same commit, `New-CCCommit` should do that.

**Comment by jda2004** [comment]
And............... it worked!!!.... thank you @matteo-prosperi You solved my 4 hours of digging in one shot!!!

**Comment by jda2004** [comment]
Hi @matteo-prosperi : I like to add little more information in my script. So this is the original syntax pattern from aws
Write-CCFile
-RepositoryName <String>
-BranchName <String>
-CommitMessage <String>
-Email <String>
-FileContent <Byte[]>
-FileMode <FileModeTypeEnum>
-FilePath <String>
-Name <String>
-ParentCommitId <String>
-Force <SwitchParameter>
 I was thinking what content to go in FileMode and how to use '-Force' to force commit? Is the '-Name' going to be the destination file name?

**Comment by matteo-prosperi** [comment]
Hi,
I can tell you that `-Force` is simply the PowerShell common parameter which will bypass the confirmation prompt of this cmdlet. `-Force` doesn't have any CodeCommit-specific use.

When it comes to the other parameters, have a look at the [reference docs here](https://docs.aws.amazon.com/powershell/latest/reference/index.html?page=Write-CCFile.html&tocid=Write-CCFile). `-Name` appears to be "the name of the person adding or updating the file". `-FileMode` is one of the values of the [FileModeTypeEnum](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=CodeCommit/TCodeCommitFileModeTypeEnum.html&tocid=Amazon_CodeCommit_FileModeTypeEnum) values (so you can do `-FileMode NORMAL`).

**Comment by jda2004** [comment]
One more :) @matteo-prosperi 
I am now thinking to put this syntax in an automation tool (WhereScape Red) template that will write the generated load script directly into the codecommit. In this case, I need to enable the FileContent 
to read a variable string. How to do that? For example:
-FileContent ([System.IO.File]::ReadAllBytes('$Loadsql'))

**Comment by matteo-prosperi** [comment]
I am not sure I understand whether you have the file name in a variable or the content of the file in a variable.
The former would be
```
-FileContent ([System.IO.File]::ReadAllBytes($FilePath))
```
the latter
```
-FileContent ([System.Text.Encoding]::UTF8.GetBytes($SomeText))
```

**Comment by jda2004** [comment]
Sorry for the confusion on the question, but you answered it with 'the latter' one. And it's working. Thanks for developing this one.
