### ISSUE TITLE
Allow increasing the part chunk size for S3 uploads.

### ISSUE THREAD

**Issue by matteo-prosperi** [aws/aws-tools-for-powershell#55]
AWS Tools for PowerShell doesn't allow to upload files larger than 50GB to S3. The default part chunk size is 5MB and multipart uploads are limited to 10,000 parts.

Add a way to increase the part chunk size.

**Comment by ashishdhingra** [comment]
Implemented in `AWS Tools for PowerShell 4.1.16.0`
