### ISSUE TITLE
Being able to change IAM-role for SG SMB-Share

### ISSUE THREAD

**Issue by CloudViking86** [aws/aws-tools-for-powershell#58]
Would like to be able to change the IAM-role for a SMB-share in Storage Gateway.
As of now (2019-10-28) there is no way through the console or CLI, the IAM-role is set on creation of the fileshare and you can't change it afterwards.

**Expected Behavior**

Being able to change the IAM-role set for a fileshare both in the console and using the CLI / PowerShell.

**Comment by matteo-prosperi** [comment]
Hello, thanks for reporting this issue.
If I understand this correctly, this would be a feature request for the Storage Gateway service, correct?

**Comment by ketanbhut** [comment]
This option is not there in API https://docs.aws.amazon.com/storagegateway/latest/APIReference/API_UpdateSMBFileShare.html - 
This would a feature request on the service/api itself

**Comment by CloudViking86** [comment]
Thank you for both of your replies.

Can you please link me to where I could put in a feature request for this?

**Comment by matteo-prosperi** [comment]
See https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/. You can either post on the forum or create a support case.
