### ISSUE TITLE
Kubeconfig file generation for EKS

### ISSUE THREAD

**Issue by costleya** [aws/aws-tools-for-powershell#62]
**Expected Behavior**

AWS Tools for Powershell should have a Cmdlet equivalent of https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html

**Current Behavior**

AWS Tools for Powershell currently does not support generation of a kubeconfig file for an EKS cluster.

**Context**
Some customers cannot use the CLI due to technical or policy limitations. With a PowerShell alternative not being available, these customers have to manually create these files to connect to their EKS clusters.

**Comment by prochnowc** [comment]
It's still missing and would be really helpfull.
/reopen
