### ISSUE TITLE
Incorrect cmdlet name returned by Get-AWSCmdletName

### ISSUE THREAD

**Issue by PowerSix** [aws/aws-tools-for-powershell#70]
Issue detected in AWS.Tools.Common 4.0.0.0.
Duplicated service tags are being returned in cmdlet names.

**Expected Behavior**

This is the output from AWSPowerShell module:
```
PS> Get-AWSCmdletName -ApiOperation describeinstances

CmdletName       ServiceOperation  ServiceName                  CmdletNounPrefix
----------       ----------------  -----------                  ----------------
Get-EC2Instance  DescribeInstances Amazon Elastic Compute Cloud EC2
Get-GMLInstance  DescribeInstances Amazon GameLift Service      GML
Get-OPSInstances DescribeInstances AWS OpsWorks                 OPS
```

**Current Behavior**

This is the output from AWS.Tools 4.0.0.0.
Cmdlet names have 'service initials' returned twice: Get-**EC2EC2**Instance, Get-**GMLGML**Instance...

```
PS> Get-AWSCmdletName -ApiOperation describeinstances

CmdletName         ServiceOperation  ServiceName                        ModuleName
----------         ----------------  -----------                        ----------
Get-EC2EC2Instance DescribeInstances Amazon Elastic Compute Cloud (EC2) AWS.Tools.EC2
Get-GMLGMLInstance DescribeInstances Amazon GameLift Service            AWS.Tools.GameLift
Get-OPSOP*Instance DescribeInstances AWS OpsWorks                       AWS.Tools.OpsWorks
```

**Your Environment**

* Affected module: AWS.Tools.Common
* Module version as reported by `Get-AWSPowerShellVersion`: 4.0.0.0
* Operating System and version as reported by `$PSVersionTable.OS`: Microsoft Windows 10.0.17763
* PowerShell version as reported by `$PSVersionTable.PSEdition`: Core

**Comment by matteo-prosperi** [comment]
Thanks for reporting this issue, it will be fixed in the next release.

**Comment by matteo-prosperi** [comment]
This is addressed in https://github.com/aws/aws-tools-for-powershell/pull/71 and scheduled for the upcoming release.

**Comment by matteo-prosperi** [comment]
Hello,
this issue was addressed. I am closing it, please reopen it in case you experience further issues.
Thanks
