### ISSUE TITLE
Add ValidateSet to Install-AWSToolsModule -Name property

### ISSUE THREAD

**Issue by tlindsay42** [aws/aws-tools-for-powershell#72]
**Expected Behavior**

The `Name` parameter of the `Install-AWSToolsModule` cmdlet should use the ValidateSet functionality to provide tab completion of values and more helpful error messages for invalid values.

**Current Behavior**

The `Name` parameter of the `Install-AWSToolsModule` cmdlet does not feature tab completion provided by ValidateSet. Also, the resulting error from invalid values is not very helpful.

```powershell
PS C:\> Install-AWSToolsModule -Name 'AWS.Tools.*'
ForEach-Object : A positional parameter cannot be found that accepts argument 'System.Collections.Hashtable'.
At ~\Documents\WindowsPowerShell\Modules\AWS.Tools.Installer\1.0.0.0\AWS.Tools.Installer.psm1:250
char:37
+ ... s = $Name | ForEach-Object { Find-Module -Name $_ $findModuleParams @ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.ForEachObjectCommand
```

**Possible Solution**

Add a ValidateSet to the `Name` parameter of the `Install-AWSToolsModule` cmdlet.

**Context**

I had to review the Examples to understand what the valid values were.

```powershell
PS C:\> man Install-AWSToolsModule -Examples

NAME
    Install-AWSToolsModule

SYNOPSIS
    Install AWS.Tools modules.


    -------------------------- EXAMPLE 1 --------------------------

    PS C:\>Install-AWSToolsModule EC2,S3 -RequiredVersion 4.0.0.0

    This example installs version 4.0.0.0 of AWS.Tools.EC2, AWS.Tools.S3 and their dependencies.
```

**Your Environment**

Include as many relevant details about the environment where the bug was discovered.
* Affected module (_AWSPowerShell_, _AWSPowerShell.NetCore_ or _AWS.Tools.*_): AWS.Tools.Installer
* Module version as reported by `Get-AWSPowerShellVersion`: 1.0.0.0 (NOTE: I haven't installed AWS.Tools.Common yet on my Windows PowerShell 5.1 version yet, so `Get-AWSPowerShellVersion` isn't available, so you may want to adjust the suggestion here)

```powershell
(Get-Module -Name 'AWS.Tools.Installer').Version

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0
```

* Operating System and version as reported by `$PSVersionTable.OS`: Microsoft Windows 10.0.17763 (NOTE: `$PSVersionTable.OS` is not a valid property in Windows PowerShell, so I had to run this from my PowerShell 6.2 instance)
* PowerShell version as reported by `$PSVersionTable.PSEdition`: Desktop

**Comment by matteo-prosperi** [comment]
Hi. Thanks for opening this issue.
We didn't create a validated set for the `Name` parameter because it would require updating the `AWS.Tools.Installer` module every time we add a new `AWS.Tools` module. Also a user would need to update `AWS.Tools.Installer` first in order to be able to use it to install other modules.
An alternative solution would be to create a completer script like https://github.com/aws/aws-tools-for-powershell/blob/master/modules/ModularAWSPowerShell/AWS.Tools.Common.Completers.psm1.
