### ISSUE TITLE
Question - When will tools support IMPORT changesets

### ISSUE THREAD

**Issue by fireflycons** [aws/aws-tools-for-powershell#76]
Or at least package with the version of AWSSDK.CloudFormation.dll that does?

Thanks

**Comment by matteo-prosperi** [comment]
Hello.
I think you are referring to the following CloudFormation feature:
```
The Resource Import feature enables customers to import existing AWS resources into new or existing CloudFormation Stacks.
```

The feature is included in the .NET SDK 3.3.628.0 which will be included in the next release of AWS Tools for PowerShell

**Comment by matteo-prosperi** [comment]
Closing. Feel free to reopen in case after the next release you have issues with the feature in question.
