### ISSUE TITLE
Get-EC2EbsEncryptionByDefault timing out, appears broken

### ISSUE THREAD

**Issue by markdjones82** [aws/aws-tools-for-powershell#78]
Provide a general summary of the issue in the Title above.

When running Get-EC2EbsEncryptionByDefault it times out and does not return results.

If you're describing a bug, tell us what should happen. If you're suggesting a change/improvement, tell us how it should work.

Timeout

If describing a bug, tell us what happens instead of the expected behavior.
Include full errors, uncaught exceptions, stack traces, and relevant logs.
If service responses are relevant, please include Fiddler-captured wirelogs.
If suggesting a change/improvement, explain the difference from current behavior.

**Possible Solution**

Not required, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.

**Steps to Reproduce (for bugs)**

Provide a self-contained, concise snippet of code that can be inserted into a PowerShell session to replicate the bug. Including business logic or unrelated code makes diagnosis more difficult.

**Context**

How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

**Your Environment**

Include as many relevant details about the environment where the bug was discovered.
* Affected module (_AWSPowerShell_, _AWSPowerShell.NetCore_ or _AWS.Tools.*_): 
* Module version as reported by `Get-AWSPowerShellVersion`: 
* Operating System and version as reported by `$PSVersionTable.OS`: 
* PowerShell version as reported by `$PSVersionTable.PSEdition`:

**Comment by ketanbhut** [comment]
Hi - I cannot reproduce the issue. Can you tell us more about how you get timeout? Are you able to reach EC2 endpoint? 

test-netconnection -computer ec2.<region>.amazonaws.com -port 443

**Comment by markdjones82** [comment]
Yeah, I realized it could be a change in our proxy issue here. I will close this out and troubleshoot further. Thanks.
