### ISSUE TITLE
Test-CFNStack throwing error for non-existent stack name

### ISSUE THREAD

**Issue by johnwc** [aws/aws-tools-for-powershell#9]
I'm using AWSPowershell 3.3.283.0 and the Test-CFNStack is throwing a error when the stack does not exist. Per this [improvements for aws cloudformation article](https://aws.amazon.com/blogs/developer/improvements-for-aws-cloudformation-and-amazon-cloudwatch-in-the-aws-tools-for-powershell-modules/), it says that you should use Test-CFNStack to see if a stack exists or not, and that it will not throw a error like it does for Get-CFNStack.

Also, it seems that most of, if not all, do not follow the ErrorAction parameter. If I set it to SilentlyContinue, it still throws a error. If I set ErrorVariable, nothing it gets applied to the variable.

**Comment by matteo-prosperi** [comment]
Could you please test this with version 3.3.485.0 or later of AWSPowerShell? In version [3.3.485.0](https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md#334850-2019-03-28) we addressed this issue:
```
* Amazon CloudFormation
  - [Breaking Change] Fixed a bug in Test-CFNStack causing the cmdlet to throw an exception instead of returning false, as described in the documentation, when the stack doesn't exist.
```

**Comment by matteo-prosperi** [comment]
Closing. Please reopen in case the latest version of the module is still affected by the issue.
