### ISSUE TITLE
Unable to add description to security group ingress/egress

### ISSUE THREAD

**Issue by dcopestake** [aws/aws-tools-for-powershell#96]
The ability to add descriptions to security group ingress/egress rules was added quite a while ago, and [seems to be possible using the AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html), but [still doesn't seem possible via the PowerShell cmdlets](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2IpPermission.html&tocid=Amazon_EC2_Model_IpPermission) as far as I can see?

**Expected Behavior**

I should be able to specify a `Description` property on `Amazon.EC2.Model.IpPermission` when using both `Grant-EC2SecurityGroupIngress` and `Grant-EC2SecurityGroupEgress`.

**Current Behavior**

It does not currently seem possible to specify a description when granting a rule.

**Comment by matteo-prosperi** [comment]
Hello,
you should be able to specify a description for the `Ipv4Ranges`, `Ipv6Ranges`, `PrefixListIds` and `UserIdGroupPairs`.
Updating `Example 1` from the [docs](https://docs.aws.amazon.com/powershell/latest/reference/items/Grant-EC2SecurityGroupIngress.html):
```
PS C:\> $ip1 = @{ IpProtocol="tcp"; FromPort="22"; ToPort="22"; Ipv4Ranges=[Amazon.EC2.Model.IpRange]@{CidrIp="203.0.113.25/32"; Description='foo'} }
PS C:\> $ip2 = @{ IpProtocol="tcp"; FromPort="3389"; ToPort="3389"; Ipv4Ranges=[Amazon.EC2.Model.IpRange]@{CidrIp="203.0.113.25/32"; Description='bar'} }

PS C:\> Grant-EC2SecurityGroupIngress -GroupId sg-12345678 -IpPermission @( $ip1, $ip2 )
```

**Comment by dcopestake** [comment]
Ah okay, thanks @matteo-prosperi, I was expecting the description to be at the root but didn't think to look further down.
